/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetEntitiesResponse,
  GetNetworksResponse,
  GetTokensResponse,
  Network,
  StakingNetwork,
  StakingOptionsResponse,
  StakingToken,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetEntitiesResponseFromJSON,
    GetEntitiesResponseToJSON,
    GetNetworksResponseFromJSON,
    GetNetworksResponseToJSON,
    GetTokensResponseFromJSON,
    GetTokensResponseToJSON,
    NetworkFromJSON,
    NetworkToJSON,
    StakingNetworkFromJSON,
    StakingNetworkToJSON,
    StakingOptionsResponseFromJSON,
    StakingOptionsResponseToJSON,
    StakingTokenFromJSON,
    StakingTokenToJSON,
} from '../models/index';

export interface GetEntitiesRequest {
    active?: string;
    entityType?: string;
}

export interface GetNetworksRequest {
    network?: Network;
    testnet?: GetNetworksTestnetEnum;
}

export interface GetStakingOptionsRequest {
    network?: StakingNetwork;
    token?: StakingToken;
    protocol?: GetStakingOptionsProtocolEnum;
    status?: GetStakingOptionsStatusEnum;
    testnet?: GetStakingOptionsTestnetEnum;
}

export interface GetTokensRequest {
    network?: StakingNetwork;
    symbol?: StakingToken;
    testnet?: GetTokensTestnetEnum;
    tokenAddress?: string;
}

/**
 * APIInfoApi - interface
 * 
 * @export
 * @interface APIInfoApiInterface
 */
export interface APIInfoApiInterface {
    /**
     * Returns a list of validator entities/organizations with their associated validators
     * @summary Get entities (validator organizations)
     * @param {string} [active] Filter by active entities
     * @param {string} [entityType] Filter by entity type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIInfoApiInterface
     */
    getEntitiesRaw(requestParameters: GetEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEntitiesResponse>>;

    /**
     * Returns a list of validator entities/organizations with their associated validators
     * Get entities (validator organizations)
     */
    getEntities(requestParameters: GetEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEntitiesResponse>;

    /**
     * Returns a list of all supported blockchain networks with their protocols, tokens, and required parameters
     * @summary Get supported networks
     * @param {Network} [network] Filter by network name
     * @param {'true' | 'false'} [testnet] Filter testnet/mainnet networks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIInfoApiInterface
     */
    getNetworksRaw(requestParameters: GetNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNetworksResponse>>;

    /**
     * Returns a list of all supported blockchain networks with their protocols, tokens, and required parameters
     * Get supported networks
     */
    getNetworks(requestParameters: GetNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNetworksResponse>;

    /**
     * Returns detailed staking options with network, token, protocol combinations and their requirements
     * @summary Get staking options
     * @param {StakingNetwork} [network] Filter by network name
     * @param {StakingToken} [token] Filter by token symbol
     * @param {'native' | 'eigenlayer' | 'morpho'} [protocol] Filter by protocol
     * @param {'LIVE' | 'PLANNED'} [status] Filter by staking status
     * @param {'true' | 'false'} [testnet] Filter by testnet/mainnet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIInfoApiInterface
     */
    getStakingOptionsRaw(requestParameters: GetStakingOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StakingOptionsResponse>>;

    /**
     * Returns detailed staking options with network, token, protocol combinations and their requirements
     * Get staking options
     */
    getStakingOptions(requestParameters: GetStakingOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StakingOptionsResponse>;

    /**
     * Returns a list of all supported tokens across all networks with their configuration details
     * @summary Get supported tokens
     * @param {StakingNetwork} [network] Filter by network name
     * @param {StakingToken} [symbol] Filter by token symbol
     * @param {'true' | 'false'} [testnet] Filter testnet/mainnet tokens
     * @param {string} [tokenAddress] Filter by token contract address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIInfoApiInterface
     */
    getTokensRaw(requestParameters: GetTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTokensResponse>>;

    /**
     * Returns a list of all supported tokens across all networks with their configuration details
     * Get supported tokens
     */
    getTokens(requestParameters: GetTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTokensResponse>;

}

/**
 * 
 */
export class APIInfoApi extends runtime.BaseAPI implements APIInfoApiInterface {

    /**
     * Returns a list of validator entities/organizations with their associated validators
     * Get entities (validator organizations)
     */
    async getEntitiesRaw(requestParameters: GetEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEntitiesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['entityType'] != null) {
            queryParameters['entityType'] = requestParameters['entityType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/info/entities`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEntitiesResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of validator entities/organizations with their associated validators
     * Get entities (validator organizations)
     */
    async getEntities(requestParameters: GetEntitiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEntitiesResponse> {
        const response = await this.getEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all supported blockchain networks with their protocols, tokens, and required parameters
     * Get supported networks
     */
    async getNetworksRaw(requestParameters: GetNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNetworksResponse>> {
        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['testnet'] != null) {
            queryParameters['testnet'] = requestParameters['testnet'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/info/networks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNetworksResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of all supported blockchain networks with their protocols, tokens, and required parameters
     * Get supported networks
     */
    async getNetworks(requestParameters: GetNetworksRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNetworksResponse> {
        const response = await this.getNetworksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns detailed staking options with network, token, protocol combinations and their requirements
     * Get staking options
     */
    async getStakingOptionsRaw(requestParameters: GetStakingOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StakingOptionsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        if (requestParameters['protocol'] != null) {
            queryParameters['protocol'] = requestParameters['protocol'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['testnet'] != null) {
            queryParameters['testnet'] = requestParameters['testnet'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/info/staking-options`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StakingOptionsResponseFromJSON(jsonValue));
    }

    /**
     * Returns detailed staking options with network, token, protocol combinations and their requirements
     * Get staking options
     */
    async getStakingOptions(requestParameters: GetStakingOptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StakingOptionsResponse> {
        const response = await this.getStakingOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all supported tokens across all networks with their configuration details
     * Get supported tokens
     */
    async getTokensRaw(requestParameters: GetTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTokensResponse>> {
        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['symbol'] != null) {
            queryParameters['symbol'] = requestParameters['symbol'];
        }

        if (requestParameters['testnet'] != null) {
            queryParameters['testnet'] = requestParameters['testnet'];
        }

        if (requestParameters['tokenAddress'] != null) {
            queryParameters['tokenAddress'] = requestParameters['tokenAddress'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/info/tokens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTokensResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of all supported tokens across all networks with their configuration details
     * Get supported tokens
     */
    async getTokens(requestParameters: GetTokensRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTokensResponse> {
        const response = await this.getTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetNetworksTestnetEnum = {
    True: 'true',
    False: 'false'
} as const;
export type GetNetworksTestnetEnum = typeof GetNetworksTestnetEnum[keyof typeof GetNetworksTestnetEnum];
/**
 * @export
 */
export const GetStakingOptionsProtocolEnum = {
    Native: 'native',
    Eigenlayer: 'eigenlayer',
    Morpho: 'morpho'
} as const;
export type GetStakingOptionsProtocolEnum = typeof GetStakingOptionsProtocolEnum[keyof typeof GetStakingOptionsProtocolEnum];
/**
 * @export
 */
export const GetStakingOptionsStatusEnum = {
    Live: 'LIVE',
    Planned: 'PLANNED'
} as const;
export type GetStakingOptionsStatusEnum = typeof GetStakingOptionsStatusEnum[keyof typeof GetStakingOptionsStatusEnum];
/**
 * @export
 */
export const GetStakingOptionsTestnetEnum = {
    True: 'true',
    False: 'false'
} as const;
export type GetStakingOptionsTestnetEnum = typeof GetStakingOptionsTestnetEnum[keyof typeof GetStakingOptionsTestnetEnum];
/**
 * @export
 */
export const GetTokensTestnetEnum = {
    True: 'true',
    False: 'false'
} as const;
export type GetTokensTestnetEnum = typeof GetTokensTestnetEnum[keyof typeof GetTokensTestnetEnum];
