/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DailyRewardsResponse,
  DelegationHistoryResponse,
  ErrorResponse,
  GetStakingPositions200Response,
  GetValidators200Response,
  RestakingDelegateRequest,
  RestakingDepositRequest,
  RestakingNetwork,
  RestakingToken,
  RestakingUndelegateRequest,
  RestakingUnstakeRequest,
  RestakingWithdrawRequest,
  RewardHistoryResponse,
  TransactionsResponse,
} from '../models/index';
import {
    DailyRewardsResponseFromJSON,
    DailyRewardsResponseToJSON,
    DelegationHistoryResponseFromJSON,
    DelegationHistoryResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetStakingPositions200ResponseFromJSON,
    GetStakingPositions200ResponseToJSON,
    GetValidators200ResponseFromJSON,
    GetValidators200ResponseToJSON,
    RestakingDelegateRequestFromJSON,
    RestakingDelegateRequestToJSON,
    RestakingDepositRequestFromJSON,
    RestakingDepositRequestToJSON,
    RestakingNetworkFromJSON,
    RestakingNetworkToJSON,
    RestakingTokenFromJSON,
    RestakingTokenToJSON,
    RestakingUndelegateRequestFromJSON,
    RestakingUndelegateRequestToJSON,
    RestakingUnstakeRequestFromJSON,
    RestakingUnstakeRequestToJSON,
    RestakingWithdrawRequestFromJSON,
    RestakingWithdrawRequestToJSON,
    RewardHistoryResponseFromJSON,
    RewardHistoryResponseToJSON,
    TransactionsResponseFromJSON,
    TransactionsResponseToJSON,
} from '../models/index';

export interface CreateRestakingDelegationRequest {
    restakingDelegateRequest: RestakingDelegateRequest;
}

export interface CreateRestakingDepositRequest {
    restakingDepositRequest: RestakingDepositRequest;
}

export interface CreateRestakingUndelegationRequest {
    restakingUndelegateRequest: RestakingUndelegateRequest;
}

export interface CreateRestakingUnstakeRequest {
    restakingUnstakeRequest: RestakingUnstakeRequest;
}

export interface CreateRestakingWithdrawalRequest {
    restakingWithdrawRequest: RestakingWithdrawRequest;
}

export interface GetRestakingDailyRewardsRequest {
    operatorId: string;
    startDate?: string;
    endDate?: string;
    limit?: string;
}

export interface GetRestakingDelegationHistoryRequest {
    validatorId: string;
    eventType?: string;
    limit?: string;
}

export interface GetRestakingPositionsRequest {
    staker: string;
    network: RestakingNetwork;
    operator: string;
    token: RestakingToken;
}

export interface GetRestakingRewardHistoryRequest {
    validatorId: string;
    limit?: string;
}

/**
 * EigenlayerRestakingApi - interface
 * 
 * @export
 * @interface EigenlayerRestakingApiInterface
 */
export interface EigenlayerRestakingApiInterface {
    /**
     *  Creates unsigned transactions to delegate deposited assets to an EigenLayer operator.  Call this after depositing tokens via /deposit. Note: You can only be delegated to one operator at a time.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * @summary Create restaking delegation transactions
     * @param {RestakingDelegateRequest} restakingDelegateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    createRestakingDelegationRaw(requestParameters: CreateRestakingDelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions to delegate deposited assets to an EigenLayer operator.  Call this after depositing tokens via /deposit. Note: You can only be delegated to one operator at a time.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * Create restaking delegation transactions
     */
    createRestakingDelegation(requestParameters: CreateRestakingDelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     *  Creates unsigned transactions to deposit LST/EIGEN tokens into an EigenLayer strategy.  This endpoint returns approve + depositIntoStrategy transactions. After depositing, you must separately call /delegate to delegate to an operator.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * @summary Create restaking deposit transactions
     * @param {RestakingDepositRequest} restakingDepositRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    createRestakingDepositRaw(requestParameters: CreateRestakingDepositRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions to deposit LST/EIGEN tokens into an EigenLayer strategy.  This endpoint returns approve + depositIntoStrategy transactions. After depositing, you must separately call /delegate to delegate to an operator.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking deposit transactions
     */
    createRestakingDeposit(requestParameters: CreateRestakingDepositRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     *  Creates unsigned transactions to undelegate from an EigenLayer operator.  **Important:** This undelegates ALL deposited assets and queues them for withdrawal. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * @summary Create restaking undelegation transactions
     * @param {RestakingUndelegateRequest} restakingUndelegateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    createRestakingUndelegationRaw(requestParameters: CreateRestakingUndelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions to undelegate from an EigenLayer operator.  **Important:** This undelegates ALL deposited assets and queues them for withdrawal. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * Create restaking undelegation transactions
     */
    createRestakingUndelegation(requestParameters: CreateRestakingUndelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     *  Creates unsigned transactions to queue a partial withdrawal on EigenLayer while remaining delegated to an operator.  Unlike /undelegate which withdraws ALL assets and undelegates, /unstake allows you to withdraw a specific amount of a single token while maintaining your delegation to the operator. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * @summary Create restaking unstake transactions
     * @param {RestakingUnstakeRequest} restakingUnstakeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    createRestakingUnstakeRaw(requestParameters: CreateRestakingUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions to queue a partial withdrawal on EigenLayer while remaining delegated to an operator.  Unlike /undelegate which withdraws ALL assets and undelegates, /unstake allows you to withdraw a specific amount of a single token while maintaining your delegation to the operator. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking unstake transactions
     */
    createRestakingUnstake(requestParameters: CreateRestakingUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     *  Creates unsigned transactions to complete queued withdrawals on EigenLayer.  Call this after the withdrawal delay period has passed following an /undelegate or /unstake call. Use GET /restaking/stakes to check withdrawal status.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * @summary Create restaking withdrawal transactions
     * @param {RestakingWithdrawRequest} restakingWithdrawRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    createRestakingWithdrawalRaw(requestParameters: CreateRestakingWithdrawalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions to complete queued withdrawals on EigenLayer.  Call this after the withdrawal delay period has passed following an /undelegate or /unstake call. Use GET /restaking/stakes to check withdrawal status.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking withdrawal transactions
     */
    createRestakingWithdrawal(requestParameters: CreateRestakingWithdrawalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     * Returns the restaking daily aggregated rewards (total rewards, delegator rewards, commission) for a specific operator. The protocol/network is automatically determined from the operatorId.
     * @summary Get restaking daily reward history for an operator
     * @param {string} operatorId 
     * @param {string} [startDate] 
     * @param {string} [endDate] 
     * @param {string} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    getRestakingDailyRewardsRaw(requestParameters: GetRestakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyRewardsResponse>>;

    /**
     * Returns the restaking daily aggregated rewards (total rewards, delegator rewards, commission) for a specific operator. The protocol/network is automatically determined from the operatorId.
     * Get restaking daily reward history for an operator
     */
    getRestakingDailyRewards(requestParameters: GetRestakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyRewardsResponse>;

    /**
     * Returns the restaking delegation transaction history (delegate, undelegate events) for a specific operator
     * @summary Get restaking delegation transaction history for an operator
     * @param {string} validatorId 
     * @param {string} [eventType] 
     * @param {string} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    getRestakingDelegationHistoryRaw(requestParameters: GetRestakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DelegationHistoryResponse>>;

    /**
     * Returns the restaking delegation transaction history (delegate, undelegate events) for a specific operator
     * Get restaking delegation transaction history for an operator
     */
    getRestakingDelegationHistory(requestParameters: GetRestakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DelegationHistoryResponse>;

    /**
     * Returns a list of restaking operators with protocol and network information
     * @summary Get restaking operators
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    getRestakingOperatorsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetValidators200Response>>;

    /**
     * Returns a list of restaking operators with protocol and network information
     * Get restaking operators
     */
    getRestakingOperators(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetValidators200Response>;

    /**
     *  Returns the current restaking positions for an address on EigenLayer.  ## Supported Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** |  ## Supported Tokens (optional filter)  | Token | |-------| | **EIGEN** | | **STETH** | | **RETH** | | **CBETH** | 
     * @summary Get restaking positions
     * @param {string} staker The staker address to query restaking stakes for
     * @param {RestakingNetwork} network The blockchain network to query
     * @param {string} operator The operator address to filter by
     * @param {RestakingToken} token The token to filter restaking stakes for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    getRestakingPositionsRaw(requestParameters: GetRestakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStakingPositions200Response>>;

    /**
     *  Returns the current restaking positions for an address on EigenLayer.  ## Supported Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** |  ## Supported Tokens (optional filter)  | Token | |-------| | **EIGEN** | | **STETH** | | **RETH** | | **CBETH** | 
     * Get restaking positions
     */
    getRestakingPositions(requestParameters: GetRestakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStakingPositions200Response>;

    /**
     * Returns the restaking reward withdrawal transaction history for a specific operator
     * @summary Get restaking reward withdrawal transaction history for an operator
     * @param {string} validatorId 
     * @param {string} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EigenlayerRestakingApiInterface
     */
    getRestakingRewardHistoryRaw(requestParameters: GetRestakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardHistoryResponse>>;

    /**
     * Returns the restaking reward withdrawal transaction history for a specific operator
     * Get restaking reward withdrawal transaction history for an operator
     */
    getRestakingRewardHistory(requestParameters: GetRestakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardHistoryResponse>;

}

/**
 * 
 */
export class EigenlayerRestakingApi extends runtime.BaseAPI implements EigenlayerRestakingApiInterface {

    /**
     *  Creates unsigned transactions to delegate deposited assets to an EigenLayer operator.  Call this after depositing tokens via /deposit. Note: You can only be delegated to one operator at a time.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * Create restaking delegation transactions
     */
    async createRestakingDelegationRaw(requestParameters: CreateRestakingDelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['restakingDelegateRequest'] == null) {
            throw new runtime.RequiredError(
                'restakingDelegateRequest',
                'Required parameter "restakingDelegateRequest" was null or undefined when calling createRestakingDelegation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/delegate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestakingDelegateRequestToJSON(requestParameters['restakingDelegateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions to delegate deposited assets to an EigenLayer operator.  Call this after depositing tokens via /deposit. Note: You can only be delegated to one operator at a time.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * Create restaking delegation transactions
     */
    async createRestakingDelegation(requestParameters: CreateRestakingDelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createRestakingDelegationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Creates unsigned transactions to deposit LST/EIGEN tokens into an EigenLayer strategy.  This endpoint returns approve + depositIntoStrategy transactions. After depositing, you must separately call /delegate to delegate to an operator.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking deposit transactions
     */
    async createRestakingDepositRaw(requestParameters: CreateRestakingDepositRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['restakingDepositRequest'] == null) {
            throw new runtime.RequiredError(
                'restakingDepositRequest',
                'Required parameter "restakingDepositRequest" was null or undefined when calling createRestakingDeposit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/deposit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestakingDepositRequestToJSON(requestParameters['restakingDepositRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions to deposit LST/EIGEN tokens into an EigenLayer strategy.  This endpoint returns approve + depositIntoStrategy transactions. After depositing, you must separately call /delegate to delegate to an operator.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking deposit transactions
     */
    async createRestakingDeposit(requestParameters: CreateRestakingDepositRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createRestakingDepositRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Creates unsigned transactions to undelegate from an EigenLayer operator.  **Important:** This undelegates ALL deposited assets and queues them for withdrawal. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * Create restaking undelegation transactions
     */
    async createRestakingUndelegationRaw(requestParameters: CreateRestakingUndelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['restakingUndelegateRequest'] == null) {
            throw new runtime.RequiredError(
                'restakingUndelegateRequest',
                'Required parameter "restakingUndelegateRequest" was null or undefined when calling createRestakingUndelegation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/undelegate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestakingUndelegateRequestToJSON(requestParameters['restakingUndelegateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions to undelegate from an EigenLayer operator.  **Important:** This undelegates ALL deposited assets and queues them for withdrawal. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** | 
     * Create restaking undelegation transactions
     */
    async createRestakingUndelegation(requestParameters: CreateRestakingUndelegationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createRestakingUndelegationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Creates unsigned transactions to queue a partial withdrawal on EigenLayer while remaining delegated to an operator.  Unlike /undelegate which withdraws ALL assets and undelegates, /unstake allows you to withdraw a specific amount of a single token while maintaining your delegation to the operator. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking unstake transactions
     */
    async createRestakingUnstakeRaw(requestParameters: CreateRestakingUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['restakingUnstakeRequest'] == null) {
            throw new runtime.RequiredError(
                'restakingUnstakeRequest',
                'Required parameter "restakingUnstakeRequest" was null or undefined when calling createRestakingUnstake().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/unstake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestakingUnstakeRequestToJSON(requestParameters['restakingUnstakeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions to queue a partial withdrawal on EigenLayer while remaining delegated to an operator.  Unlike /undelegate which withdraws ALL assets and undelegates, /unstake allows you to withdraw a specific amount of a single token while maintaining your delegation to the operator. After the withdrawal delay period (~7 days on mainnet), call /withdraw to complete the withdrawal.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking unstake transactions
     */
    async createRestakingUnstake(requestParameters: CreateRestakingUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createRestakingUnstakeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Creates unsigned transactions to complete queued withdrawals on EigenLayer.  Call this after the withdrawal delay period has passed following an /undelegate or /unstake call. Use GET /restaking/stakes to check withdrawal status.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking withdrawal transactions
     */
    async createRestakingWithdrawalRaw(requestParameters: CreateRestakingWithdrawalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['restakingWithdrawRequest'] == null) {
            throw new runtime.RequiredError(
                'restakingWithdrawRequest',
                'Required parameter "restakingWithdrawRequest" was null or undefined when calling createRestakingWithdrawal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/withdraw`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestakingWithdrawRequestToJSON(requestParameters['restakingWithdrawRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions to complete queued withdrawals on EigenLayer.  Call this after the withdrawal delay period has passed following an /undelegate or /unstake call. Use GET /restaking/stakes to check withdrawal status.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **EIGEN** | ethereum | | **STETH** | ethereum | | **RETH** | ethereum | | **CBETH** | ethereum | 
     * Create restaking withdrawal transactions
     */
    async createRestakingWithdrawal(requestParameters: CreateRestakingWithdrawalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createRestakingWithdrawalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the restaking daily aggregated rewards (total rewards, delegator rewards, commission) for a specific operator. The protocol/network is automatically determined from the operatorId.
     * Get restaking daily reward history for an operator
     */
    async getRestakingDailyRewardsRaw(requestParameters: GetRestakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyRewardsResponse>> {
        if (requestParameters['operatorId'] == null) {
            throw new runtime.RequiredError(
                'operatorId',
                'Required parameter "operatorId" was null or undefined when calling getRestakingDailyRewards().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/daily-reward-history/{operatorId}`.replace(`{${"operatorId"}}`, encodeURIComponent(String(requestParameters['operatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DailyRewardsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the restaking daily aggregated rewards (total rewards, delegator rewards, commission) for a specific operator. The protocol/network is automatically determined from the operatorId.
     * Get restaking daily reward history for an operator
     */
    async getRestakingDailyRewards(requestParameters: GetRestakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyRewardsResponse> {
        const response = await this.getRestakingDailyRewardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the restaking delegation transaction history (delegate, undelegate events) for a specific operator
     * Get restaking delegation transaction history for an operator
     */
    async getRestakingDelegationHistoryRaw(requestParameters: GetRestakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DelegationHistoryResponse>> {
        if (requestParameters['validatorId'] == null) {
            throw new runtime.RequiredError(
                'validatorId',
                'Required parameter "validatorId" was null or undefined when calling getRestakingDelegationHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['eventType'] != null) {
            queryParameters['eventType'] = requestParameters['eventType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/delegation-tx-history/{validatorId}`.replace(`{${"validatorId"}}`, encodeURIComponent(String(requestParameters['validatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DelegationHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Returns the restaking delegation transaction history (delegate, undelegate events) for a specific operator
     * Get restaking delegation transaction history for an operator
     */
    async getRestakingDelegationHistory(requestParameters: GetRestakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DelegationHistoryResponse> {
        const response = await this.getRestakingDelegationHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of restaking operators with protocol and network information
     * Get restaking operators
     */
    async getRestakingOperatorsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetValidators200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/operators`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetValidators200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of restaking operators with protocol and network information
     * Get restaking operators
     */
    async getRestakingOperators(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetValidators200Response> {
        const response = await this.getRestakingOperatorsRaw(initOverrides);
        return await response.value();
    }

    /**
     *  Returns the current restaking positions for an address on EigenLayer.  ## Supported Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** |  ## Supported Tokens (optional filter)  | Token | |-------| | **EIGEN** | | **STETH** | | **RETH** | | **CBETH** | 
     * Get restaking positions
     */
    async getRestakingPositionsRaw(requestParameters: GetRestakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStakingPositions200Response>> {
        if (requestParameters['staker'] == null) {
            throw new runtime.RequiredError(
                'staker',
                'Required parameter "staker" was null or undefined when calling getRestakingPositions().'
            );
        }

        if (requestParameters['network'] == null) {
            throw new runtime.RequiredError(
                'network',
                'Required parameter "network" was null or undefined when calling getRestakingPositions().'
            );
        }

        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling getRestakingPositions().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getRestakingPositions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['staker'] != null) {
            queryParameters['staker'] = requestParameters['staker'];
        }

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/stakes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStakingPositions200ResponseFromJSON(jsonValue));
    }

    /**
     *  Returns the current restaking positions for an address on EigenLayer.  ## Supported Networks  | Network | |---------| | **ethereum** | | **ethereum-hoodi-testnet** |  ## Supported Tokens (optional filter)  | Token | |-------| | **EIGEN** | | **STETH** | | **RETH** | | **CBETH** | 
     * Get restaking positions
     */
    async getRestakingPositions(requestParameters: GetRestakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStakingPositions200Response> {
        const response = await this.getRestakingPositionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the restaking reward withdrawal transaction history for a specific operator
     * Get restaking reward withdrawal transaction history for an operator
     */
    async getRestakingRewardHistoryRaw(requestParameters: GetRestakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardHistoryResponse>> {
        if (requestParameters['validatorId'] == null) {
            throw new runtime.RequiredError(
                'validatorId',
                'Required parameter "validatorId" was null or undefined when calling getRestakingRewardHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/restaking/withdraw-rewards-tx-history/{validatorId}`.replace(`{${"validatorId"}}`, encodeURIComponent(String(requestParameters['validatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Returns the restaking reward withdrawal transaction history for a specific operator
     * Get restaking reward withdrawal transaction history for an operator
     */
    async getRestakingRewardHistory(requestParameters: GetRestakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardHistoryResponse> {
        const response = await this.getRestakingRewardHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
