/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  EthereumCancelStake200Response,
  EthereumCancelStakeRequest,
  EthereumConfirmStake200Response,
  EthereumConfirmStakeRequest,
  EthereumConsolidate200Response,
  EthereumConsolidateRequest,
  EthereumExit202Response,
  EthereumExitRequest,
  EthereumForceExit200Response,
  EthereumForceExitRequest,
  EthereumGetDailyRewardsHistory200Response,
  EthereumGetStakingTxHistory200Response,
  EthereumGetValidators200Response,
  EthereumNetwork,
  EthereumStake200Response,
  EthereumStakeRequest,
  EthereumTopup200Response,
  EthereumTopupRequest,
  EthereumWithdraw200Response,
  EthereumWithdrawRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    EthereumCancelStake200ResponseFromJSON,
    EthereumCancelStake200ResponseToJSON,
    EthereumCancelStakeRequestFromJSON,
    EthereumCancelStakeRequestToJSON,
    EthereumConfirmStake200ResponseFromJSON,
    EthereumConfirmStake200ResponseToJSON,
    EthereumConfirmStakeRequestFromJSON,
    EthereumConfirmStakeRequestToJSON,
    EthereumConsolidate200ResponseFromJSON,
    EthereumConsolidate200ResponseToJSON,
    EthereumConsolidateRequestFromJSON,
    EthereumConsolidateRequestToJSON,
    EthereumExit202ResponseFromJSON,
    EthereumExit202ResponseToJSON,
    EthereumExitRequestFromJSON,
    EthereumExitRequestToJSON,
    EthereumForceExit200ResponseFromJSON,
    EthereumForceExit200ResponseToJSON,
    EthereumForceExitRequestFromJSON,
    EthereumForceExitRequestToJSON,
    EthereumGetDailyRewardsHistory200ResponseFromJSON,
    EthereumGetDailyRewardsHistory200ResponseToJSON,
    EthereumGetStakingTxHistory200ResponseFromJSON,
    EthereumGetStakingTxHistory200ResponseToJSON,
    EthereumGetValidators200ResponseFromJSON,
    EthereumGetValidators200ResponseToJSON,
    EthereumNetworkFromJSON,
    EthereumNetworkToJSON,
    EthereumStake200ResponseFromJSON,
    EthereumStake200ResponseToJSON,
    EthereumStakeRequestFromJSON,
    EthereumStakeRequestToJSON,
    EthereumTopup200ResponseFromJSON,
    EthereumTopup200ResponseToJSON,
    EthereumTopupRequestFromJSON,
    EthereumTopupRequestToJSON,
    EthereumWithdraw200ResponseFromJSON,
    EthereumWithdraw200ResponseToJSON,
    EthereumWithdrawRequestFromJSON,
    EthereumWithdrawRequestToJSON,
} from '../models/index';

export interface EthereumCancelStakeOperationRequest {
    ethereumCancelStakeRequest: EthereumCancelStakeRequest;
}

export interface EthereumConfirmStakeOperationRequest {
    ethereumConfirmStakeRequest: EthereumConfirmStakeRequest;
}

export interface EthereumConsolidateOperationRequest {
    ethereumConsolidateRequest?: EthereumConsolidateRequest;
}

export interface EthereumExitOperationRequest {
    ethereumExitRequest: EthereumExitRequest;
}

export interface EthereumForceExitOperationRequest {
    ethereumForceExitRequest: EthereumForceExitRequest;
}

export interface EthereumGetDailyRewardsHistoryRequest {
    pubkey: string;
    network: EthereumNetwork;
    startDate?: string;
    endDate?: string;
    limit?: string;
}

export interface EthereumGetStakingTxHistoryRequest {
    pubkey: string;
    network: EthereumNetwork;
    eventType?: string;
    limit?: string;
}

export interface EthereumGetValidatorsRequest {
    network: EthereumNetwork;
    state?: EthereumGetValidatorsStateEnum;
    consensusLayerState?: EthereumGetValidatorsConsensusLayerStateEnum;
    indexerState?: EthereumGetValidatorsIndexerStateEnum;
    validatorName?: string;
    validatorPublicKey?: string;
}

export interface EthereumStakeOperationRequest {
    ethereumStakeRequest: EthereumStakeRequest;
    idempotencyKey?: string;
}

export interface EthereumTopupOperationRequest {
    ethereumTopupRequest?: EthereumTopupRequest;
}

export interface EthereumWithdrawOperationRequest {
    ethereumWithdrawRequest: EthereumWithdrawRequest;
}

/**
 * EthereumStakingApi - interface
 * 
 * @export
 * @interface EthereumStakingApiInterface
 */
export interface EthereumStakingApiInterface {
    /**
     * Cancels a pending stake created by `POST /stake` before its deposit transaction is broadcast on chain. Returns 409 when a deposit for that validator has already been observed on chain. Once deposited, funds can be recovered via `POST /exit`.
     * @summary Cancel Pending Stake
     * @param {EthereumCancelStakeRequest} ethereumCancelStakeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumCancelStakeRaw(requestParameters: EthereumCancelStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumCancelStake200Response>>;

    /**
     * Cancels a pending stake created by `POST /stake` before its deposit transaction is broadcast on chain. Returns 409 when a deposit for that validator has already been observed on chain. Once deposited, funds can be recovered via `POST /exit`.
     * Cancel Pending Stake
     */
    ethereumCancelStake(requestParameters: EthereumCancelStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumCancelStake200Response>;

    /**
     * Confirms that the deposit transaction returned from `POST /stake` has been broadcast, promoting the pending stake once the deposit is verified on chain.  The supplied `depositTxHash` is checked on chain: the receipt must exist, have succeeded, have the required number of confirmations, and contain a `DepositEvent` for the supplied `validatorPublicKey`.  This call is optional and idempotent. A background watcher promotes the same pending record automatically once it observes the deposit log on chain, so the result is the same whether or not this endpoint is called.  Pending records that are never confirmed by either path expire automatically and leave no trace.
     * @summary Confirm Stake
     * @param {EthereumConfirmStakeRequest} ethereumConfirmStakeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumConfirmStakeRaw(requestParameters: EthereumConfirmStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumConfirmStake200Response>>;

    /**
     * Confirms that the deposit transaction returned from `POST /stake` has been broadcast, promoting the pending stake once the deposit is verified on chain.  The supplied `depositTxHash` is checked on chain: the receipt must exist, have succeeded, have the required number of confirmations, and contain a `DepositEvent` for the supplied `validatorPublicKey`.  This call is optional and idempotent. A background watcher promotes the same pending record automatically once it observes the deposit log on chain, so the result is the same whether or not this endpoint is called.  Pending records that are never confirmed by either path expire automatically and leave no trace.
     * Confirm Stake
     */
    ethereumConfirmStake(requestParameters: EthereumConfirmStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumConfirmStake200Response>;

    /**
     * Build an unsigned EIP-7251 consolidation request transaction that moves the source validator\'s balance into the target validator and exits the source. Both validators must share the same withdrawal address. Signed by the withdrawal address (msg.sender check on the EIP-7251 predeploy).
     * @summary Transfer Stake (\"Consolidate\")
     * @param {EthereumConsolidateRequest} [ethereumConsolidateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumConsolidateRaw(requestParameters: EthereumConsolidateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumConsolidate200Response>>;

    /**
     * Build an unsigned EIP-7251 consolidation request transaction that moves the source validator\'s balance into the target validator and exits the source. Both validators must share the same withdrawal address. Signed by the withdrawal address (msg.sender check on the EIP-7251 predeploy).
     * Transfer Stake (\"Consolidate\")
     */
    ethereumConsolidate(requestParameters: EthereumConsolidateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumConsolidate200Response>;

    /**
     * Fully exits a validator. The operator holds the validator\'s signing key and uses it to submit the exit request to the network.  This endpoint only does full exits. To take out part of the balance and keep the validator running, use `POST /v1/ethereum-staking/withdraw`. For a full exit the withdrawal address can submit on its own without this API, use `POST /v1/ethereum-staking/force-exit`.  A validator can only exit after it has been active for about 27 hours (256 epochs). The response includes `accepted` and an `exitEpoch`. The `exitEpoch` stays null until the network schedules the exit.
     * @summary Exit (via operator)
     * @param {EthereumExitRequest} ethereumExitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumExitRaw(requestParameters: EthereumExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumExit202Response>>;

    /**
     * Fully exits a validator. The operator holds the validator\'s signing key and uses it to submit the exit request to the network.  This endpoint only does full exits. To take out part of the balance and keep the validator running, use `POST /v1/ethereum-staking/withdraw`. For a full exit the withdrawal address can submit on its own without this API, use `POST /v1/ethereum-staking/force-exit`.  A validator can only exit after it has been active for about 27 hours (256 epochs). The response includes `accepted` and an `exitEpoch`. The `exitEpoch` stays null until the network schedules the exit.
     * Exit (via operator)
     */
    ethereumExit(requestParameters: EthereumExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumExit202Response>;

    /**
     * Returns an unsigned EIP-7002 full-exit transaction (amount = 0) for the withdrawal address to sign and broadcast.  A full exit is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  Unlike `POST /v1/ethereum-staking/exit`, which needs the validator signing key, this transaction is signed by the withdrawal address. Both reach the same result: the validator exits and its balance returns to the withdrawal address. A validator can only exit after it has been active for about 27 hours (256 epochs).
     * @summary Force exit (trustless)
     * @param {EthereumForceExitRequest} ethereumForceExitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumForceExitRaw(requestParameters: EthereumForceExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumForceExit200Response>>;

    /**
     * Returns an unsigned EIP-7002 full-exit transaction (amount = 0) for the withdrawal address to sign and broadcast.  A full exit is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  Unlike `POST /v1/ethereum-staking/exit`, which needs the validator signing key, this transaction is signed by the withdrawal address. Both reach the same result: the validator exits and its balance returns to the withdrawal address. A validator can only exit after it has been active for about 27 hours (256 epochs).
     * Force exit (trustless)
     */
    ethereumForceExit(requestParameters: EthereumForceExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumForceExit200Response>;

    /**
     * Daily reward history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports startDate/endDate (YYYY-MM-DD) and limit filters.
     * @summary Rewards Daily History
     * @param {string} pubkey 48-byte BLS validator public key
     * @param {EthereumNetwork} network Target Ethereum network
     * @param {string} [startDate] Inclusive start date (YYYY-MM-DD)
     * @param {string} [endDate] Inclusive end date (YYYY-MM-DD)
     * @param {string} [limit] Maximum number of items to return. Must be a positive integer.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumGetDailyRewardsHistoryRaw(requestParameters: EthereumGetDailyRewardsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumGetDailyRewardsHistory200Response>>;

    /**
     * Daily reward history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports startDate/endDate (YYYY-MM-DD) and limit filters.
     * Rewards Daily History
     */
    ethereumGetDailyRewardsHistory(requestParameters: EthereumGetDailyRewardsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumGetDailyRewardsHistory200Response>;

    /**
     * Delegation/deposit event history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports eventType and limit filters.
     * @summary Staking Transaction History
     * @param {string} pubkey 48-byte BLS validator public key
     * @param {EthereumNetwork} network Target Ethereum network
     * @param {string} [eventType] Filter by indexer event type
     * @param {string} [limit] Maximum number of items to return. Must be a positive integer.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumGetStakingTxHistoryRaw(requestParameters: EthereumGetStakingTxHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumGetStakingTxHistory200Response>>;

    /**
     * Delegation/deposit event history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports eventType and limit filters.
     * Staking Transaction History
     */
    ethereumGetStakingTxHistory(requestParameters: EthereumGetStakingTxHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumGetStakingTxHistory200Response>;

    /**
     * Lists all Ethereum validators for the authenticated account. Returns the full set when called without filters. Supply any combination of the filters below to narrow the results.  Each validator exposes three separate status fields:  - **`state`**: the high-level lifecycle stage, derived from the beacon state, the indexer status, and recent on-chain exit requests. Progresses through `pending`, `queued`, `activating`, `active`, `exit_pending`, `exiting`, `withdrawn`. - **`consensusLayerState`**: the raw beacon-node state (consensus-spec values such as `active_ongoing`, `active_exiting`, `exited_slashed`, `withdrawal_done`), or `unknown` before the beacon chain has ingested the validator. - **`indexerState`**: the raw staking-data indexer status (`planned`, `active`, `deactivated`), plus `pending` before the deposit is observed on chain and `unknown` when the indexer holds no matching record.  Filters (all optional and combinable): `state`, `consensusLayerState`, `indexerState`, `validatorName` (exact match on the validator label), and `validatorPublicKey` (exact match on the BLS public key).
     * @summary Get Validators
     * @param {EthereumNetwork} network Target Ethereum network
     * @param {'pending' | 'queued' | 'activating' | 'active' | 'exit_pending' | 'exiting' | 'withdrawn'} [state] Filter by state
     * @param {'pending_initialized' | 'pending_queued' | 'active_ongoing' | 'active_exiting' | 'active_slashed' | 'exited_unslashed' | 'exited_slashed' | 'withdrawal_possible' | 'withdrawal_done' | 'unknown'} [consensusLayerState] Filter by beacon (consensus layer) state
     * @param {'planned' | 'active' | 'deactivated' | 'pending' | 'unknown'} [indexerState] Filter by indexer status
     * @param {string} [validatorName] Filter on validator name
     * @param {string} [validatorPublicKey] Filter on public key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumGetValidatorsRaw(requestParameters: EthereumGetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumGetValidators200Response>>;

    /**
     * Lists all Ethereum validators for the authenticated account. Returns the full set when called without filters. Supply any combination of the filters below to narrow the results.  Each validator exposes three separate status fields:  - **`state`**: the high-level lifecycle stage, derived from the beacon state, the indexer status, and recent on-chain exit requests. Progresses through `pending`, `queued`, `activating`, `active`, `exit_pending`, `exiting`, `withdrawn`. - **`consensusLayerState`**: the raw beacon-node state (consensus-spec values such as `active_ongoing`, `active_exiting`, `exited_slashed`, `withdrawal_done`), or `unknown` before the beacon chain has ingested the validator. - **`indexerState`**: the raw staking-data indexer status (`planned`, `active`, `deactivated`), plus `pending` before the deposit is observed on chain and `unknown` when the indexer holds no matching record.  Filters (all optional and combinable): `state`, `consensusLayerState`, `indexerState`, `validatorName` (exact match on the validator label), and `validatorPublicKey` (exact match on the BLS public key).
     * Get Validators
     */
    ethereumGetValidators(requestParameters: EthereumGetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumGetValidators200Response>;

    /**
     * Generates a BLS key, registers it with the validator client, and returns an unsigned deposit transaction.  You can send an `Idempotency-Key` header (UUID) to make retries safe. Repeating the same key with the same body returns the original response without minting a new key.  **Pending stakes:** An account may hold at most 10 pending stakes at a time (deposits that have been generated but whose deposit transaction has not yet been broadcast on chain). Cancel a pending stake with `POST /v1/ethereum-staking/cancel-stake` to free a slot.  **MEV policy:** MEV-Boost configuration (relay allowlist, min-bid threshold, builder participation) is set per-customer at the operator level rather than per-stake. The policy in effect at the time of a proposal slot is the one that applies. Confirm the MEV policy with the assigned operator before staking.
     * @summary Stake
     * @param {EthereumStakeRequest} ethereumStakeRequest 
     * @param {string} [idempotencyKey] Dedup key for safe retries (UUID recommended). Same key + same body replays the original response; same key + different body → 409.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumStakeRaw(requestParameters: EthereumStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumStake200Response>>;

    /**
     * Generates a BLS key, registers it with the validator client, and returns an unsigned deposit transaction.  You can send an `Idempotency-Key` header (UUID) to make retries safe. Repeating the same key with the same body returns the original response without minting a new key.  **Pending stakes:** An account may hold at most 10 pending stakes at a time (deposits that have been generated but whose deposit transaction has not yet been broadcast on chain). Cancel a pending stake with `POST /v1/ethereum-staking/cancel-stake` to free a slot.  **MEV policy:** MEV-Boost configuration (relay allowlist, min-bid threshold, builder participation) is set per-customer at the operator level rather than per-stake. The policy in effect at the time of a proposal slot is the one that applies. Confirm the MEV policy with the assigned operator before staking.
     * Stake
     */
    ethereumStake(requestParameters: EthereumStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumStake200Response>;

    /**
     * Build an unsigned deposit-contract transaction that adds balance to an existing 0x02 (compounding) validator, reusing its pubkey and withdrawal credentials. Useful for pushing balance toward the 2048 ETH cap without provisioning a new validator.
     * @summary Add Stake (\"Topup\")
     * @param {EthereumTopupRequest} [ethereumTopupRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumTopupRaw(requestParameters: EthereumTopupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumTopup200Response>>;

    /**
     * Build an unsigned deposit-contract transaction that adds balance to an existing 0x02 (compounding) validator, reusing its pubkey and withdrawal credentials. Useful for pushing balance toward the 2048 ETH cap without provisioning a new validator.
     * Add Stake (\"Topup\")
     */
    ethereumTopup(requestParameters: EthereumTopupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumTopup200Response>;

    /**
     * Returns an unsigned EIP-7002 partial-withdrawal transaction for the withdrawal address to sign and broadcast. The validator stays active and keeps attesting.  A partial withdrawal is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  `amountWei` must be a whole-gwei multiple of at least 1 gwei, and the remaining balance must stay above 32 ETH. For a full exit, use `POST /v1/ethereum-staking/exit` or `POST /v1/ethereum-staking/force-exit`.  A validator must have been active for at least 256 epochs (about 27 hours) before a withdrawal request is accepted.
     * @summary Withdrawal (trustless)
     * @param {EthereumWithdrawRequest} ethereumWithdrawRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthereumStakingApiInterface
     */
    ethereumWithdrawRaw(requestParameters: EthereumWithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumWithdraw200Response>>;

    /**
     * Returns an unsigned EIP-7002 partial-withdrawal transaction for the withdrawal address to sign and broadcast. The validator stays active and keeps attesting.  A partial withdrawal is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  `amountWei` must be a whole-gwei multiple of at least 1 gwei, and the remaining balance must stay above 32 ETH. For a full exit, use `POST /v1/ethereum-staking/exit` or `POST /v1/ethereum-staking/force-exit`.  A validator must have been active for at least 256 epochs (about 27 hours) before a withdrawal request is accepted.
     * Withdrawal (trustless)
     */
    ethereumWithdraw(requestParameters: EthereumWithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumWithdraw200Response>;

}

/**
 * 
 */
export class EthereumStakingApi extends runtime.BaseAPI implements EthereumStakingApiInterface {

    /**
     * Cancels a pending stake created by `POST /stake` before its deposit transaction is broadcast on chain. Returns 409 when a deposit for that validator has already been observed on chain. Once deposited, funds can be recovered via `POST /exit`.
     * Cancel Pending Stake
     */
    async ethereumCancelStakeRaw(requestParameters: EthereumCancelStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumCancelStake200Response>> {
        if (requestParameters['ethereumCancelStakeRequest'] == null) {
            throw new runtime.RequiredError(
                'ethereumCancelStakeRequest',
                'Required parameter "ethereumCancelStakeRequest" was null or undefined when calling ethereumCancelStake().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/cancel-stake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumCancelStakeRequestToJSON(requestParameters['ethereumCancelStakeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumCancelStake200ResponseFromJSON(jsonValue));
    }

    /**
     * Cancels a pending stake created by `POST /stake` before its deposit transaction is broadcast on chain. Returns 409 when a deposit for that validator has already been observed on chain. Once deposited, funds can be recovered via `POST /exit`.
     * Cancel Pending Stake
     */
    async ethereumCancelStake(requestParameters: EthereumCancelStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumCancelStake200Response> {
        const response = await this.ethereumCancelStakeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Confirms that the deposit transaction returned from `POST /stake` has been broadcast, promoting the pending stake once the deposit is verified on chain.  The supplied `depositTxHash` is checked on chain: the receipt must exist, have succeeded, have the required number of confirmations, and contain a `DepositEvent` for the supplied `validatorPublicKey`.  This call is optional and idempotent. A background watcher promotes the same pending record automatically once it observes the deposit log on chain, so the result is the same whether or not this endpoint is called.  Pending records that are never confirmed by either path expire automatically and leave no trace.
     * Confirm Stake
     */
    async ethereumConfirmStakeRaw(requestParameters: EthereumConfirmStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumConfirmStake200Response>> {
        if (requestParameters['ethereumConfirmStakeRequest'] == null) {
            throw new runtime.RequiredError(
                'ethereumConfirmStakeRequest',
                'Required parameter "ethereumConfirmStakeRequest" was null or undefined when calling ethereumConfirmStake().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/confirm-stake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumConfirmStakeRequestToJSON(requestParameters['ethereumConfirmStakeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumConfirmStake200ResponseFromJSON(jsonValue));
    }

    /**
     * Confirms that the deposit transaction returned from `POST /stake` has been broadcast, promoting the pending stake once the deposit is verified on chain.  The supplied `depositTxHash` is checked on chain: the receipt must exist, have succeeded, have the required number of confirmations, and contain a `DepositEvent` for the supplied `validatorPublicKey`.  This call is optional and idempotent. A background watcher promotes the same pending record automatically once it observes the deposit log on chain, so the result is the same whether or not this endpoint is called.  Pending records that are never confirmed by either path expire automatically and leave no trace.
     * Confirm Stake
     */
    async ethereumConfirmStake(requestParameters: EthereumConfirmStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumConfirmStake200Response> {
        const response = await this.ethereumConfirmStakeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Build an unsigned EIP-7251 consolidation request transaction that moves the source validator\'s balance into the target validator and exits the source. Both validators must share the same withdrawal address. Signed by the withdrawal address (msg.sender check on the EIP-7251 predeploy).
     * Transfer Stake (\"Consolidate\")
     */
    async ethereumConsolidateRaw(requestParameters: EthereumConsolidateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumConsolidate200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/consolidate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumConsolidateRequestToJSON(requestParameters['ethereumConsolidateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumConsolidate200ResponseFromJSON(jsonValue));
    }

    /**
     * Build an unsigned EIP-7251 consolidation request transaction that moves the source validator\'s balance into the target validator and exits the source. Both validators must share the same withdrawal address. Signed by the withdrawal address (msg.sender check on the EIP-7251 predeploy).
     * Transfer Stake (\"Consolidate\")
     */
    async ethereumConsolidate(requestParameters: EthereumConsolidateOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumConsolidate200Response> {
        const response = await this.ethereumConsolidateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fully exits a validator. The operator holds the validator\'s signing key and uses it to submit the exit request to the network.  This endpoint only does full exits. To take out part of the balance and keep the validator running, use `POST /v1/ethereum-staking/withdraw`. For a full exit the withdrawal address can submit on its own without this API, use `POST /v1/ethereum-staking/force-exit`.  A validator can only exit after it has been active for about 27 hours (256 epochs). The response includes `accepted` and an `exitEpoch`. The `exitEpoch` stays null until the network schedules the exit.
     * Exit (via operator)
     */
    async ethereumExitRaw(requestParameters: EthereumExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumExit202Response>> {
        if (requestParameters['ethereumExitRequest'] == null) {
            throw new runtime.RequiredError(
                'ethereumExitRequest',
                'Required parameter "ethereumExitRequest" was null or undefined when calling ethereumExit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/exit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumExitRequestToJSON(requestParameters['ethereumExitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumExit202ResponseFromJSON(jsonValue));
    }

    /**
     * Fully exits a validator. The operator holds the validator\'s signing key and uses it to submit the exit request to the network.  This endpoint only does full exits. To take out part of the balance and keep the validator running, use `POST /v1/ethereum-staking/withdraw`. For a full exit the withdrawal address can submit on its own without this API, use `POST /v1/ethereum-staking/force-exit`.  A validator can only exit after it has been active for about 27 hours (256 epochs). The response includes `accepted` and an `exitEpoch`. The `exitEpoch` stays null until the network schedules the exit.
     * Exit (via operator)
     */
    async ethereumExit(requestParameters: EthereumExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumExit202Response> {
        const response = await this.ethereumExitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns an unsigned EIP-7002 full-exit transaction (amount = 0) for the withdrawal address to sign and broadcast.  A full exit is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  Unlike `POST /v1/ethereum-staking/exit`, which needs the validator signing key, this transaction is signed by the withdrawal address. Both reach the same result: the validator exits and its balance returns to the withdrawal address. A validator can only exit after it has been active for about 27 hours (256 epochs).
     * Force exit (trustless)
     */
    async ethereumForceExitRaw(requestParameters: EthereumForceExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumForceExit200Response>> {
        if (requestParameters['ethereumForceExitRequest'] == null) {
            throw new runtime.RequiredError(
                'ethereumForceExitRequest',
                'Required parameter "ethereumForceExitRequest" was null or undefined when calling ethereumForceExit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/force-exit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumForceExitRequestToJSON(requestParameters['ethereumForceExitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumForceExit200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns an unsigned EIP-7002 full-exit transaction (amount = 0) for the withdrawal address to sign and broadcast.  A full exit is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  Unlike `POST /v1/ethereum-staking/exit`, which needs the validator signing key, this transaction is signed by the withdrawal address. Both reach the same result: the validator exits and its balance returns to the withdrawal address. A validator can only exit after it has been active for about 27 hours (256 epochs).
     * Force exit (trustless)
     */
    async ethereumForceExit(requestParameters: EthereumForceExitOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumForceExit200Response> {
        const response = await this.ethereumForceExitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Daily reward history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports startDate/endDate (YYYY-MM-DD) and limit filters.
     * Rewards Daily History
     */
    async ethereumGetDailyRewardsHistoryRaw(requestParameters: EthereumGetDailyRewardsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumGetDailyRewardsHistory200Response>> {
        if (requestParameters['pubkey'] == null) {
            throw new runtime.RequiredError(
                'pubkey',
                'Required parameter "pubkey" was null or undefined when calling ethereumGetDailyRewardsHistory().'
            );
        }

        if (requestParameters['network'] == null) {
            throw new runtime.RequiredError(
                'network',
                'Required parameter "network" was null or undefined when calling ethereumGetDailyRewardsHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/daily-rewards-history/{pubkey}`.replace(`{${"pubkey"}}`, encodeURIComponent(String(requestParameters['pubkey']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumGetDailyRewardsHistory200ResponseFromJSON(jsonValue));
    }

    /**
     * Daily reward history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports startDate/endDate (YYYY-MM-DD) and limit filters.
     * Rewards Daily History
     */
    async ethereumGetDailyRewardsHistory(requestParameters: EthereumGetDailyRewardsHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumGetDailyRewardsHistory200Response> {
        const response = await this.ethereumGetDailyRewardsHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delegation/deposit event history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports eventType and limit filters.
     * Staking Transaction History
     */
    async ethereumGetStakingTxHistoryRaw(requestParameters: EthereumGetStakingTxHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumGetStakingTxHistory200Response>> {
        if (requestParameters['pubkey'] == null) {
            throw new runtime.RequiredError(
                'pubkey',
                'Required parameter "pubkey" was null or undefined when calling ethereumGetStakingTxHistory().'
            );
        }

        if (requestParameters['network'] == null) {
            throw new runtime.RequiredError(
                'network',
                'Required parameter "network" was null or undefined when calling ethereumGetStakingTxHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['eventType'] = requestParameters['eventType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/staking-tx-history/{pubkey}`.replace(`{${"pubkey"}}`, encodeURIComponent(String(requestParameters['pubkey']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumGetStakingTxHistory200ResponseFromJSON(jsonValue));
    }

    /**
     * Delegation/deposit event history for a single Ethereum validator, sourced from the staking data indexer (BFF). Pubkey must be owned by the caller. Supports eventType and limit filters.
     * Staking Transaction History
     */
    async ethereumGetStakingTxHistory(requestParameters: EthereumGetStakingTxHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumGetStakingTxHistory200Response> {
        const response = await this.ethereumGetStakingTxHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all Ethereum validators for the authenticated account. Returns the full set when called without filters. Supply any combination of the filters below to narrow the results.  Each validator exposes three separate status fields:  - **`state`**: the high-level lifecycle stage, derived from the beacon state, the indexer status, and recent on-chain exit requests. Progresses through `pending`, `queued`, `activating`, `active`, `exit_pending`, `exiting`, `withdrawn`. - **`consensusLayerState`**: the raw beacon-node state (consensus-spec values such as `active_ongoing`, `active_exiting`, `exited_slashed`, `withdrawal_done`), or `unknown` before the beacon chain has ingested the validator. - **`indexerState`**: the raw staking-data indexer status (`planned`, `active`, `deactivated`), plus `pending` before the deposit is observed on chain and `unknown` when the indexer holds no matching record.  Filters (all optional and combinable): `state`, `consensusLayerState`, `indexerState`, `validatorName` (exact match on the validator label), and `validatorPublicKey` (exact match on the BLS public key).
     * Get Validators
     */
    async ethereumGetValidatorsRaw(requestParameters: EthereumGetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumGetValidators200Response>> {
        if (requestParameters['network'] == null) {
            throw new runtime.RequiredError(
                'network',
                'Required parameter "network" was null or undefined when calling ethereumGetValidators().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['consensusLayerState'] != null) {
            queryParameters['consensusLayerState'] = requestParameters['consensusLayerState'];
        }

        if (requestParameters['indexerState'] != null) {
            queryParameters['indexerState'] = requestParameters['indexerState'];
        }

        if (requestParameters['validatorName'] != null) {
            queryParameters['validatorName'] = requestParameters['validatorName'];
        }

        if (requestParameters['validatorPublicKey'] != null) {
            queryParameters['validatorPublicKey'] = requestParameters['validatorPublicKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/validators`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumGetValidators200ResponseFromJSON(jsonValue));
    }

    /**
     * Lists all Ethereum validators for the authenticated account. Returns the full set when called without filters. Supply any combination of the filters below to narrow the results.  Each validator exposes three separate status fields:  - **`state`**: the high-level lifecycle stage, derived from the beacon state, the indexer status, and recent on-chain exit requests. Progresses through `pending`, `queued`, `activating`, `active`, `exit_pending`, `exiting`, `withdrawn`. - **`consensusLayerState`**: the raw beacon-node state (consensus-spec values such as `active_ongoing`, `active_exiting`, `exited_slashed`, `withdrawal_done`), or `unknown` before the beacon chain has ingested the validator. - **`indexerState`**: the raw staking-data indexer status (`planned`, `active`, `deactivated`), plus `pending` before the deposit is observed on chain and `unknown` when the indexer holds no matching record.  Filters (all optional and combinable): `state`, `consensusLayerState`, `indexerState`, `validatorName` (exact match on the validator label), and `validatorPublicKey` (exact match on the BLS public key).
     * Get Validators
     */
    async ethereumGetValidators(requestParameters: EthereumGetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumGetValidators200Response> {
        const response = await this.ethereumGetValidatorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a BLS key, registers it with the validator client, and returns an unsigned deposit transaction.  You can send an `Idempotency-Key` header (UUID) to make retries safe. Repeating the same key with the same body returns the original response without minting a new key.  **Pending stakes:** An account may hold at most 10 pending stakes at a time (deposits that have been generated but whose deposit transaction has not yet been broadcast on chain). Cancel a pending stake with `POST /v1/ethereum-staking/cancel-stake` to free a slot.  **MEV policy:** MEV-Boost configuration (relay allowlist, min-bid threshold, builder participation) is set per-customer at the operator level rather than per-stake. The policy in effect at the time of a proposal slot is the one that applies. Confirm the MEV policy with the assigned operator before staking.
     * Stake
     */
    async ethereumStakeRaw(requestParameters: EthereumStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumStake200Response>> {
        if (requestParameters['ethereumStakeRequest'] == null) {
            throw new runtime.RequiredError(
                'ethereumStakeRequest',
                'Required parameter "ethereumStakeRequest" was null or undefined when calling ethereumStake().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/stake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumStakeRequestToJSON(requestParameters['ethereumStakeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumStake200ResponseFromJSON(jsonValue));
    }

    /**
     * Generates a BLS key, registers it with the validator client, and returns an unsigned deposit transaction.  You can send an `Idempotency-Key` header (UUID) to make retries safe. Repeating the same key with the same body returns the original response without minting a new key.  **Pending stakes:** An account may hold at most 10 pending stakes at a time (deposits that have been generated but whose deposit transaction has not yet been broadcast on chain). Cancel a pending stake with `POST /v1/ethereum-staking/cancel-stake` to free a slot.  **MEV policy:** MEV-Boost configuration (relay allowlist, min-bid threshold, builder participation) is set per-customer at the operator level rather than per-stake. The policy in effect at the time of a proposal slot is the one that applies. Confirm the MEV policy with the assigned operator before staking.
     * Stake
     */
    async ethereumStake(requestParameters: EthereumStakeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumStake200Response> {
        const response = await this.ethereumStakeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Build an unsigned deposit-contract transaction that adds balance to an existing 0x02 (compounding) validator, reusing its pubkey and withdrawal credentials. Useful for pushing balance toward the 2048 ETH cap without provisioning a new validator.
     * Add Stake (\"Topup\")
     */
    async ethereumTopupRaw(requestParameters: EthereumTopupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumTopup200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/topup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumTopupRequestToJSON(requestParameters['ethereumTopupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumTopup200ResponseFromJSON(jsonValue));
    }

    /**
     * Build an unsigned deposit-contract transaction that adds balance to an existing 0x02 (compounding) validator, reusing its pubkey and withdrawal credentials. Useful for pushing balance toward the 2048 ETH cap without provisioning a new validator.
     * Add Stake (\"Topup\")
     */
    async ethereumTopup(requestParameters: EthereumTopupOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumTopup200Response> {
        const response = await this.ethereumTopupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns an unsigned EIP-7002 partial-withdrawal transaction for the withdrawal address to sign and broadcast. The validator stays active and keeps attesting.  A partial withdrawal is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  `amountWei` must be a whole-gwei multiple of at least 1 gwei, and the remaining balance must stay above 32 ETH. For a full exit, use `POST /v1/ethereum-staking/exit` or `POST /v1/ethereum-staking/force-exit`.  A validator must have been active for at least 256 epochs (about 27 hours) before a withdrawal request is accepted.
     * Withdrawal (trustless)
     */
    async ethereumWithdrawRaw(requestParameters: EthereumWithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EthereumWithdraw200Response>> {
        if (requestParameters['ethereumWithdrawRequest'] == null) {
            throw new runtime.RequiredError(
                'ethereumWithdrawRequest',
                'Required parameter "ethereumWithdrawRequest" was null or undefined when calling ethereumWithdraw().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/ethereum-staking/withdraw`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EthereumWithdrawRequestToJSON(requestParameters['ethereumWithdrawRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EthereumWithdraw200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns an unsigned EIP-7002 partial-withdrawal transaction for the withdrawal address to sign and broadcast. The validator stays active and keeps attesting.  A partial withdrawal is a standard on-chain request that the withdrawal address can build and send on its own, without this API. This endpoint is a convenience that assembles that transaction so it does not have to be built by hand.  `amountWei` must be a whole-gwei multiple of at least 1 gwei, and the remaining balance must stay above 32 ETH. For a full exit, use `POST /v1/ethereum-staking/exit` or `POST /v1/ethereum-staking/force-exit`.  A validator must have been active for at least 256 epochs (about 27 hours) before a withdrawal request is accepted.
     * Withdrawal (trustless)
     */
    async ethereumWithdraw(requestParameters: EthereumWithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EthereumWithdraw200Response> {
        const response = await this.ethereumWithdrawRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const EthereumGetValidatorsStateEnum = {
    Pending: 'pending',
    Queued: 'queued',
    Activating: 'activating',
    Active: 'active',
    ExitPending: 'exit_pending',
    Exiting: 'exiting',
    Withdrawn: 'withdrawn'
} as const;
export type EthereumGetValidatorsStateEnum = typeof EthereumGetValidatorsStateEnum[keyof typeof EthereumGetValidatorsStateEnum];
/**
 * @export
 */
export const EthereumGetValidatorsConsensusLayerStateEnum = {
    PendingInitialized: 'pending_initialized',
    PendingQueued: 'pending_queued',
    ActiveOngoing: 'active_ongoing',
    ActiveExiting: 'active_exiting',
    ActiveSlashed: 'active_slashed',
    ExitedUnslashed: 'exited_unslashed',
    ExitedSlashed: 'exited_slashed',
    WithdrawalPossible: 'withdrawal_possible',
    WithdrawalDone: 'withdrawal_done',
    Unknown: 'unknown'
} as const;
export type EthereumGetValidatorsConsensusLayerStateEnum = typeof EthereumGetValidatorsConsensusLayerStateEnum[keyof typeof EthereumGetValidatorsConsensusLayerStateEnum];
/**
 * @export
 */
export const EthereumGetValidatorsIndexerStateEnum = {
    Planned: 'planned',
    Active: 'active',
    Deactivated: 'deactivated',
    Pending: 'pending',
    Unknown: 'unknown'
} as const;
export type EthereumGetValidatorsIndexerStateEnum = typeof EthereumGetValidatorsIndexerStateEnum[keyof typeof EthereumGetValidatorsIndexerStateEnum];
