/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateStakingWithdrawalRequest,
  DailyRewardsResponse,
  DelegationHistoryResponse,
  ErrorResponse,
  GetStakingPositions200Response,
  GetValidators200Response,
  RewardHistoryResponse,
  SimplifiedStakeRequest,
  StakingNetwork,
  StakingToken,
  TransactionsResponse,
} from '../models/index';
import {
    CreateStakingWithdrawalRequestFromJSON,
    CreateStakingWithdrawalRequestToJSON,
    DailyRewardsResponseFromJSON,
    DailyRewardsResponseToJSON,
    DelegationHistoryResponseFromJSON,
    DelegationHistoryResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetStakingPositions200ResponseFromJSON,
    GetStakingPositions200ResponseToJSON,
    GetValidators200ResponseFromJSON,
    GetValidators200ResponseToJSON,
    RewardHistoryResponseFromJSON,
    RewardHistoryResponseToJSON,
    SimplifiedStakeRequestFromJSON,
    SimplifiedStakeRequestToJSON,
    StakingNetworkFromJSON,
    StakingNetworkToJSON,
    StakingTokenFromJSON,
    StakingTokenToJSON,
    TransactionsResponseFromJSON,
    TransactionsResponseToJSON,
} from '../models/index';

export interface CreateStakeRequest {
    simplifiedStakeRequest: SimplifiedStakeRequest;
}

export interface CreateStakingWithdrawalOperationRequest {
    createStakingWithdrawalRequest: CreateStakingWithdrawalRequest;
}

export interface CreateUnstakeRequest {
    simplifiedStakeRequest: SimplifiedStakeRequest;
}

export interface GetStakingDailyRewardsRequest {
    validatorId: string;
    startDate?: string;
    endDate?: string;
    limit?: string;
}

export interface GetStakingDelegationHistoryRequest {
    validatorId: string;
    eventType?: string;
    limit?: string;
}

export interface GetStakingPositionsRequest {
    staker: string;
    network: StakingNetwork;
    validator: string;
    token: StakingToken;
}

export interface GetStakingRewardHistoryRequest {
    validatorId: string;
    limit?: string;
}

export interface GetValidatorsRequest {
    network?: StakingNetwork;
    status?: GetValidatorsStatusEnum;
}

/**
 * SimpleStakingApi - interface
 * 
 * @export
 * @interface SimpleStakingApiInterface
 */
export interface SimpleStakingApiInterface {
    /**
     *  Creates unsigned transactions for staking or delegation operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available staking combinations   | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **S** | sonic, sonic-testnet | | **KAIA** | kaia | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **SOMI** | somnia | | **ROCK** | zenrock, zenrock-testnet |  **Notes:** - **Amount**: Amount is not required for Cardano. All balance is staked by protocol design. 
     * @summary Create staking transactions
     * @param {SimplifiedStakeRequest} simplifiedStakeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    createStakeRaw(requestParameters: CreateStakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions for staking or delegation operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available staking combinations   | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **S** | sonic, sonic-testnet | | **KAIA** | kaia | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **SOMI** | somnia | | **ROCK** | zenrock, zenrock-testnet |  **Notes:** - **Amount**: Amount is not required for Cardano. All balance is staked by protocol design. 
     * Create staking transactions
     */
    createStake(requestParameters: CreateStakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     *  Creates unsigned transactions for the staking withdrawal operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | Withdrawal Period | |-------|---------|-------------------| | **POL** | ethereum, ethereum-sepolia-testnet | ~80 checkpoints (~2-3 days) | | **SOL** | solana, solana-testnet | 1 epoch (~2 days) | | **KAIA** | kaia | 7 days | | **S** | sonic, sonic-testnet | 14 days | | **SOMI** | somnia | ~1 epoch (a few minutes) | | **APT** | aptos, aptos-testnet | Immediate | | **NEAR** | near, near-testnet | 2-3 epochs (~36-52 hours) |  **Note:** Withdrawals complete all available stake from previous unstake requests. Call /unstake first to initiate the withdrawal process. 
     * @summary Create stake withdrawal transactions
     * @param {CreateStakingWithdrawalRequest} createStakingWithdrawalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    createStakingWithdrawalRaw(requestParameters: CreateStakingWithdrawalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions for the staking withdrawal operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | Withdrawal Period | |-------|---------|-------------------| | **POL** | ethereum, ethereum-sepolia-testnet | ~80 checkpoints (~2-3 days) | | **SOL** | solana, solana-testnet | 1 epoch (~2 days) | | **KAIA** | kaia | 7 days | | **S** | sonic, sonic-testnet | 14 days | | **SOMI** | somnia | ~1 epoch (a few minutes) | | **APT** | aptos, aptos-testnet | Immediate | | **NEAR** | near, near-testnet | 2-3 epochs (~36-52 hours) |  **Note:** Withdrawals complete all available stake from previous unstake requests. Call /unstake first to initiate the withdrawal process. 
     * Create stake withdrawal transactions
     */
    createStakingWithdrawal(requestParameters: CreateStakingWithdrawalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     *  Creates unsigned transactions for the staking unstaking operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **ADA** | cardano, cardano-testnet | | **SOMI** | somnia | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * @summary Create stake unstaking transactions
     * @param {SimplifiedStakeRequest} simplifiedStakeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    createUnstakeRaw(requestParameters: CreateUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>>;

    /**
     *  Creates unsigned transactions for the staking unstaking operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **ADA** | cardano, cardano-testnet | | **SOMI** | somnia | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * Create stake unstaking transactions
     */
    createUnstake(requestParameters: CreateUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse>;

    /**
     * Returns the daily aggregated rewards (total rewards, delegator rewards, commission) for a specific validator. The network is automatically determined from the validatorId.
     * @summary Get staking daily reward history for a validator
     * @param {string} validatorId 
     * @param {string} [startDate] 
     * @param {string} [endDate] 
     * @param {string} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    getStakingDailyRewardsRaw(requestParameters: GetStakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyRewardsResponse>>;

    /**
     * Returns the daily aggregated rewards (total rewards, delegator rewards, commission) for a specific validator. The network is automatically determined from the validatorId.
     * Get staking daily reward history for a validator
     */
    getStakingDailyRewards(requestParameters: GetStakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyRewardsResponse>;

    /**
     * Returns the delegation transaction history (delegate, undelegate, redelegate events) for a specific validator
     * @summary Get staking delegation transaction history for a validator
     * @param {string} validatorId 
     * @param {string} [eventType] 
     * @param {string} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    getStakingDelegationHistoryRaw(requestParameters: GetStakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DelegationHistoryResponse>>;

    /**
     * Returns the delegation transaction history (delegate, undelegate, redelegate events) for a specific validator
     * Get staking delegation transaction history for a validator
     */
    getStakingDelegationHistory(requestParameters: GetStakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DelegationHistoryResponse>;

    /**
     *  Returns the current staking positions for an address across supported networks.  ## Tokens and Networks  | Token | Network | |-------|---------| | **POL** | ethereum | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * @summary Get staking positions
     * @param {string} staker The staker address to query stakes for
     * @param {StakingNetwork} network The blockchain network to query
     * @param {string} validator The validator address (required for Kaia)
     * @param {StakingToken} token The token to query stakes for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    getStakingPositionsRaw(requestParameters: GetStakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStakingPositions200Response>>;

    /**
     *  Returns the current staking positions for an address across supported networks.  ## Tokens and Networks  | Token | Network | |-------|---------| | **POL** | ethereum | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * Get staking positions
     */
    getStakingPositions(requestParameters: GetStakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStakingPositions200Response>;

    /**
     * Returns the reward withdrawal transaction history for a specific validator
     * @summary Get staking reward withdrawal transaction history for a validator
     * @param {string} validatorId 
     * @param {string} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    getStakingRewardHistoryRaw(requestParameters: GetStakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardHistoryResponse>>;

    /**
     * Returns the reward withdrawal transaction history for a specific validator
     * Get staking reward withdrawal transaction history for a validator
     */
    getStakingRewardHistory(requestParameters: GetStakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardHistoryResponse>;

    /**
     * Returns a list of validators with network and status information
     * @summary Get validators
     * @param {StakingNetwork} [network] Network to filter validators by
     * @param {'LIVE' | 'PLANNED'} [status] Status to filter validators by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimpleStakingApiInterface
     */
    getValidatorsRaw(requestParameters: GetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetValidators200Response>>;

    /**
     * Returns a list of validators with network and status information
     * Get validators
     */
    getValidators(requestParameters: GetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetValidators200Response>;

}

/**
 * 
 */
export class SimpleStakingApi extends runtime.BaseAPI implements SimpleStakingApiInterface {

    /**
     *  Creates unsigned transactions for staking or delegation operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available staking combinations   | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **S** | sonic, sonic-testnet | | **KAIA** | kaia | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **SOMI** | somnia | | **ROCK** | zenrock, zenrock-testnet |  **Notes:** - **Amount**: Amount is not required for Cardano. All balance is staked by protocol design. 
     * Create staking transactions
     */
    async createStakeRaw(requestParameters: CreateStakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['simplifiedStakeRequest'] == null) {
            throw new runtime.RequiredError(
                'simplifiedStakeRequest',
                'Required parameter "simplifiedStakeRequest" was null or undefined when calling createStake().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/stake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimplifiedStakeRequestToJSON(requestParameters['simplifiedStakeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions for staking or delegation operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available staking combinations   | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **S** | sonic, sonic-testnet | | **KAIA** | kaia | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **SOMI** | somnia | | **ROCK** | zenrock, zenrock-testnet |  **Notes:** - **Amount**: Amount is not required for Cardano. All balance is staked by protocol design. 
     * Create staking transactions
     */
    async createStake(requestParameters: CreateStakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createStakeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Creates unsigned transactions for the staking withdrawal operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | Withdrawal Period | |-------|---------|-------------------| | **POL** | ethereum, ethereum-sepolia-testnet | ~80 checkpoints (~2-3 days) | | **SOL** | solana, solana-testnet | 1 epoch (~2 days) | | **KAIA** | kaia | 7 days | | **S** | sonic, sonic-testnet | 14 days | | **SOMI** | somnia | ~1 epoch (a few minutes) | | **APT** | aptos, aptos-testnet | Immediate | | **NEAR** | near, near-testnet | 2-3 epochs (~36-52 hours) |  **Note:** Withdrawals complete all available stake from previous unstake requests. Call /unstake first to initiate the withdrawal process. 
     * Create stake withdrawal transactions
     */
    async createStakingWithdrawalRaw(requestParameters: CreateStakingWithdrawalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['createStakingWithdrawalRequest'] == null) {
            throw new runtime.RequiredError(
                'createStakingWithdrawalRequest',
                'Required parameter "createStakingWithdrawalRequest" was null or undefined when calling createStakingWithdrawal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/withdraw`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStakingWithdrawalRequestToJSON(requestParameters['createStakingWithdrawalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions for the staking withdrawal operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | Withdrawal Period | |-------|---------|-------------------| | **POL** | ethereum, ethereum-sepolia-testnet | ~80 checkpoints (~2-3 days) | | **SOL** | solana, solana-testnet | 1 epoch (~2 days) | | **KAIA** | kaia | 7 days | | **S** | sonic, sonic-testnet | 14 days | | **SOMI** | somnia | ~1 epoch (a few minutes) | | **APT** | aptos, aptos-testnet | Immediate | | **NEAR** | near, near-testnet | 2-3 epochs (~36-52 hours) |  **Note:** Withdrawals complete all available stake from previous unstake requests. Call /unstake first to initiate the withdrawal process. 
     * Create stake withdrawal transactions
     */
    async createStakingWithdrawal(requestParameters: CreateStakingWithdrawalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createStakingWithdrawalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Creates unsigned transactions for the staking unstaking operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **ADA** | cardano, cardano-testnet | | **SOMI** | somnia | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * Create stake unstaking transactions
     */
    async createUnstakeRaw(requestParameters: CreateUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionsResponse>> {
        if (requestParameters['simplifiedStakeRequest'] == null) {
            throw new runtime.RequiredError(
                'simplifiedStakeRequest',
                'Required parameter "simplifiedStakeRequest" was null or undefined when calling createUnstake().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/unstake`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimplifiedStakeRequestToJSON(requestParameters['simplifiedStakeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionsResponseFromJSON(jsonValue));
    }

    /**
     *  Creates unsigned transactions for the staking unstaking operations across supported blockchain networks.  Address format, token denomination and some other parameters vary by network. Examples for each network are provided in the examples on the right panel.  ## Available Networks and Tokens  | Token | Network | |-------|---------| | **POL** | ethereum, ethereum-sepolia-testnet | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **NIL** | nillion, nillion-testnet | | **ADA** | cardano, cardano-testnet | | **SOMI** | somnia | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **MON** | monad, monad-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * Create stake unstaking transactions
     */
    async createUnstake(requestParameters: CreateUnstakeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionsResponse> {
        const response = await this.createUnstakeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the daily aggregated rewards (total rewards, delegator rewards, commission) for a specific validator. The network is automatically determined from the validatorId.
     * Get staking daily reward history for a validator
     */
    async getStakingDailyRewardsRaw(requestParameters: GetStakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DailyRewardsResponse>> {
        if (requestParameters['validatorId'] == null) {
            throw new runtime.RequiredError(
                'validatorId',
                'Required parameter "validatorId" was null or undefined when calling getStakingDailyRewards().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/daily-reward-history/{validatorId}`.replace(`{${"validatorId"}}`, encodeURIComponent(String(requestParameters['validatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DailyRewardsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the daily aggregated rewards (total rewards, delegator rewards, commission) for a specific validator. The network is automatically determined from the validatorId.
     * Get staking daily reward history for a validator
     */
    async getStakingDailyRewards(requestParameters: GetStakingDailyRewardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DailyRewardsResponse> {
        const response = await this.getStakingDailyRewardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the delegation transaction history (delegate, undelegate, redelegate events) for a specific validator
     * Get staking delegation transaction history for a validator
     */
    async getStakingDelegationHistoryRaw(requestParameters: GetStakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DelegationHistoryResponse>> {
        if (requestParameters['validatorId'] == null) {
            throw new runtime.RequiredError(
                'validatorId',
                'Required parameter "validatorId" was null or undefined when calling getStakingDelegationHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['eventType'] != null) {
            queryParameters['eventType'] = requestParameters['eventType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/delegation-tx-history/{validatorId}`.replace(`{${"validatorId"}}`, encodeURIComponent(String(requestParameters['validatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DelegationHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Returns the delegation transaction history (delegate, undelegate, redelegate events) for a specific validator
     * Get staking delegation transaction history for a validator
     */
    async getStakingDelegationHistory(requestParameters: GetStakingDelegationHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DelegationHistoryResponse> {
        const response = await this.getStakingDelegationHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *  Returns the current staking positions for an address across supported networks.  ## Tokens and Networks  | Token | Network | |-------|---------| | **POL** | ethereum | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * Get staking positions
     */
    async getStakingPositionsRaw(requestParameters: GetStakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStakingPositions200Response>> {
        if (requestParameters['staker'] == null) {
            throw new runtime.RequiredError(
                'staker',
                'Required parameter "staker" was null or undefined when calling getStakingPositions().'
            );
        }

        if (requestParameters['network'] == null) {
            throw new runtime.RequiredError(
                'network',
                'Required parameter "network" was null or undefined when calling getStakingPositions().'
            );
        }

        if (requestParameters['validator'] == null) {
            throw new runtime.RequiredError(
                'validator',
                'Required parameter "validator" was null or undefined when calling getStakingPositions().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getStakingPositions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['staker'] != null) {
            queryParameters['staker'] = requestParameters['staker'];
        }

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['validator'] != null) {
            queryParameters['validator'] = requestParameters['validator'];
        }

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/stakes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStakingPositions200ResponseFromJSON(jsonValue));
    }

    /**
     *  Returns the current staking positions for an address across supported networks.  ## Tokens and Networks  | Token | Network | |-------|---------| | **POL** | ethereum | | **SOL** | solana, solana-testnet | | **KAIA** | kaia | | **S** | sonic, sonic-testnet | | **MANTRA** | mantra, mantra-testnet | | **ADA** | cardano, cardano-testnet | | **APT** | aptos, aptos-testnet | | **NEAR** | near, near-testnet | | **ROCK** | zenrock, zenrock-testnet | 
     * Get staking positions
     */
    async getStakingPositions(requestParameters: GetStakingPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStakingPositions200Response> {
        const response = await this.getStakingPositionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the reward withdrawal transaction history for a specific validator
     * Get staking reward withdrawal transaction history for a validator
     */
    async getStakingRewardHistoryRaw(requestParameters: GetStakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardHistoryResponse>> {
        if (requestParameters['validatorId'] == null) {
            throw new runtime.RequiredError(
                'validatorId',
                'Required parameter "validatorId" was null or undefined when calling getStakingRewardHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/withdraw-rewards-tx-history/{validatorId}`.replace(`{${"validatorId"}}`, encodeURIComponent(String(requestParameters['validatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Returns the reward withdrawal transaction history for a specific validator
     * Get staking reward withdrawal transaction history for a validator
     */
    async getStakingRewardHistory(requestParameters: GetStakingRewardHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardHistoryResponse> {
        const response = await this.getStakingRewardHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of validators with network and status information
     * Get validators
     */
    async getValidatorsRaw(requestParameters: GetValidatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetValidators200Response>> {
        const queryParameters: any = {};

        if (requestParameters['network'] != null) {
            queryParameters['network'] = requestParameters['network'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/v1/staking/validators`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetValidators200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of validators with network and status information
     * Get validators
     */
    async getValidators(requestParameters: GetValidatorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetValidators200Response> {
        const response = await this.getValidatorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetValidatorsStatusEnum = {
    Live: 'LIVE',
    Planned: 'PLANNED'
} as const;
export type GetValidatorsStatusEnum = typeof GetValidatorsStatusEnum[keyof typeof GetValidatorsStatusEnum];
