/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetHealthStatus200Response,
  GetOpenApiSpec200Response,
} from '../models/index';
import {
    GetHealthStatus200ResponseFromJSON,
    GetHealthStatus200ResponseToJSON,
    GetOpenApiSpec200ResponseFromJSON,
    GetOpenApiSpec200ResponseToJSON,
} from '../models/index';

/**
 * SystemApi - interface
 * 
 * @export
 * @interface SystemApiInterface
 */
export interface SystemApiInterface {
    /**
     * Returns the health status of the API
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    getHealthStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHealthStatus200Response>>;

    /**
     * Returns the health status of the API
     * Health check endpoint
     */
    getHealthStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHealthStatus200Response>;

    /**
     * Returns the complete OpenAPI 3.0 specification for this API
     * @summary Get OpenAPI specification
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    getOpenApiSpecRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOpenApiSpec200Response>>;

    /**
     * Returns the complete OpenAPI 3.0 specification for this API
     * Get OpenAPI specification
     */
    getOpenApiSpec(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOpenApiSpec200Response>;

}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI implements SystemApiInterface {

    /**
     * Returns the health status of the API
     * Health check endpoint
     */
    async getHealthStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHealthStatus200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHealthStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the health status of the API
     * Health check endpoint
     */
    async getHealthStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHealthStatus200Response> {
        const response = await this.getHealthStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the complete OpenAPI 3.0 specification for this API
     * Get OpenAPI specification
     */
    async getOpenApiSpecRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOpenApiSpec200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/openapi.json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOpenApiSpec200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the complete OpenAPI 3.0 specification for this API
     * Get OpenAPI specification
     */
    async getOpenApiSpec(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOpenApiSpec200Response> {
        const response = await this.getOpenApiSpecRaw(initOverrides);
        return await response.value();
    }

}
