/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingNetwork } from './StakingNetwork';
import {
    StakingNetworkFromJSON,
    StakingNetworkFromJSONTyped,
    StakingNetworkToJSON,
    StakingNetworkToJSONTyped,
} from './StakingNetwork';
import type { StakingToken } from './StakingToken';
import {
    StakingTokenFromJSON,
    StakingTokenFromJSONTyped,
    StakingTokenToJSON,
    StakingTokenToJSONTyped,
} from './StakingToken';

/**
 * 
 * @export
 * @interface CreateStakingWithdrawalRequest
 */
export interface CreateStakingWithdrawalRequest {
    /**
     * 
     * @type {StakingNetwork}
     * @memberof CreateStakingWithdrawalRequest
     */
    network: StakingNetwork;
    /**
     * 
     * @type {StakingToken}
     * @memberof CreateStakingWithdrawalRequest
     */
    token: StakingToken;
    /**
     * Staker address or public key.
     * 
     * | Network Type | Format | Example |
     * |--------------|--------|---------|
     * | **Solana** | Base58 encoded public key | updtkJ8HAhh3rSkBCd3p9Z1Q74yJW4rMhSbScRskDPM |
     * | **EVM Networks (Polygon/Sonic/Kaia/Somnia/Monad)** | 0x-prefixed hex address | 0x1234567890abcdef1234567890abcdef12345678 |
     * | **Aptos** | 0x-prefixed hex address | 0xfa792d402a59ad9a634936d8682578e2706b0ef2460377a673f107316524e5cb |
     * | **NEAR** | ed25519 public key | ed25519:2BRMynZbQKW7eYCsLB41BjdUpyWgH4ou7DiWEaiz7HLx |
     * 
     * @type {string}
     * @memberof CreateStakingWithdrawalRequest
     */
    staker: string;
    /**
     * Validator address/pubkey/identifier.
     * 
     * | Network Type | Format | Example |
     * |--------------|--------|---------|
     * | **Solana** | Base58 encoded vote account address | he1iusunGwqrNtafDtLdhsUQDFvo13z9sUa36PauBtk |
     * | **Polygon** | 0x-prefixed validator contract address | 0x26D1Ec50b4e62C1D1a40d16e7caD677311A5F2C5 |
     * | **Sonic/Kaia/Somnia** | 0x-prefixed validator address | 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb8 |
     * | **Monad** | Validator ID (numeric string) | 1 |
     * | **Aptos** | 0x-prefixed validator address | 0xdb5247f859ce63dbe8940cf8773be722a60dcc594a8be9aca4b76abceb251b8e |
     * | **NEAR** | NEAR staking pool account ID | everstake.poolv1.near |
     * @type {string}
     * @memberof CreateStakingWithdrawalRequest
     */
    validator?: string;
    /**
     * Additional network-specific parameters. Refer to specific examples for additional information.
     * 
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateStakingWithdrawalRequest
     */
    params?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateStakingWithdrawalRequest interface.
 */
export function instanceOfCreateStakingWithdrawalRequest(value: object): value is CreateStakingWithdrawalRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    return true;
}

export function CreateStakingWithdrawalRequestFromJSON(json: any): CreateStakingWithdrawalRequest {
    return CreateStakingWithdrawalRequestFromJSONTyped(json, false);
}

export function CreateStakingWithdrawalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStakingWithdrawalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': StakingNetworkFromJSON(json['network']),
        'token': StakingTokenFromJSON(json['token']),
        'staker': json['staker'],
        'validator': json['validator'] == null ? undefined : json['validator'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function CreateStakingWithdrawalRequestToJSON(json: any): CreateStakingWithdrawalRequest {
    return CreateStakingWithdrawalRequestToJSONTyped(json, false);
}

export function CreateStakingWithdrawalRequestToJSONTyped(value?: CreateStakingWithdrawalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': StakingNetworkToJSON(value['network']),
        'token': StakingTokenToJSON(value['token']),
        'staker': value['staker'],
        'validator': value['validator'],
        'params': value['params'],
    };
}

