/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyRewardItem
 */
export interface DailyRewardItem {
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    validatorId: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    validatorAddress: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    validatorMoniker?: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    totalReward: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    totalRewardFormatted: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    delegatorReward: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    delegatorRewardFormatted: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    validatorCommission: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    validatorCommissionFormatted: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    tokenSymbol: string;
    /**
     * 
     * @type {number}
     * @memberof DailyRewardItem
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof DailyRewardItem
     */
    protocol?: string;
}

/**
 * Check if a given object implements the DailyRewardItem interface.
 */
export function instanceOfDailyRewardItem(value: object): value is DailyRewardItem {
    if (!('validatorId' in value) || value['validatorId'] === undefined) return false;
    if (!('validatorAddress' in value) || value['validatorAddress'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('totalReward' in value) || value['totalReward'] === undefined) return false;
    if (!('totalRewardFormatted' in value) || value['totalRewardFormatted'] === undefined) return false;
    if (!('delegatorReward' in value) || value['delegatorReward'] === undefined) return false;
    if (!('delegatorRewardFormatted' in value) || value['delegatorRewardFormatted'] === undefined) return false;
    if (!('validatorCommission' in value) || value['validatorCommission'] === undefined) return false;
    if (!('validatorCommissionFormatted' in value) || value['validatorCommissionFormatted'] === undefined) return false;
    if (!('tokenSymbol' in value) || value['tokenSymbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    return true;
}

export function DailyRewardItemFromJSON(json: any): DailyRewardItem {
    return DailyRewardItemFromJSONTyped(json, false);
}

export function DailyRewardItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyRewardItem {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorId': json['validatorId'],
        'validatorAddress': json['validatorAddress'],
        'validatorMoniker': json['validatorMoniker'] == null ? undefined : json['validatorMoniker'],
        'date': json['date'],
        'totalReward': json['totalReward'],
        'totalRewardFormatted': json['totalRewardFormatted'],
        'delegatorReward': json['delegatorReward'],
        'delegatorRewardFormatted': json['delegatorRewardFormatted'],
        'validatorCommission': json['validatorCommission'],
        'validatorCommissionFormatted': json['validatorCommissionFormatted'],
        'tokenSymbol': json['tokenSymbol'],
        'decimals': json['decimals'],
        'network': json['network'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
    };
}

export function DailyRewardItemToJSON(json: any): DailyRewardItem {
    return DailyRewardItemToJSONTyped(json, false);
}

export function DailyRewardItemToJSONTyped(value?: DailyRewardItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorId': value['validatorId'],
        'validatorAddress': value['validatorAddress'],
        'validatorMoniker': value['validatorMoniker'],
        'date': value['date'],
        'totalReward': value['totalReward'],
        'totalRewardFormatted': value['totalRewardFormatted'],
        'delegatorReward': value['delegatorReward'],
        'delegatorRewardFormatted': value['delegatorRewardFormatted'],
        'validatorCommission': value['validatorCommission'],
        'validatorCommissionFormatted': value['validatorCommissionFormatted'],
        'tokenSymbol': value['tokenSymbol'],
        'decimals': value['decimals'],
        'network': value['network'],
        'protocol': value['protocol'],
    };
}

