/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DailyRewardItem } from './DailyRewardItem';
import {
    DailyRewardItemFromJSON,
    DailyRewardItemFromJSONTyped,
    DailyRewardItemToJSON,
    DailyRewardItemToJSONTyped,
} from './DailyRewardItem';

/**
 * 
 * @export
 * @interface DailyRewardsResponse
 */
export interface DailyRewardsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DailyRewardsResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<DailyRewardItem>}
     * @memberof DailyRewardsResponse
     */
    data: Array<DailyRewardItem>;
}

/**
 * Check if a given object implements the DailyRewardsResponse interface.
 */
export function instanceOfDailyRewardsResponse(value: object): value is DailyRewardsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DailyRewardsResponseFromJSON(json: any): DailyRewardsResponse {
    return DailyRewardsResponseFromJSONTyped(json, false);
}

export function DailyRewardsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyRewardsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(DailyRewardItemFromJSON)),
    };
}

export function DailyRewardsResponseToJSON(json: any): DailyRewardsResponse {
    return DailyRewardsResponseToJSONTyped(json, false);
}

export function DailyRewardsResponseToJSONTyped(value?: DailyRewardsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(DailyRewardItemToJSON)),
    };
}

