/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DelegationHistoryItem
 */
export interface DelegationHistoryItem {
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    validatorId: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    validatorAddress: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    validatorMoniker?: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    delegatorAddress: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    eventType: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    amountFormatted: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    tokenSymbol: string;
    /**
     * 
     * @type {number}
     * @memberof DelegationHistoryItem
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    blockNumber: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    transactionHash: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationHistoryItem
     */
    protocol?: string;
}

/**
 * Check if a given object implements the DelegationHistoryItem interface.
 */
export function instanceOfDelegationHistoryItem(value: object): value is DelegationHistoryItem {
    if (!('validatorId' in value) || value['validatorId'] === undefined) return false;
    if (!('validatorAddress' in value) || value['validatorAddress'] === undefined) return false;
    if (!('delegatorAddress' in value) || value['delegatorAddress'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('amountFormatted' in value) || value['amountFormatted'] === undefined) return false;
    if (!('tokenSymbol' in value) || value['tokenSymbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('transactionHash' in value) || value['transactionHash'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    return true;
}

export function DelegationHistoryItemFromJSON(json: any): DelegationHistoryItem {
    return DelegationHistoryItemFromJSONTyped(json, false);
}

export function DelegationHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DelegationHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorId': json['validatorId'],
        'validatorAddress': json['validatorAddress'],
        'validatorMoniker': json['validatorMoniker'] == null ? undefined : json['validatorMoniker'],
        'delegatorAddress': json['delegatorAddress'],
        'eventType': json['eventType'],
        'amount': json['amount'],
        'amountFormatted': json['amountFormatted'],
        'tokenSymbol': json['tokenSymbol'],
        'decimals': json['decimals'],
        'blockNumber': json['blockNumber'],
        'transactionHash': json['transactionHash'],
        'timestamp': json['timestamp'],
        'network': json['network'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
    };
}

export function DelegationHistoryItemToJSON(json: any): DelegationHistoryItem {
    return DelegationHistoryItemToJSONTyped(json, false);
}

export function DelegationHistoryItemToJSONTyped(value?: DelegationHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorId': value['validatorId'],
        'validatorAddress': value['validatorAddress'],
        'validatorMoniker': value['validatorMoniker'],
        'delegatorAddress': value['delegatorAddress'],
        'eventType': value['eventType'],
        'amount': value['amount'],
        'amountFormatted': value['amountFormatted'],
        'tokenSymbol': value['tokenSymbol'],
        'decimals': value['decimals'],
        'blockNumber': value['blockNumber'],
        'transactionHash': value['transactionHash'],
        'timestamp': value['timestamp'],
        'network': value['network'],
        'protocol': value['protocol'],
    };
}

