/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DelegationHistoryItem } from './DelegationHistoryItem';
import {
    DelegationHistoryItemFromJSON,
    DelegationHistoryItemFromJSONTyped,
    DelegationHistoryItemToJSON,
    DelegationHistoryItemToJSONTyped,
} from './DelegationHistoryItem';

/**
 * 
 * @export
 * @interface DelegationHistoryResponse
 */
export interface DelegationHistoryResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DelegationHistoryResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<DelegationHistoryItem>}
     * @memberof DelegationHistoryResponse
     */
    data: Array<DelegationHistoryItem>;
}

/**
 * Check if a given object implements the DelegationHistoryResponse interface.
 */
export function instanceOfDelegationHistoryResponse(value: object): value is DelegationHistoryResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DelegationHistoryResponseFromJSON(json: any): DelegationHistoryResponse {
    return DelegationHistoryResponseFromJSONTyped(json, false);
}

export function DelegationHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DelegationHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(DelegationHistoryItemFromJSON)),
    };
}

export function DelegationHistoryResponseToJSON(json: any): DelegationHistoryResponse {
    return DelegationHistoryResponseToJSONTyped(json, false);
}

export function DelegationHistoryResponseToJSONTyped(value?: DelegationHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(DelegationHistoryItemToJSON)),
    };
}

