/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Network the validator runs on
 * @export
 * @interface EntityValidatorNetwork
 */
export interface EntityValidatorNetwork {
    /**
     * Network identifier
     * @type {string}
     * @memberof EntityValidatorNetwork
     */
    name: string;
    /**
     * Network type
     * @type {string}
     * @memberof EntityValidatorNetwork
     */
    type: EntityValidatorNetworkTypeEnum;
    /**
     * Native token
     * @type {string}
     * @memberof EntityValidatorNetwork
     */
    nativeToken: string;
    /**
     * Token symbol
     * @type {string}
     * @memberof EntityValidatorNetwork
     */
    tokenSymbol: string | null;
    /**
     * Token decimals
     * @type {number}
     * @memberof EntityValidatorNetwork
     */
    decimals: number | null;
}


/**
 * @export
 */
export const EntityValidatorNetworkTypeEnum = {
    Mainnet: 'mainnet',
    Testnet: 'testnet'
} as const;
export type EntityValidatorNetworkTypeEnum = typeof EntityValidatorNetworkTypeEnum[keyof typeof EntityValidatorNetworkTypeEnum];


/**
 * Check if a given object implements the EntityValidatorNetwork interface.
 */
export function instanceOfEntityValidatorNetwork(value: object): value is EntityValidatorNetwork {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('nativeToken' in value) || value['nativeToken'] === undefined) return false;
    if (!('tokenSymbol' in value) || value['tokenSymbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    return true;
}

export function EntityValidatorNetworkFromJSON(json: any): EntityValidatorNetwork {
    return EntityValidatorNetworkFromJSONTyped(json, false);
}

export function EntityValidatorNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityValidatorNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'nativeToken': json['nativeToken'],
        'tokenSymbol': json['tokenSymbol'],
        'decimals': json['decimals'],
    };
}

export function EntityValidatorNetworkToJSON(json: any): EntityValidatorNetwork {
    return EntityValidatorNetworkToJSONTyped(json, false);
}

export function EntityValidatorNetworkToJSONTyped(value?: EntityValidatorNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'nativeToken': value['nativeToken'],
        'tokenSymbol': value['tokenSymbol'],
        'decimals': value['decimals'],
    };
}

