/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityValidator } from './EntityValidator';
import {
    EntityValidatorFromJSON,
    EntityValidatorFromJSONTyped,
    EntityValidatorToJSON,
    EntityValidatorToJSONTyped,
} from './EntityValidator';

/**
 * Validator organization
 * @export
 * @interface Entity
 */
export interface Entity {
    /**
     * Entity identifier
     * @type {string}
     * @memberof Entity
     */
    entityId: string;
    /**
     * Entity type
     * @type {string}
     * @memberof Entity
     */
    entityType: string;
    /**
     * Entity name
     * @type {string}
     * @memberof Entity
     */
    name: string;
    /**
     * Entity description
     * @type {string}
     * @memberof Entity
     */
    description: string;
    /**
     * Whether the entity is active
     * @type {boolean}
     * @memberof Entity
     */
    active: boolean;
    /**
     * Validators operated by this entity
     * @type {Array<EntityValidator>}
     * @memberof Entity
     */
    validators?: Array<EntityValidator>;
}

/**
 * Check if a given object implements the Entity interface.
 */
export function instanceOfEntity(value: object): value is Entity {
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('entityType' in value) || value['entityType'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function EntityFromJSON(json: any): Entity {
    return EntityFromJSONTyped(json, false);
}

export function EntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entity {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['entityId'],
        'entityType': json['entityType'],
        'name': json['name'],
        'description': json['description'],
        'active': json['active'],
        'validators': json['validators'] == null ? undefined : ((json['validators'] as Array<any>).map(EntityValidatorFromJSON)),
    };
}

export function EntityToJSON(json: any): Entity {
    return EntityToJSONTyped(json, false);
}

export function EntityToJSONTyped(value?: Entity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityId': value['entityId'],
        'entityType': value['entityType'],
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'validators': value['validators'] == null ? undefined : ((value['validators'] as Array<any>).map(EntityValidatorToJSON)),
    };
}

