/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityValidatorNetwork } from './EntityValidatorNetwork';
import {
    EntityValidatorNetworkFromJSON,
    EntityValidatorNetworkFromJSONTyped,
    EntityValidatorNetworkToJSON,
    EntityValidatorNetworkToJSONTyped,
} from './EntityValidatorNetwork';

/**
 * Validator within an entity
 * @export
 * @interface EntityValidator
 */
export interface EntityValidator {
    /**
     * Validator identifier
     * @type {string}
     * @memberof EntityValidator
     */
    validatorId: string;
    /**
     * Validator address
     * @type {string}
     * @memberof EntityValidator
     */
    validatorAddress: string;
    /**
     * Validator display name
     * @type {string}
     * @memberof EntityValidator
     */
    moniker: string;
    /**
     * Validator status
     * @type {string}
     * @memberof EntityValidator
     */
    status: string;
    /**
     * 
     * @type {EntityValidatorNetwork}
     * @memberof EntityValidator
     */
    network: EntityValidatorNetwork;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    commissionRate?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    maxCommissionRate?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    maxCommissionChangeRate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityValidator
     */
    publicDelegationEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    creationBlockNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    ownerAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    stakingContract?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    securityContact?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityValidator
     */
    details?: string;
}

/**
 * Check if a given object implements the EntityValidator interface.
 */
export function instanceOfEntityValidator(value: object): value is EntityValidator {
    if (!('validatorId' in value) || value['validatorId'] === undefined) return false;
    if (!('validatorAddress' in value) || value['validatorAddress'] === undefined) return false;
    if (!('moniker' in value) || value['moniker'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    return true;
}

export function EntityValidatorFromJSON(json: any): EntityValidator {
    return EntityValidatorFromJSONTyped(json, false);
}

export function EntityValidatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityValidator {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorId': json['validatorId'],
        'validatorAddress': json['validatorAddress'],
        'moniker': json['moniker'],
        'status': json['status'],
        'network': EntityValidatorNetworkFromJSON(json['network']),
        'commissionRate': json['commissionRate'] == null ? undefined : json['commissionRate'],
        'maxCommissionRate': json['maxCommissionRate'] == null ? undefined : json['maxCommissionRate'],
        'maxCommissionChangeRate': json['maxCommissionChangeRate'] == null ? undefined : json['maxCommissionChangeRate'],
        'publicDelegationEnabled': json['publicDelegationEnabled'] == null ? undefined : json['publicDelegationEnabled'],
        'creationBlockNumber': json['creationBlockNumber'] == null ? undefined : json['creationBlockNumber'],
        'ownerAddress': json['ownerAddress'] == null ? undefined : json['ownerAddress'],
        'stakingContract': json['stakingContract'] == null ? undefined : json['stakingContract'],
        'website': json['website'] == null ? undefined : json['website'],
        'securityContact': json['securityContact'] == null ? undefined : json['securityContact'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function EntityValidatorToJSON(json: any): EntityValidator {
    return EntityValidatorToJSONTyped(json, false);
}

export function EntityValidatorToJSONTyped(value?: EntityValidator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorId': value['validatorId'],
        'validatorAddress': value['validatorAddress'],
        'moniker': value['moniker'],
        'status': value['status'],
        'network': EntityValidatorNetworkToJSON(value['network']),
        'commissionRate': value['commissionRate'],
        'maxCommissionRate': value['maxCommissionRate'],
        'maxCommissionChangeRate': value['maxCommissionChangeRate'],
        'publicDelegationEnabled': value['publicDelegationEnabled'],
        'creationBlockNumber': value['creationBlockNumber'],
        'ownerAddress': value['ownerAddress'],
        'stakingContract': value['stakingContract'],
        'website': value['website'],
        'securityContact': value['securityContact'],
        'details': value['details'],
    };
}

