/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumTransaction } from './EthereumTransaction';
import {
    EthereumTransactionFromJSON,
    EthereumTransactionFromJSONTyped,
    EthereumTransactionToJSON,
    EthereumTransactionToJSONTyped,
} from './EthereumTransaction';

/**
 * 
 * @export
 * @interface EthereumForceExitResponse
 */
export interface EthereumForceExitResponse {
    /**
     * 
     * @type {EthereumTransaction}
     * @memberof EthereumForceExitResponse
     */
    forceExitTransaction: EthereumTransaction;
}

/**
 * Check if a given object implements the EthereumForceExitResponse interface.
 */
export function instanceOfEthereumForceExitResponse(value: object): value is EthereumForceExitResponse {
    if (!('forceExitTransaction' in value) || value['forceExitTransaction'] === undefined) return false;
    return true;
}

export function EthereumForceExitResponseFromJSON(json: any): EthereumForceExitResponse {
    return EthereumForceExitResponseFromJSONTyped(json, false);
}

export function EthereumForceExitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumForceExitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'forceExitTransaction': EthereumTransactionFromJSON(json['forceExitTransaction']),
    };
}

export function EthereumForceExitResponseToJSON(json: any): EthereumForceExitResponse {
    return EthereumForceExitResponseToJSONTyped(json, false);
}

export function EthereumForceExitResponseToJSONTyped(value?: EthereumForceExitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'forceExitTransaction': EthereumTransactionToJSON(value['forceExitTransaction']),
    };
}

