/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EthereumExitResponse
 */
export interface EthereumExitResponse {
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumExitResponse
     */
    validatorPublicKey: string;
    /**
     * 
     * @type {boolean}
     * @memberof EthereumExitResponse
     */
    accepted: boolean;
    /**
     * Null until the consensus layer assigns it
     * @type {number}
     * @memberof EthereumExitResponse
     */
    exitEpoch: number | null;
}

/**
 * Check if a given object implements the EthereumExitResponse interface.
 */
export function instanceOfEthereumExitResponse(value: object): value is EthereumExitResponse {
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('exitEpoch' in value) || value['exitEpoch'] === undefined) return false;
    return true;
}

export function EthereumExitResponseFromJSON(json: any): EthereumExitResponse {
    return EthereumExitResponseFromJSONTyped(json, false);
}

export function EthereumExitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumExitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorPublicKey': json['validatorPublicKey'],
        'accepted': json['accepted'],
        'exitEpoch': json['exitEpoch'],
    };
}

export function EthereumExitResponseToJSON(json: any): EthereumExitResponse {
    return EthereumExitResponseToJSONTyped(json, false);
}

export function EthereumExitResponseToJSONTyped(value?: EthereumExitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorPublicKey': value['validatorPublicKey'],
        'accepted': value['accepted'],
        'exitEpoch': value['exitEpoch'],
    };
}

