/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumTransactionTx } from './EthereumTransactionTx';
import {
    EthereumTransactionTxFromJSON,
    EthereumTransactionTxFromJSONTyped,
    EthereumTransactionTxToJSON,
    EthereumTransactionTxToJSONTyped,
} from './EthereumTransactionTx';

/**
 * 
 * @export
 * @interface EthereumTransaction
 */
export interface EthereumTransaction {
    /**
     * Operation type
     * @type {string}
     * @memberof EthereumTransaction
     */
    type: EthereumTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransaction
     */
    transactionType: EthereumTransactionTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransaction
     */
    encodingFormat: EthereumTransactionEncodingFormatEnum;
    /**
     * 
     * @type {EthereumTransactionTx}
     * @memberof EthereumTransaction
     */
    tx: EthereumTransactionTx;
    /**
     * Hex-encoded unsigned transaction
     * @type {string}
     * @memberof EthereumTransaction
     */
    encodedTx: string;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransaction
     */
    description: string;
}


/**
 * @export
 */
export const EthereumTransactionTypeEnum = {
    Deposit: 'deposit',
    Withdraw: 'withdraw',
    ForceExit: 'force-exit'
} as const;
export type EthereumTransactionTypeEnum = typeof EthereumTransactionTypeEnum[keyof typeof EthereumTransactionTypeEnum];

/**
 * @export
 */
export const EthereumTransactionTransactionTypeEnum = {
    Evm: 'evm'
} as const;
export type EthereumTransactionTransactionTypeEnum = typeof EthereumTransactionTransactionTypeEnum[keyof typeof EthereumTransactionTransactionTypeEnum];

/**
 * @export
 */
export const EthereumTransactionEncodingFormatEnum = {
    Hex: 'hex'
} as const;
export type EthereumTransactionEncodingFormatEnum = typeof EthereumTransactionEncodingFormatEnum[keyof typeof EthereumTransactionEncodingFormatEnum];


/**
 * Check if a given object implements the EthereumTransaction interface.
 */
export function instanceOfEthereumTransaction(value: object): value is EthereumTransaction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('transactionType' in value) || value['transactionType'] === undefined) return false;
    if (!('encodingFormat' in value) || value['encodingFormat'] === undefined) return false;
    if (!('tx' in value) || value['tx'] === undefined) return false;
    if (!('encodedTx' in value) || value['encodedTx'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function EthereumTransactionFromJSON(json: any): EthereumTransaction {
    return EthereumTransactionFromJSONTyped(json, false);
}

export function EthereumTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'transactionType': json['transactionType'],
        'encodingFormat': json['encodingFormat'],
        'tx': EthereumTransactionTxFromJSON(json['tx']),
        'encodedTx': json['encodedTx'],
        'description': json['description'],
    };
}

export function EthereumTransactionToJSON(json: any): EthereumTransaction {
    return EthereumTransactionToJSONTyped(json, false);
}

export function EthereumTransactionToJSONTyped(value?: EthereumTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'transactionType': value['transactionType'],
        'encodingFormat': value['encodingFormat'],
        'tx': EthereumTransactionTxToJSON(value['tx']),
        'encodedTx': value['encodedTx'],
        'description': value['description'],
    };
}

