/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumTransaction } from './EthereumTransaction';
import {
    EthereumTransactionFromJSON,
    EthereumTransactionFromJSONTyped,
    EthereumTransactionToJSON,
    EthereumTransactionToJSONTyped,
} from './EthereumTransaction';

/**
 * 
 * @export
 * @interface EthereumWithdrawResponse
 */
export interface EthereumWithdrawResponse {
    /**
     * 
     * @type {EthereumTransaction}
     * @memberof EthereumWithdrawResponse
     */
    withdrawalTransaction: EthereumTransaction;
}

/**
 * Check if a given object implements the EthereumWithdrawResponse interface.
 */
export function instanceOfEthereumWithdrawResponse(value: object): value is EthereumWithdrawResponse {
    if (!('withdrawalTransaction' in value) || value['withdrawalTransaction'] === undefined) return false;
    return true;
}

export function EthereumWithdrawResponseFromJSON(json: any): EthereumWithdrawResponse {
    return EthereumWithdrawResponseFromJSONTyped(json, false);
}

export function EthereumWithdrawResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumWithdrawResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'withdrawalTransaction': EthereumTransactionFromJSON(json['withdrawalTransaction']),
    };
}

export function EthereumWithdrawResponseToJSON(json: any): EthereumWithdrawResponse {
    return EthereumWithdrawResponseToJSONTyped(json, false);
}

export function EthereumWithdrawResponseToJSONTyped(value?: EthereumWithdrawResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'withdrawalTransaction': EthereumTransactionToJSON(value['withdrawalTransaction']),
    };
}

