/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EthereumCancelStakeResponse
 */
export interface EthereumCancelStakeResponse {
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumCancelStakeResponse
     */
    validatorPublicKey: string;
}

/**
 * Check if a given object implements the EthereumCancelStakeResponse interface.
 */
export function instanceOfEthereumCancelStakeResponse(value: object): value is EthereumCancelStakeResponse {
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    return true;
}

export function EthereumCancelStakeResponseFromJSON(json: any): EthereumCancelStakeResponse {
    return EthereumCancelStakeResponseFromJSONTyped(json, false);
}

export function EthereumCancelStakeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumCancelStakeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorPublicKey': json['validatorPublicKey'],
    };
}

export function EthereumCancelStakeResponseToJSON(json: any): EthereumCancelStakeResponse {
    return EthereumCancelStakeResponseToJSONTyped(json, false);
}

export function EthereumCancelStakeResponseToJSONTyped(value?: EthereumCancelStakeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorPublicKey': value['validatorPublicKey'],
    };
}

