/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumTransaction } from './EthereumTransaction';
import {
    EthereumTransactionFromJSON,
    EthereumTransactionFromJSONTyped,
    EthereumTransactionToJSON,
    EthereumTransactionToJSONTyped,
} from './EthereumTransaction';

/**
 * 
 * @export
 * @interface EthereumTopupResponse
 */
export interface EthereumTopupResponse {
    /**
     * 
     * @type {EthereumTransaction}
     * @memberof EthereumTopupResponse
     */
    topupTransaction: EthereumTransaction;
}

/**
 * Check if a given object implements the EthereumTopupResponse interface.
 */
export function instanceOfEthereumTopupResponse(value: object): value is EthereumTopupResponse {
    if (!('topupTransaction' in value) || value['topupTransaction'] === undefined) return false;
    return true;
}

export function EthereumTopupResponseFromJSON(json: any): EthereumTopupResponse {
    return EthereumTopupResponseFromJSONTyped(json, false);
}

export function EthereumTopupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumTopupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'topupTransaction': EthereumTransactionFromJSON(json['topupTransaction']),
    };
}

export function EthereumTopupResponseToJSON(json: any): EthereumTopupResponse {
    return EthereumTopupResponseToJSONTyped(json, false);
}

export function EthereumTopupResponseToJSONTyped(value?: EthereumTopupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topupTransaction': EthereumTransactionToJSON(value['topupTransaction']),
    };
}

