/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumWithdrawResponse } from './EthereumWithdrawResponse';
import {
    EthereumWithdrawResponseFromJSON,
    EthereumWithdrawResponseFromJSONTyped,
    EthereumWithdrawResponseToJSON,
    EthereumWithdrawResponseToJSONTyped,
} from './EthereumWithdrawResponse';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface EthereumWithdraw200Response
 */
export interface EthereumWithdraw200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumWithdraw200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumWithdrawResponse}
     * @memberof EthereumWithdraw200Response
     */
    data?: EthereumWithdrawResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumWithdraw200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumWithdraw200Response interface.
 */
export function instanceOfEthereumWithdraw200Response(value: object): value is EthereumWithdraw200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumWithdraw200ResponseFromJSON(json: any): EthereumWithdraw200Response {
    return EthereumWithdraw200ResponseFromJSONTyped(json, false);
}

export function EthereumWithdraw200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumWithdraw200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumWithdrawResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumWithdraw200ResponseToJSON(json: any): EthereumWithdraw200Response {
    return EthereumWithdraw200ResponseToJSONTyped(json, false);
}

export function EthereumWithdraw200ResponseToJSONTyped(value?: EthereumWithdraw200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumWithdrawResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

