/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumValidator } from './EthereumValidator';
import {
    EthereumValidatorFromJSON,
    EthereumValidatorFromJSONTyped,
    EthereumValidatorToJSON,
    EthereumValidatorToJSONTyped,
} from './EthereumValidator';

/**
 * 
 * @export
 * @interface EthereumGetValidatorsResponse
 */
export interface EthereumGetValidatorsResponse {
    /**
     * 
     * @type {Array<EthereumValidator>}
     * @memberof EthereumGetValidatorsResponse
     */
    validators: Array<EthereumValidator>;
}

/**
 * Check if a given object implements the EthereumGetValidatorsResponse interface.
 */
export function instanceOfEthereumGetValidatorsResponse(value: object): value is EthereumGetValidatorsResponse {
    if (!('validators' in value) || value['validators'] === undefined) return false;
    return true;
}

export function EthereumGetValidatorsResponseFromJSON(json: any): EthereumGetValidatorsResponse {
    return EthereumGetValidatorsResponseFromJSONTyped(json, false);
}

export function EthereumGetValidatorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumGetValidatorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'validators': ((json['validators'] as Array<any>).map(EthereumValidatorFromJSON)),
    };
}

export function EthereumGetValidatorsResponseToJSON(json: any): EthereumGetValidatorsResponse {
    return EthereumGetValidatorsResponseToJSONTyped(json, false);
}

export function EthereumGetValidatorsResponseToJSONTyped(value?: EthereumGetValidatorsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validators': ((value['validators'] as Array<any>).map(EthereumValidatorToJSON)),
    };
}

