/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumValidator } from './EthereumValidator';
import {
    EthereumValidatorFromJSON,
    EthereumValidatorFromJSONTyped,
    EthereumValidatorToJSON,
    EthereumValidatorToJSONTyped,
} from './EthereumValidator';
import type { EthereumTransaction } from './EthereumTransaction';
import {
    EthereumTransactionFromJSON,
    EthereumTransactionFromJSONTyped,
    EthereumTransactionToJSON,
    EthereumTransactionToJSONTyped,
} from './EthereumTransaction';

/**
 * 
 * @export
 * @interface EthereumStakeResponse
 */
export interface EthereumStakeResponse {
    /**
     * Batch identifier for this stake operation
     * @type {string}
     * @memberof EthereumStakeResponse
     */
    validatorBatchId: string;
    /**
     * 
     * @type {Array<EthereumValidator>}
     * @memberof EthereumStakeResponse
     */
    validators: Array<EthereumValidator>;
    /**
     * 
     * @type {EthereumTransaction}
     * @memberof EthereumStakeResponse
     */
    depositTransaction: EthereumTransaction;
}

/**
 * Check if a given object implements the EthereumStakeResponse interface.
 */
export function instanceOfEthereumStakeResponse(value: object): value is EthereumStakeResponse {
    if (!('validatorBatchId' in value) || value['validatorBatchId'] === undefined) return false;
    if (!('validators' in value) || value['validators'] === undefined) return false;
    if (!('depositTransaction' in value) || value['depositTransaction'] === undefined) return false;
    return true;
}

export function EthereumStakeResponseFromJSON(json: any): EthereumStakeResponse {
    return EthereumStakeResponseFromJSONTyped(json, false);
}

export function EthereumStakeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumStakeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorBatchId': json['validatorBatchId'],
        'validators': ((json['validators'] as Array<any>).map(EthereumValidatorFromJSON)),
        'depositTransaction': EthereumTransactionFromJSON(json['depositTransaction']),
    };
}

export function EthereumStakeResponseToJSON(json: any): EthereumStakeResponse {
    return EthereumStakeResponseToJSONTyped(json, false);
}

export function EthereumStakeResponseToJSONTyped(value?: EthereumStakeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorBatchId': value['validatorBatchId'],
        'validators': ((value['validators'] as Array<any>).map(EthereumValidatorToJSON)),
        'depositTransaction': EthereumTransactionToJSON(value['depositTransaction']),
    };
}

