/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EthereumConfirmStakeResponse
 */
export interface EthereumConfirmStakeResponse {
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumConfirmStakeResponse
     */
    validatorPublicKey: string;
}

/**
 * Check if a given object implements the EthereumConfirmStakeResponse interface.
 */
export function instanceOfEthereumConfirmStakeResponse(value: object): value is EthereumConfirmStakeResponse {
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    return true;
}

export function EthereumConfirmStakeResponseFromJSON(json: any): EthereumConfirmStakeResponse {
    return EthereumConfirmStakeResponseFromJSONTyped(json, false);
}

export function EthereumConfirmStakeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumConfirmStakeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorPublicKey': json['validatorPublicKey'],
    };
}

export function EthereumConfirmStakeResponseToJSON(json: any): EthereumConfirmStakeResponse {
    return EthereumConfirmStakeResponseToJSONTyped(json, false);
}

export function EthereumConfirmStakeResponseToJSONTyped(value?: EthereumConfirmStakeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorPublicKey': value['validatorPublicKey'],
    };
}

