/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumConfirmStakeResponse } from './EthereumConfirmStakeResponse';
import {
    EthereumConfirmStakeResponseFromJSON,
    EthereumConfirmStakeResponseFromJSONTyped,
    EthereumConfirmStakeResponseToJSON,
    EthereumConfirmStakeResponseToJSONTyped,
} from './EthereumConfirmStakeResponse';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface EthereumConfirmStake200Response
 */
export interface EthereumConfirmStake200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumConfirmStake200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumConfirmStakeResponse}
     * @memberof EthereumConfirmStake200Response
     */
    data?: EthereumConfirmStakeResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumConfirmStake200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumConfirmStake200Response interface.
 */
export function instanceOfEthereumConfirmStake200Response(value: object): value is EthereumConfirmStake200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumConfirmStake200ResponseFromJSON(json: any): EthereumConfirmStake200Response {
    return EthereumConfirmStake200ResponseFromJSONTyped(json, false);
}

export function EthereumConfirmStake200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumConfirmStake200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumConfirmStakeResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumConfirmStake200ResponseToJSON(json: any): EthereumConfirmStake200Response {
    return EthereumConfirmStake200ResponseToJSONTyped(json, false);
}

export function EthereumConfirmStake200ResponseToJSONTyped(value?: EthereumConfirmStake200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumConfirmStakeResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

