/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';
import type { EthereumValidatorExitRequest } from './EthereumValidatorExitRequest';
import {
    EthereumValidatorExitRequestFromJSON,
    EthereumValidatorExitRequestFromJSONTyped,
    EthereumValidatorExitRequestToJSON,
    EthereumValidatorExitRequestToJSONTyped,
} from './EthereumValidatorExitRequest';

/**
 * 
 * @export
 * @interface EthereumValidator
 */
export interface EthereumValidator {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumValidator
     */
    network: EthereumNetwork;
    /**
     * Customer-supplied label
     * @type {string}
     * @memberof EthereumValidator
     */
    validatorName: string | null;
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumValidator
     */
    validatorPublicKey: string;
    /**
     * Beacon chain validator index, null until activation
     * @type {number}
     * @memberof EthereumValidator
     */
    validatorIndex: number | null;
    /**
     * Credential type (v1: 0x02 compounding only)
     * @type {string}
     * @memberof EthereumValidator
     */
    validatorType: EthereumValidatorValidatorTypeEnum;
    /**
     * Address that receives the principal at exit. Embedded in the 0x02 credentials at deposit time. Null if the indexer is unreachable.
     * @type {string}
     * @memberof EthereumValidator
     */
    withdrawalAddress: string | null;
    /**
     * Execution layer fee recipient. Null if the indexer is unreachable.
     * @type {string}
     * @memberof EthereumValidator
     */
    feeRecipient: string | null;
    /**
     * Current balance in wei. Null when beacon hasn't seen the validator yet (unknown, not zero).
     * @type {string}
     * @memberof EthereumValidator
     */
    balanceWei: string | null;
    /**
     * Protocol effective balance in wei. Null when beacon hasn't seen the validator yet.
     * @type {string}
     * @memberof EthereumValidator
     */
    effectiveBalanceWei: string | null;
    /**
     * Validator lifecycle stage. `pending` = no on-chain deposit observed yet (pre-broadcast or never broadcast). `queued` = deposit on chain, waiting in the Electra pending_deposits queue (no beacon registry entry yet). `activating` = beacon has the validator and it is in the activation queue. `active` = attesting. `exit_pending` = a force-exit tx mined on EL but beacon hasn't ingested it yet. `exiting` = beacon ingested the exit and the validator is winding down. `withdrawn` = principal returned to the withdrawal address.
     * @type {string}
     * @memberof EthereumValidator
     */
    state: EthereumValidatorStateEnum;
    /**
     * Consensus-spec validator state, plus 'unknown' for pubkeys beacon hasn't ingested (pre-deposit, in the activation lag window, or absent entirely).
     * @type {string}
     * @memberof EthereumValidator
     */
    consensusLayerState: EthereumValidatorConsensusLayerStateEnum;
    /**
     * Indexer status: planned/active/deactivated; 'pending' before the deposit is observed on chain; 'unknown' if the validator exists in our DB but the indexer has no matching record.
     * @type {string}
     * @memberof EthereumValidator
     */
    indexerState: EthereumValidatorIndexerStateEnum;
    /**
     * ISO 8601 timestamp of activation
     * @type {string}
     * @memberof EthereumValidator
     */
    activatedAt: string | null;
    /**
     * Exit epoch, null if not exiting
     * @type {number}
     * @memberof EthereumValidator
     */
    exitEpoch: number | null;
    /**
     * Epoch after which balance can be withdrawn
     * @type {number}
     * @memberof EthereumValidator
     */
    withdrawableEpoch: number | null;
    /**
     * 
     * @type {EthereumValidatorExitRequest}
     * @memberof EthereumValidator
     */
    exitRequest: EthereumValidatorExitRequest | null;
}


/**
 * @export
 */
export const EthereumValidatorValidatorTypeEnum = {
    _0x02: '0x02'
} as const;
export type EthereumValidatorValidatorTypeEnum = typeof EthereumValidatorValidatorTypeEnum[keyof typeof EthereumValidatorValidatorTypeEnum];

/**
 * @export
 */
export const EthereumValidatorStateEnum = {
    Pending: 'pending',
    Queued: 'queued',
    Activating: 'activating',
    Active: 'active',
    ExitPending: 'exit_pending',
    Exiting: 'exiting',
    Withdrawn: 'withdrawn'
} as const;
export type EthereumValidatorStateEnum = typeof EthereumValidatorStateEnum[keyof typeof EthereumValidatorStateEnum];

/**
 * @export
 */
export const EthereumValidatorConsensusLayerStateEnum = {
    PendingInitialized: 'pending_initialized',
    PendingQueued: 'pending_queued',
    ActiveOngoing: 'active_ongoing',
    ActiveExiting: 'active_exiting',
    ActiveSlashed: 'active_slashed',
    ExitedUnslashed: 'exited_unslashed',
    ExitedSlashed: 'exited_slashed',
    WithdrawalPossible: 'withdrawal_possible',
    WithdrawalDone: 'withdrawal_done',
    Unknown: 'unknown'
} as const;
export type EthereumValidatorConsensusLayerStateEnum = typeof EthereumValidatorConsensusLayerStateEnum[keyof typeof EthereumValidatorConsensusLayerStateEnum];

/**
 * @export
 */
export const EthereumValidatorIndexerStateEnum = {
    Planned: 'planned',
    Active: 'active',
    Deactivated: 'deactivated',
    Pending: 'pending',
    Unknown: 'unknown'
} as const;
export type EthereumValidatorIndexerStateEnum = typeof EthereumValidatorIndexerStateEnum[keyof typeof EthereumValidatorIndexerStateEnum];


/**
 * Check if a given object implements the EthereumValidator interface.
 */
export function instanceOfEthereumValidator(value: object): value is EthereumValidator {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorName' in value) || value['validatorName'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    if (!('validatorIndex' in value) || value['validatorIndex'] === undefined) return false;
    if (!('validatorType' in value) || value['validatorType'] === undefined) return false;
    if (!('withdrawalAddress' in value) || value['withdrawalAddress'] === undefined) return false;
    if (!('feeRecipient' in value) || value['feeRecipient'] === undefined) return false;
    if (!('balanceWei' in value) || value['balanceWei'] === undefined) return false;
    if (!('effectiveBalanceWei' in value) || value['effectiveBalanceWei'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('consensusLayerState' in value) || value['consensusLayerState'] === undefined) return false;
    if (!('indexerState' in value) || value['indexerState'] === undefined) return false;
    if (!('activatedAt' in value) || value['activatedAt'] === undefined) return false;
    if (!('exitEpoch' in value) || value['exitEpoch'] === undefined) return false;
    if (!('withdrawableEpoch' in value) || value['withdrawableEpoch'] === undefined) return false;
    if (!('exitRequest' in value) || value['exitRequest'] === undefined) return false;
    return true;
}

export function EthereumValidatorFromJSON(json: any): EthereumValidator {
    return EthereumValidatorFromJSONTyped(json, false);
}

export function EthereumValidatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumValidator {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorName': json['validatorName'],
        'validatorPublicKey': json['validatorPublicKey'],
        'validatorIndex': json['validatorIndex'],
        'validatorType': json['validatorType'],
        'withdrawalAddress': json['withdrawalAddress'],
        'feeRecipient': json['feeRecipient'],
        'balanceWei': json['balanceWei'],
        'effectiveBalanceWei': json['effectiveBalanceWei'],
        'state': json['state'],
        'consensusLayerState': json['consensusLayerState'],
        'indexerState': json['indexerState'],
        'activatedAt': json['activatedAt'],
        'exitEpoch': json['exitEpoch'],
        'withdrawableEpoch': json['withdrawableEpoch'],
        'exitRequest': EthereumValidatorExitRequestFromJSON(json['exitRequest']),
    };
}

export function EthereumValidatorToJSON(json: any): EthereumValidator {
    return EthereumValidatorToJSONTyped(json, false);
}

export function EthereumValidatorToJSONTyped(value?: EthereumValidator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorName': value['validatorName'],
        'validatorPublicKey': value['validatorPublicKey'],
        'validatorIndex': value['validatorIndex'],
        'validatorType': value['validatorType'],
        'withdrawalAddress': value['withdrawalAddress'],
        'feeRecipient': value['feeRecipient'],
        'balanceWei': value['balanceWei'],
        'effectiveBalanceWei': value['effectiveBalanceWei'],
        'state': value['state'],
        'consensusLayerState': value['consensusLayerState'],
        'indexerState': value['indexerState'],
        'activatedAt': value['activatedAt'],
        'exitEpoch': value['exitEpoch'],
        'withdrawableEpoch': value['withdrawableEpoch'],
        'exitRequest': EthereumValidatorExitRequestToJSON(value['exitRequest']),
    };
}

