/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumCancelStakeRequest
 */
export interface EthereumCancelStakeRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumCancelStakeRequest
     */
    network: EthereumNetwork;
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumCancelStakeRequest
     */
    validatorPublicKey: string;
}



/**
 * Check if a given object implements the EthereumCancelStakeRequest interface.
 */
export function instanceOfEthereumCancelStakeRequest(value: object): value is EthereumCancelStakeRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    return true;
}

export function EthereumCancelStakeRequestFromJSON(json: any): EthereumCancelStakeRequest {
    return EthereumCancelStakeRequestFromJSONTyped(json, false);
}

export function EthereumCancelStakeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumCancelStakeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorPublicKey': json['validatorPublicKey'],
    };
}

export function EthereumCancelStakeRequestToJSON(json: any): EthereumCancelStakeRequest {
    return EthereumCancelStakeRequestToJSONTyped(json, false);
}

export function EthereumCancelStakeRequestToJSONTyped(value?: EthereumCancelStakeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorPublicKey': value['validatorPublicKey'],
    };
}

