/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Latest EIP-7002 request for this pubkey. Null if there's no recent exit or partial-withdrawal request.
 * @export
 * @interface EthereumValidatorExitRequest
 */
export interface EthereumValidatorExitRequest {
    /**
     * EL transaction hash that called the EIP-7002 predeploy
     * @type {string}
     * @memberof EthereumValidatorExitRequest
     */
    txHash: string;
    /**
     * EL block in which the request was mined
     * @type {number}
     * @memberof EthereumValidatorExitRequest
     */
    blockNumber: number;
    /**
     * Requested amount in gwei. `0` means full exit; otherwise partial withdrawal.
     * @type {string}
     * @memberof EthereumValidatorExitRequest
     */
    amountGwei: string;
}

/**
 * Check if a given object implements the EthereumValidatorExitRequest interface.
 */
export function instanceOfEthereumValidatorExitRequest(value: object): value is EthereumValidatorExitRequest {
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('amountGwei' in value) || value['amountGwei'] === undefined) return false;
    return true;
}

export function EthereumValidatorExitRequestFromJSON(json: any): EthereumValidatorExitRequest {
    return EthereumValidatorExitRequestFromJSONTyped(json, false);
}

export function EthereumValidatorExitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumValidatorExitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'txHash': json['txHash'],
        'blockNumber': json['blockNumber'],
        'amountGwei': json['amountGwei'],
    };
}

export function EthereumValidatorExitRequestToJSON(json: any): EthereumValidatorExitRequest {
    return EthereumValidatorExitRequestToJSONTyped(json, false);
}

export function EthereumValidatorExitRequestToJSONTyped(value?: EthereumValidatorExitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'txHash': value['txHash'],
        'blockNumber': value['blockNumber'],
        'amountGwei': value['amountGwei'],
    };
}

