/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { EthereumCancelStakeResponse } from './EthereumCancelStakeResponse';
import {
    EthereumCancelStakeResponseFromJSON,
    EthereumCancelStakeResponseFromJSONTyped,
    EthereumCancelStakeResponseToJSON,
    EthereumCancelStakeResponseToJSONTyped,
} from './EthereumCancelStakeResponse';

/**
 * 
 * @export
 * @interface EthereumCancelStake200Response
 */
export interface EthereumCancelStake200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumCancelStake200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumCancelStakeResponse}
     * @memberof EthereumCancelStake200Response
     */
    data?: EthereumCancelStakeResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumCancelStake200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumCancelStake200Response interface.
 */
export function instanceOfEthereumCancelStake200Response(value: object): value is EthereumCancelStake200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumCancelStake200ResponseFromJSON(json: any): EthereumCancelStake200Response {
    return EthereumCancelStake200ResponseFromJSONTyped(json, false);
}

export function EthereumCancelStake200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumCancelStake200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumCancelStakeResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumCancelStake200ResponseToJSON(json: any): EthereumCancelStake200Response {
    return EthereumCancelStake200ResponseToJSONTyped(json, false);
}

export function EthereumCancelStake200ResponseToJSONTyped(value?: EthereumCancelStake200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumCancelStakeResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

