/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumForceExitRequest
 */
export interface EthereumForceExitRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumForceExitRequest
     */
    network: EthereumNetwork;
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumForceExitRequest
     */
    validatorPublicKey: string;
}



/**
 * Check if a given object implements the EthereumForceExitRequest interface.
 */
export function instanceOfEthereumForceExitRequest(value: object): value is EthereumForceExitRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    return true;
}

export function EthereumForceExitRequestFromJSON(json: any): EthereumForceExitRequest {
    return EthereumForceExitRequestFromJSONTyped(json, false);
}

export function EthereumForceExitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumForceExitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorPublicKey': json['validatorPublicKey'],
    };
}

export function EthereumForceExitRequestToJSON(json: any): EthereumForceExitRequest {
    return EthereumForceExitRequestToJSONTyped(json, false);
}

export function EthereumForceExitRequestToJSONTyped(value?: EthereumForceExitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorPublicKey': value['validatorPublicKey'],
    };
}

