/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumConsolidateRequest
 */
export interface EthereumConsolidateRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumConsolidateRequest
     */
    network: EthereumNetwork;
    /**
     * Pubkey of the validator being consolidated. Its balance is moved to the target and it exits.
     * @type {string}
     * @memberof EthereumConsolidateRequest
     */
    sourceValidatorPublicKey: string;
    /**
     * Pubkey of the 0x02 validator that will receive the consolidated balance. Must share the same withdrawal address as source.
     * @type {string}
     * @memberof EthereumConsolidateRequest
     */
    targetValidatorPublicKey: string;
}



/**
 * Check if a given object implements the EthereumConsolidateRequest interface.
 */
export function instanceOfEthereumConsolidateRequest(value: object): value is EthereumConsolidateRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('sourceValidatorPublicKey' in value) || value['sourceValidatorPublicKey'] === undefined) return false;
    if (!('targetValidatorPublicKey' in value) || value['targetValidatorPublicKey'] === undefined) return false;
    return true;
}

export function EthereumConsolidateRequestFromJSON(json: any): EthereumConsolidateRequest {
    return EthereumConsolidateRequestFromJSONTyped(json, false);
}

export function EthereumConsolidateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumConsolidateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'sourceValidatorPublicKey': json['sourceValidatorPublicKey'],
        'targetValidatorPublicKey': json['targetValidatorPublicKey'],
    };
}

export function EthereumConsolidateRequestToJSON(json: any): EthereumConsolidateRequest {
    return EthereumConsolidateRequestToJSONTyped(json, false);
}

export function EthereumConsolidateRequestToJSONTyped(value?: EthereumConsolidateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'sourceValidatorPublicKey': value['sourceValidatorPublicKey'],
        'targetValidatorPublicKey': value['targetValidatorPublicKey'],
    };
}

