/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumStakeResponse } from './EthereumStakeResponse';
import {
    EthereumStakeResponseFromJSON,
    EthereumStakeResponseFromJSONTyped,
    EthereumStakeResponseToJSON,
    EthereumStakeResponseToJSONTyped,
} from './EthereumStakeResponse';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface EthereumStake200Response
 */
export interface EthereumStake200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumStake200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumStakeResponse}
     * @memberof EthereumStake200Response
     */
    data?: EthereumStakeResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumStake200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumStake200Response interface.
 */
export function instanceOfEthereumStake200Response(value: object): value is EthereumStake200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumStake200ResponseFromJSON(json: any): EthereumStake200Response {
    return EthereumStake200ResponseFromJSONTyped(json, false);
}

export function EthereumStake200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumStake200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumStakeResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumStake200ResponseToJSON(json: any): EthereumStake200Response {
    return EthereumStake200ResponseToJSONTyped(json, false);
}

export function EthereumStake200ResponseToJSONTyped(value?: EthereumStake200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumStakeResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

