/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EthereumTransactionTx
 */
export interface EthereumTransactionTx {
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    chainId: string;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    from: string | null;
    /**
     * 
     * @type {number}
     * @memberof EthereumTransactionTx
     */
    nonce: number | null;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    gasLimit: string | null;
    /**
     * 
     * @type {string}
     * @memberof EthereumTransactionTx
     */
    gasPrice: string | null;
}

/**
 * Check if a given object implements the EthereumTransactionTx interface.
 */
export function instanceOfEthereumTransactionTx(value: object): value is EthereumTransactionTx {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('gasLimit' in value) || value['gasLimit'] === undefined) return false;
    if (!('gasPrice' in value) || value['gasPrice'] === undefined) return false;
    return true;
}

export function EthereumTransactionTxFromJSON(json: any): EthereumTransactionTx {
    return EthereumTransactionTxFromJSONTyped(json, false);
}

export function EthereumTransactionTxFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumTransactionTx {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'value': json['value'],
        'data': json['data'],
        'chainId': json['chainId'],
        'from': json['from'],
        'nonce': json['nonce'],
        'gasLimit': json['gasLimit'],
        'gasPrice': json['gasPrice'],
    };
}

export function EthereumTransactionTxToJSON(json: any): EthereumTransactionTx {
    return EthereumTransactionTxToJSONTyped(json, false);
}

export function EthereumTransactionTxToJSONTyped(value?: EthereumTransactionTx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'value': value['value'],
        'data': value['data'],
        'chainId': value['chainId'],
        'from': value['from'],
        'nonce': value['nonce'],
        'gasLimit': value['gasLimit'],
        'gasPrice': value['gasPrice'],
    };
}

