/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { DelegationHistoryItem } from './DelegationHistoryItem';
import {
    DelegationHistoryItemFromJSON,
    DelegationHistoryItemFromJSONTyped,
    DelegationHistoryItemToJSON,
    DelegationHistoryItemToJSONTyped,
} from './DelegationHistoryItem';

/**
 * 
 * @export
 * @interface EthereumGetStakingTxHistory200Response
 */
export interface EthereumGetStakingTxHistory200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumGetStakingTxHistory200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<DelegationHistoryItem>}
     * @memberof EthereumGetStakingTxHistory200Response
     */
    data?: Array<DelegationHistoryItem>;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumGetStakingTxHistory200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumGetStakingTxHistory200Response interface.
 */
export function instanceOfEthereumGetStakingTxHistory200Response(value: object): value is EthereumGetStakingTxHistory200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumGetStakingTxHistory200ResponseFromJSON(json: any): EthereumGetStakingTxHistory200Response {
    return EthereumGetStakingTxHistory200ResponseFromJSONTyped(json, false);
}

export function EthereumGetStakingTxHistory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumGetStakingTxHistory200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DelegationHistoryItemFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumGetStakingTxHistory200ResponseToJSON(json: any): EthereumGetStakingTxHistory200Response {
    return EthereumGetStakingTxHistory200ResponseToJSONTyped(json, false);
}

export function EthereumGetStakingTxHistory200ResponseToJSONTyped(value?: EthereumGetStakingTxHistory200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DelegationHistoryItemToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

