/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { EthereumGetValidatorsResponse } from './EthereumGetValidatorsResponse';
import {
    EthereumGetValidatorsResponseFromJSON,
    EthereumGetValidatorsResponseFromJSONTyped,
    EthereumGetValidatorsResponseToJSON,
    EthereumGetValidatorsResponseToJSONTyped,
} from './EthereumGetValidatorsResponse';

/**
 * 
 * @export
 * @interface EthereumGetValidators200Response
 */
export interface EthereumGetValidators200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumGetValidators200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumGetValidatorsResponse}
     * @memberof EthereumGetValidators200Response
     */
    data?: EthereumGetValidatorsResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumGetValidators200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumGetValidators200Response interface.
 */
export function instanceOfEthereumGetValidators200Response(value: object): value is EthereumGetValidators200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumGetValidators200ResponseFromJSON(json: any): EthereumGetValidators200Response {
    return EthereumGetValidators200ResponseFromJSONTyped(json, false);
}

export function EthereumGetValidators200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumGetValidators200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumGetValidatorsResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumGetValidators200ResponseToJSON(json: any): EthereumGetValidators200Response {
    return EthereumGetValidators200ResponseToJSONTyped(json, false);
}

export function EthereumGetValidators200ResponseToJSONTyped(value?: EthereumGetValidators200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumGetValidatorsResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

