/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumConfirmStakeRequest
 */
export interface EthereumConfirmStakeRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumConfirmStakeRequest
     */
    network: EthereumNetwork;
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumConfirmStakeRequest
     */
    validatorPublicKey: string;
    /**
     * Deposit transaction hash.
     * @type {string}
     * @memberof EthereumConfirmStakeRequest
     */
    depositTxHash: string;
}



/**
 * Check if a given object implements the EthereumConfirmStakeRequest interface.
 */
export function instanceOfEthereumConfirmStakeRequest(value: object): value is EthereumConfirmStakeRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    if (!('depositTxHash' in value) || value['depositTxHash'] === undefined) return false;
    return true;
}

export function EthereumConfirmStakeRequestFromJSON(json: any): EthereumConfirmStakeRequest {
    return EthereumConfirmStakeRequestFromJSONTyped(json, false);
}

export function EthereumConfirmStakeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumConfirmStakeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorPublicKey': json['validatorPublicKey'],
        'depositTxHash': json['depositTxHash'],
    };
}

export function EthereumConfirmStakeRequestToJSON(json: any): EthereumConfirmStakeRequest {
    return EthereumConfirmStakeRequestToJSONTyped(json, false);
}

export function EthereumConfirmStakeRequestToJSONTyped(value?: EthereumConfirmStakeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorPublicKey': value['validatorPublicKey'],
        'depositTxHash': value['depositTxHash'],
    };
}

