/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumExitRequest
 */
export interface EthereumExitRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumExitRequest
     */
    network: EthereumNetwork;
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumExitRequest
     */
    validatorPublicKey: string;
}



/**
 * Check if a given object implements the EthereumExitRequest interface.
 */
export function instanceOfEthereumExitRequest(value: object): value is EthereumExitRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    return true;
}

export function EthereumExitRequestFromJSON(json: any): EthereumExitRequest {
    return EthereumExitRequestFromJSONTyped(json, false);
}

export function EthereumExitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumExitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorPublicKey': json['validatorPublicKey'],
    };
}

export function EthereumExitRequestToJSON(json: any): EthereumExitRequest {
    return EthereumExitRequestToJSONTyped(json, false);
}

export function EthereumExitRequestToJSONTyped(value?: EthereumExitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorPublicKey': value['validatorPublicKey'],
    };
}

