/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumWithdrawRequest
 */
export interface EthereumWithdrawRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumWithdrawRequest
     */
    network: EthereumNetwork;
    /**
     * 48-byte BLS validator public key
     * @type {string}
     * @memberof EthereumWithdrawRequest
     */
    validatorPublicKey: string;
    /**
     * Amount to withdraw in wei. Must be at least 1 gwei (use /force-exit for full exit). Protocol caps at effectiveBalance - 32 ETH.
     * @type {string}
     * @memberof EthereumWithdrawRequest
     */
    amountWei: string;
}



/**
 * Check if a given object implements the EthereumWithdrawRequest interface.
 */
export function instanceOfEthereumWithdrawRequest(value: object): value is EthereumWithdrawRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    if (!('amountWei' in value) || value['amountWei'] === undefined) return false;
    return true;
}

export function EthereumWithdrawRequestFromJSON(json: any): EthereumWithdrawRequest {
    return EthereumWithdrawRequestFromJSONTyped(json, false);
}

export function EthereumWithdrawRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumWithdrawRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorPublicKey': json['validatorPublicKey'],
        'amountWei': json['amountWei'],
    };
}

export function EthereumWithdrawRequestToJSON(json: any): EthereumWithdrawRequest {
    return EthereumWithdrawRequestToJSONTyped(json, false);
}

export function EthereumWithdrawRequestToJSONTyped(value?: EthereumWithdrawRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorPublicKey': value['validatorPublicKey'],
        'amountWei': value['amountWei'],
    };
}

