/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { EthereumConsolidateResponse } from './EthereumConsolidateResponse';
import {
    EthereumConsolidateResponseFromJSON,
    EthereumConsolidateResponseFromJSONTyped,
    EthereumConsolidateResponseToJSON,
    EthereumConsolidateResponseToJSONTyped,
} from './EthereumConsolidateResponse';

/**
 * 
 * @export
 * @interface EthereumConsolidate200Response
 */
export interface EthereumConsolidate200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumConsolidate200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumConsolidateResponse}
     * @memberof EthereumConsolidate200Response
     */
    data?: EthereumConsolidateResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumConsolidate200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumConsolidate200Response interface.
 */
export function instanceOfEthereumConsolidate200Response(value: object): value is EthereumConsolidate200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumConsolidate200ResponseFromJSON(json: any): EthereumConsolidate200Response {
    return EthereumConsolidate200ResponseFromJSONTyped(json, false);
}

export function EthereumConsolidate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumConsolidate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumConsolidateResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumConsolidate200ResponseToJSON(json: any): EthereumConsolidate200Response {
    return EthereumConsolidate200ResponseToJSONTyped(json, false);
}

export function EthereumConsolidate200ResponseToJSONTyped(value?: EthereumConsolidate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumConsolidateResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

