/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumForceExitResponse } from './EthereumForceExitResponse';
import {
    EthereumForceExitResponseFromJSON,
    EthereumForceExitResponseFromJSONTyped,
    EthereumForceExitResponseToJSON,
    EthereumForceExitResponseToJSONTyped,
} from './EthereumForceExitResponse';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface EthereumForceExit200Response
 */
export interface EthereumForceExit200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumForceExit200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumForceExitResponse}
     * @memberof EthereumForceExit200Response
     */
    data?: EthereumForceExitResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumForceExit200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumForceExit200Response interface.
 */
export function instanceOfEthereumForceExit200Response(value: object): value is EthereumForceExit200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumForceExit200ResponseFromJSON(json: any): EthereumForceExit200Response {
    return EthereumForceExit200ResponseFromJSONTyped(json, false);
}

export function EthereumForceExit200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumForceExit200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumForceExitResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumForceExit200ResponseToJSON(json: any): EthereumForceExit200Response {
    return EthereumForceExit200ResponseToJSONTyped(json, false);
}

export function EthereumForceExit200ResponseToJSONTyped(value?: EthereumForceExit200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumForceExitResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

