/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumTopupRequest
 */
export interface EthereumTopupRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumTopupRequest
     */
    network: EthereumNetwork;
    /**
     * Pubkey of the existing 0x02 validator to top up. Withdrawal credentials and fee recipient are reused.
     * @type {string}
     * @memberof EthereumTopupRequest
     */
    validatorPublicKey: string;
    /**
     * Amount to deposit in wei. Must be between 1 and 2048 ETH
     * @type {string}
     * @memberof EthereumTopupRequest
     */
    amountWei: string;
}



/**
 * Check if a given object implements the EthereumTopupRequest interface.
 */
export function instanceOfEthereumTopupRequest(value: object): value is EthereumTopupRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('validatorPublicKey' in value) || value['validatorPublicKey'] === undefined) return false;
    if (!('amountWei' in value) || value['amountWei'] === undefined) return false;
    return true;
}

export function EthereumTopupRequestFromJSON(json: any): EthereumTopupRequest {
    return EthereumTopupRequestFromJSONTyped(json, false);
}

export function EthereumTopupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumTopupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'validatorPublicKey': json['validatorPublicKey'],
        'amountWei': json['amountWei'],
    };
}

export function EthereumTopupRequestToJSON(json: any): EthereumTopupRequest {
    return EthereumTopupRequestToJSONTyped(json, false);
}

export function EthereumTopupRequestToJSONTyped(value?: EthereumTopupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'validatorPublicKey': value['validatorPublicKey'],
        'amountWei': value['amountWei'],
    };
}

