/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumTopupResponse } from './EthereumTopupResponse';
import {
    EthereumTopupResponseFromJSON,
    EthereumTopupResponseFromJSONTyped,
    EthereumTopupResponseToJSON,
    EthereumTopupResponseToJSONTyped,
} from './EthereumTopupResponse';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface EthereumTopup200Response
 */
export interface EthereumTopup200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumTopup200Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumTopupResponse}
     * @memberof EthereumTopup200Response
     */
    data?: EthereumTopupResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumTopup200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumTopup200Response interface.
 */
export function instanceOfEthereumTopup200Response(value: object): value is EthereumTopup200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumTopup200ResponseFromJSON(json: any): EthereumTopup200Response {
    return EthereumTopup200ResponseFromJSONTyped(json, false);
}

export function EthereumTopup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumTopup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumTopupResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumTopup200ResponseToJSON(json: any): EthereumTopup200Response {
    return EthereumTopup200ResponseToJSONTyped(json, false);
}

export function EthereumTopup200ResponseToJSONTyped(value?: EthereumTopup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumTopupResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

