/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumTransaction } from './EthereumTransaction';
import {
    EthereumTransactionFromJSON,
    EthereumTransactionFromJSONTyped,
    EthereumTransactionToJSON,
    EthereumTransactionToJSONTyped,
} from './EthereumTransaction';

/**
 * 
 * @export
 * @interface EthereumConsolidateResponse
 */
export interface EthereumConsolidateResponse {
    /**
     * 
     * @type {EthereumTransaction}
     * @memberof EthereumConsolidateResponse
     */
    consolidationTransaction: EthereumTransaction;
}

/**
 * Check if a given object implements the EthereumConsolidateResponse interface.
 */
export function instanceOfEthereumConsolidateResponse(value: object): value is EthereumConsolidateResponse {
    if (!('consolidationTransaction' in value) || value['consolidationTransaction'] === undefined) return false;
    return true;
}

export function EthereumConsolidateResponseFromJSON(json: any): EthereumConsolidateResponse {
    return EthereumConsolidateResponseFromJSONTyped(json, false);
}

export function EthereumConsolidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumConsolidateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'consolidationTransaction': EthereumTransactionFromJSON(json['consolidationTransaction']),
    };
}

export function EthereumConsolidateResponseToJSON(json: any): EthereumConsolidateResponse {
    return EthereumConsolidateResponseToJSONTyped(json, false);
}

export function EthereumConsolidateResponseToJSONTyped(value?: EthereumConsolidateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consolidationTransaction': EthereumTransactionToJSON(value['consolidationTransaction']),
    };
}

