/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumNetwork } from './EthereumNetwork';
import {
    EthereumNetworkFromJSON,
    EthereumNetworkFromJSONTyped,
    EthereumNetworkToJSON,
    EthereumNetworkToJSONTyped,
} from './EthereumNetwork';

/**
 * 
 * @export
 * @interface EthereumStakeRequest
 */
export interface EthereumStakeRequest {
    /**
     * 
     * @type {EthereumNetwork}
     * @memberof EthereumStakeRequest
     */
    network: EthereumNetwork;
    /**
     * Amount to deposit in wei. Must be a whole-ETH multiple between 32 and 2048 ETH.
     * @type {string}
     * @memberof EthereumStakeRequest
     */
    amountWei: string;
    /**
     * Execution layer address for withdrawal credentials
     * @type {string}
     * @memberof EthereumStakeRequest
     */
    withdrawalAddress: string;
    /**
     * Execution layer address receiving execution layer tips. Currently informational — fee recipient is set on the validator client at deploy time.
     * @type {string}
     * @memberof EthereumStakeRequest
     */
    feeRecipient: string;
    /**
     * Customer-supplied label for the validator. Must be unique within the organization. Max 32 chars. In local/dev/staging it must start with the environment moniker prefix (e.g. "staging-"). No leading/trailing whitespace.
     * @type {string}
     * @memberof EthereumStakeRequest
     */
    validatorName: string;
    /**
     * Gas-limit vote applied when this validator proposes a block. Currently informational — accepted and stored for forward compatibility.
     * @type {number}
     * @memberof EthereumStakeRequest
     */
    gasLimit?: number;
}



/**
 * Check if a given object implements the EthereumStakeRequest interface.
 */
export function instanceOfEthereumStakeRequest(value: object): value is EthereumStakeRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('amountWei' in value) || value['amountWei'] === undefined) return false;
    if (!('withdrawalAddress' in value) || value['withdrawalAddress'] === undefined) return false;
    if (!('feeRecipient' in value) || value['feeRecipient'] === undefined) return false;
    if (!('validatorName' in value) || value['validatorName'] === undefined) return false;
    return true;
}

export function EthereumStakeRequestFromJSON(json: any): EthereumStakeRequest {
    return EthereumStakeRequestFromJSONTyped(json, false);
}

export function EthereumStakeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumStakeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': EthereumNetworkFromJSON(json['network']),
        'amountWei': json['amountWei'],
        'withdrawalAddress': json['withdrawalAddress'],
        'feeRecipient': json['feeRecipient'],
        'validatorName': json['validatorName'],
        'gasLimit': json['gasLimit'] == null ? undefined : json['gasLimit'],
    };
}

export function EthereumStakeRequestToJSON(json: any): EthereumStakeRequest {
    return EthereumStakeRequestToJSONTyped(json, false);
}

export function EthereumStakeRequestToJSONTyped(value?: EthereumStakeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': EthereumNetworkToJSON(value['network']),
        'amountWei': value['amountWei'],
        'withdrawalAddress': value['withdrawalAddress'],
        'feeRecipient': value['feeRecipient'],
        'validatorName': value['validatorName'],
        'gasLimit': value['gasLimit'],
    };
}

