/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { DailyRewardItem } from './DailyRewardItem';
import {
    DailyRewardItemFromJSON,
    DailyRewardItemFromJSONTyped,
    DailyRewardItemToJSON,
    DailyRewardItemToJSONTyped,
} from './DailyRewardItem';

/**
 * 
 * @export
 * @interface EthereumGetDailyRewardsHistory200Response
 */
export interface EthereumGetDailyRewardsHistory200Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumGetDailyRewardsHistory200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<DailyRewardItem>}
     * @memberof EthereumGetDailyRewardsHistory200Response
     */
    data?: Array<DailyRewardItem>;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumGetDailyRewardsHistory200Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumGetDailyRewardsHistory200Response interface.
 */
export function instanceOfEthereumGetDailyRewardsHistory200Response(value: object): value is EthereumGetDailyRewardsHistory200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumGetDailyRewardsHistory200ResponseFromJSON(json: any): EthereumGetDailyRewardsHistory200Response {
    return EthereumGetDailyRewardsHistory200ResponseFromJSONTyped(json, false);
}

export function EthereumGetDailyRewardsHistory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumGetDailyRewardsHistory200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DailyRewardItemFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumGetDailyRewardsHistory200ResponseToJSON(json: any): EthereumGetDailyRewardsHistory200Response {
    return EthereumGetDailyRewardsHistory200ResponseToJSONTyped(json, false);
}

export function EthereumGetDailyRewardsHistory200ResponseToJSONTyped(value?: EthereumGetDailyRewardsHistory200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DailyRewardItemToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

