/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EthereumExitResponse } from './EthereumExitResponse';
import {
    EthereumExitResponseFromJSON,
    EthereumExitResponseFromJSONTyped,
    EthereumExitResponseToJSON,
    EthereumExitResponseToJSONTyped,
} from './EthereumExitResponse';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface EthereumExit202Response
 */
export interface EthereumExit202Response {
    /**
     * 
     * @type {boolean}
     * @memberof EthereumExit202Response
     */
    success: boolean;
    /**
     * 
     * @type {EthereumExitResponse}
     * @memberof EthereumExit202Response
     */
    data?: EthereumExitResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof EthereumExit202Response
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the EthereumExit202Response interface.
 */
export function instanceOfEthereumExit202Response(value: object): value is EthereumExit202Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function EthereumExit202ResponseFromJSON(json: any): EthereumExit202Response {
    return EthereumExit202ResponseFromJSONTyped(json, false);
}

export function EthereumExit202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumExit202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : EthereumExitResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function EthereumExit202ResponseToJSON(json: any): EthereumExit202Response {
    return EthereumExit202ResponseToJSONTyped(json, false);
}

export function EthereumExit202ResponseToJSONTyped(value?: EthereumExit202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EthereumExitResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

