/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Target Ethereum network
 * @export
 */
export const EthereumNetwork = {
    Ethereum: 'ethereum',
    EthereumHoodiTestnet: 'ethereum-hoodi-testnet'
} as const;
export type EthereumNetwork = typeof EthereumNetwork[keyof typeof EthereumNetwork];


export function instanceOfEthereumNetwork(value: any): boolean {
    for (const key in EthereumNetwork) {
        if (Object.prototype.hasOwnProperty.call(EthereumNetwork, key)) {
            if (EthereumNetwork[key as keyof typeof EthereumNetwork] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EthereumNetworkFromJSON(json: any): EthereumNetwork {
    return EthereumNetworkFromJSONTyped(json, false);
}

export function EthereumNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthereumNetwork {
    return json as EthereumNetwork;
}

export function EthereumNetworkToJSON(value?: EthereumNetwork | null): any {
    return value as any;
}

export function EthereumNetworkToJSONTyped(value: any, ignoreDiscriminator: boolean): EthereumNetwork {
    return value as EthereumNetwork;
}

