/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * List of entities
 * @export
 * @interface GetEntitiesResponse
 */
export interface GetEntitiesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetEntitiesResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<Entity>}
     * @memberof GetEntitiesResponse
     */
    data?: Array<Entity>;
    /**
     * 
     * @type {ApiError}
     * @memberof GetEntitiesResponse
     */
    error?: ApiError;
    /**
     * Number of entities returned
     * @type {number}
     * @memberof GetEntitiesResponse
     */
    count: number;
}

/**
 * Check if a given object implements the GetEntitiesResponse interface.
 */
export function instanceOfGetEntitiesResponse(value: object): value is GetEntitiesResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetEntitiesResponseFromJSON(json: any): GetEntitiesResponse {
    return GetEntitiesResponseFromJSONTyped(json, false);
}

export function GetEntitiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEntitiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EntityFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
        'count': json['count'],
    };
}

export function GetEntitiesResponseToJSON(json: any): GetEntitiesResponse {
    return GetEntitiesResponseToJSONTyped(json, false);
}

export function GetEntitiesResponseToJSONTyped(value?: GetEntitiesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EntityToJSON)),
        'error': ApiErrorToJSON(value['error']),
        'count': value['count'],
    };
}

