/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealthStatus200Response
 */
export interface GetHealthStatus200Response {
    /**
     * 
     * @type {string}
     * @memberof GetHealthStatus200Response
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GetHealthStatus200Response
     */
    timestamp: string;
    /**
     * 
     * @type {number}
     * @memberof GetHealthStatus200Response
     */
    uptime: number;
}

/**
 * Check if a given object implements the GetHealthStatus200Response interface.
 */
export function instanceOfGetHealthStatus200Response(value: object): value is GetHealthStatus200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    return true;
}

export function GetHealthStatus200ResponseFromJSON(json: any): GetHealthStatus200Response {
    return GetHealthStatus200ResponseFromJSONTyped(json, false);
}

export function GetHealthStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealthStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': json['timestamp'],
        'uptime': json['uptime'],
    };
}

export function GetHealthStatus200ResponseToJSON(json: any): GetHealthStatus200Response {
    return GetHealthStatus200ResponseToJSONTyped(json, false);
}

export function GetHealthStatus200ResponseToJSONTyped(value?: GetHealthStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'],
        'uptime': value['uptime'],
    };
}

