/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkConfig } from './NetworkConfig';
import {
    NetworkConfigFromJSON,
    NetworkConfigFromJSONTyped,
    NetworkConfigToJSON,
    NetworkConfigToJSONTyped,
} from './NetworkConfig';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * Response containing all supported staking networks
 * @export
 * @interface GetNetworksResponse
 */
export interface GetNetworksResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetNetworksResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<NetworkConfig>}
     * @memberof GetNetworksResponse
     */
    data?: Array<NetworkConfig>;
    /**
     * 
     * @type {ApiError}
     * @memberof GetNetworksResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the GetNetworksResponse interface.
 */
export function instanceOfGetNetworksResponse(value: object): value is GetNetworksResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetNetworksResponseFromJSON(json: any): GetNetworksResponse {
    return GetNetworksResponseFromJSONTyped(json, false);
}

export function GetNetworksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NetworkConfigFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function GetNetworksResponseToJSON(json: any): GetNetworksResponse {
    return GetNetworksResponseToJSONTyped(json, false);
}

export function GetNetworksResponseToJSONTyped(value?: GetNetworksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NetworkConfigToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

