/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOpenApiSpec200ResponseServersInner
 */
export interface GetOpenApiSpec200ResponseServersInner {
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseServersInner
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseServersInner
     */
    description: string;
}

/**
 * Check if a given object implements the GetOpenApiSpec200ResponseServersInner interface.
 */
export function instanceOfGetOpenApiSpec200ResponseServersInner(value: object): value is GetOpenApiSpec200ResponseServersInner {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GetOpenApiSpec200ResponseServersInnerFromJSON(json: any): GetOpenApiSpec200ResponseServersInner {
    return GetOpenApiSpec200ResponseServersInnerFromJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOpenApiSpec200ResponseServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'description': json['description'],
    };
}

export function GetOpenApiSpec200ResponseServersInnerToJSON(json: any): GetOpenApiSpec200ResponseServersInner {
    return GetOpenApiSpec200ResponseServersInnerToJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseServersInnerToJSONTyped(value?: GetOpenApiSpec200ResponseServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'description': value['description'],
    };
}

