/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOpenApiSpec200ResponseTagsInner
 */
export interface GetOpenApiSpec200ResponseTagsInner {
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseTagsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseTagsInner
     */
    description: string;
}

/**
 * Check if a given object implements the GetOpenApiSpec200ResponseTagsInner interface.
 */
export function instanceOfGetOpenApiSpec200ResponseTagsInner(value: object): value is GetOpenApiSpec200ResponseTagsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GetOpenApiSpec200ResponseTagsInnerFromJSON(json: any): GetOpenApiSpec200ResponseTagsInner {
    return GetOpenApiSpec200ResponseTagsInnerFromJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOpenApiSpec200ResponseTagsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function GetOpenApiSpec200ResponseTagsInnerToJSON(json: any): GetOpenApiSpec200ResponseTagsInner {
    return GetOpenApiSpec200ResponseTagsInnerToJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseTagsInnerToJSONTyped(value?: GetOpenApiSpec200ResponseTagsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

