/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOpenApiSpec200ResponseInfo
 */
export interface GetOpenApiSpec200ResponseInfo {
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseInfo
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200ResponseInfo
     */
    description: string;
}

/**
 * Check if a given object implements the GetOpenApiSpec200ResponseInfo interface.
 */
export function instanceOfGetOpenApiSpec200ResponseInfo(value: object): value is GetOpenApiSpec200ResponseInfo {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GetOpenApiSpec200ResponseInfoFromJSON(json: any): GetOpenApiSpec200ResponseInfo {
    return GetOpenApiSpec200ResponseInfoFromJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOpenApiSpec200ResponseInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'version': json['version'],
        'description': json['description'],
    };
}

export function GetOpenApiSpec200ResponseInfoToJSON(json: any): GetOpenApiSpec200ResponseInfo {
    return GetOpenApiSpec200ResponseInfoToJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseInfoToJSONTyped(value?: GetOpenApiSpec200ResponseInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'version': value['version'],
        'description': value['description'],
    };
}

