/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetOpenApiSpec200ResponseComponents } from './GetOpenApiSpec200ResponseComponents';
import {
    GetOpenApiSpec200ResponseComponentsFromJSON,
    GetOpenApiSpec200ResponseComponentsFromJSONTyped,
    GetOpenApiSpec200ResponseComponentsToJSON,
    GetOpenApiSpec200ResponseComponentsToJSONTyped,
} from './GetOpenApiSpec200ResponseComponents';
import type { GetOpenApiSpec200ResponseInfo } from './GetOpenApiSpec200ResponseInfo';
import {
    GetOpenApiSpec200ResponseInfoFromJSON,
    GetOpenApiSpec200ResponseInfoFromJSONTyped,
    GetOpenApiSpec200ResponseInfoToJSON,
    GetOpenApiSpec200ResponseInfoToJSONTyped,
} from './GetOpenApiSpec200ResponseInfo';
import type { GetOpenApiSpec200ResponseTagsInner } from './GetOpenApiSpec200ResponseTagsInner';
import {
    GetOpenApiSpec200ResponseTagsInnerFromJSON,
    GetOpenApiSpec200ResponseTagsInnerFromJSONTyped,
    GetOpenApiSpec200ResponseTagsInnerToJSON,
    GetOpenApiSpec200ResponseTagsInnerToJSONTyped,
} from './GetOpenApiSpec200ResponseTagsInner';
import type { GetOpenApiSpec200ResponseServersInner } from './GetOpenApiSpec200ResponseServersInner';
import {
    GetOpenApiSpec200ResponseServersInnerFromJSON,
    GetOpenApiSpec200ResponseServersInnerFromJSONTyped,
    GetOpenApiSpec200ResponseServersInnerToJSON,
    GetOpenApiSpec200ResponseServersInnerToJSONTyped,
} from './GetOpenApiSpec200ResponseServersInner';

/**
 * 
 * @export
 * @interface GetOpenApiSpec200Response
 */
export interface GetOpenApiSpec200Response {
    /**
     * 
     * @type {string}
     * @memberof GetOpenApiSpec200Response
     */
    openapi: string;
    /**
     * 
     * @type {GetOpenApiSpec200ResponseInfo}
     * @memberof GetOpenApiSpec200Response
     */
    info: GetOpenApiSpec200ResponseInfo;
    /**
     * 
     * @type {Array<GetOpenApiSpec200ResponseServersInner>}
     * @memberof GetOpenApiSpec200Response
     */
    servers: Array<GetOpenApiSpec200ResponseServersInner>;
    /**
     * 
     * @type {{ [key: string]: any | null; }}
     * @memberof GetOpenApiSpec200Response
     */
    paths: { [key: string]: any | null; };
    /**
     * 
     * @type {GetOpenApiSpec200ResponseComponents}
     * @memberof GetOpenApiSpec200Response
     */
    components?: GetOpenApiSpec200ResponseComponents;
    /**
     * 
     * @type {Array<GetOpenApiSpec200ResponseTagsInner>}
     * @memberof GetOpenApiSpec200Response
     */
    tags?: Array<GetOpenApiSpec200ResponseTagsInner>;
}

/**
 * Check if a given object implements the GetOpenApiSpec200Response interface.
 */
export function instanceOfGetOpenApiSpec200Response(value: object): value is GetOpenApiSpec200Response {
    if (!('openapi' in value) || value['openapi'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    if (!('servers' in value) || value['servers'] === undefined) return false;
    if (!('paths' in value) || value['paths'] === undefined) return false;
    return true;
}

export function GetOpenApiSpec200ResponseFromJSON(json: any): GetOpenApiSpec200Response {
    return GetOpenApiSpec200ResponseFromJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOpenApiSpec200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'openapi': json['openapi'],
        'info': GetOpenApiSpec200ResponseInfoFromJSON(json['info']),
        'servers': ((json['servers'] as Array<any>).map(GetOpenApiSpec200ResponseServersInnerFromJSON)),
        'paths': json['paths'],
        'components': json['components'] == null ? undefined : GetOpenApiSpec200ResponseComponentsFromJSON(json['components']),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(GetOpenApiSpec200ResponseTagsInnerFromJSON)),
    };
}

export function GetOpenApiSpec200ResponseToJSON(json: any): GetOpenApiSpec200Response {
    return GetOpenApiSpec200ResponseToJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseToJSONTyped(value?: GetOpenApiSpec200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openapi': value['openapi'],
        'info': GetOpenApiSpec200ResponseInfoToJSON(value['info']),
        'servers': ((value['servers'] as Array<any>).map(GetOpenApiSpec200ResponseServersInnerToJSON)),
        'paths': value['paths'],
        'components': GetOpenApiSpec200ResponseComponentsToJSON(value['components']),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(GetOpenApiSpec200ResponseTagsInnerToJSON)),
    };
}

