/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Operator } from './Operator';
import {
    OperatorFromJSON,
    OperatorFromJSONTyped,
    OperatorToJSON,
    OperatorToJSONTyped,
} from './Operator';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * List of restaking operators
 * @export
 * @interface GetOperatorsResponse
 */
export interface GetOperatorsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetOperatorsResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<Operator>}
     * @memberof GetOperatorsResponse
     */
    data?: Array<Operator>;
    /**
     * 
     * @type {ApiError}
     * @memberof GetOperatorsResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the GetOperatorsResponse interface.
 */
export function instanceOfGetOperatorsResponse(value: object): value is GetOperatorsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetOperatorsResponseFromJSON(json: any): GetOperatorsResponse {
    return GetOperatorsResponseFromJSONTyped(json, false);
}

export function GetOperatorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOperatorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(OperatorFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function GetOperatorsResponseToJSON(json: any): GetOperatorsResponse {
    return GetOperatorsResponseToJSONTyped(json, false);
}

export function GetOperatorsResponseToJSONTyped(value?: GetOperatorsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(OperatorToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

