/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOpenApiSpec200ResponseComponents
 */
export interface GetOpenApiSpec200ResponseComponents {
    /**
     * 
     * @type {{ [key: string]: any | null; }}
     * @memberof GetOpenApiSpec200ResponseComponents
     */
    schemas: { [key: string]: any | null; };
}

/**
 * Check if a given object implements the GetOpenApiSpec200ResponseComponents interface.
 */
export function instanceOfGetOpenApiSpec200ResponseComponents(value: object): value is GetOpenApiSpec200ResponseComponents {
    if (!('schemas' in value) || value['schemas'] === undefined) return false;
    return true;
}

export function GetOpenApiSpec200ResponseComponentsFromJSON(json: any): GetOpenApiSpec200ResponseComponents {
    return GetOpenApiSpec200ResponseComponentsFromJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseComponentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOpenApiSpec200ResponseComponents {
    if (json == null) {
        return json;
    }
    return {
        
        'schemas': json['schemas'],
    };
}

export function GetOpenApiSpec200ResponseComponentsToJSON(json: any): GetOpenApiSpec200ResponseComponents {
    return GetOpenApiSpec200ResponseComponentsToJSONTyped(json, false);
}

export function GetOpenApiSpec200ResponseComponentsToJSONTyped(value?: GetOpenApiSpec200ResponseComponents | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schemas': value['schemas'],
    };
}

