/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { GetRestakingStakesResponseData } from './GetRestakingStakesResponseData';
import {
    GetRestakingStakesResponseDataFromJSON,
    GetRestakingStakesResponseDataFromJSONTyped,
    GetRestakingStakesResponseDataToJSON,
    GetRestakingStakesResponseDataToJSONTyped,
} from './GetRestakingStakesResponseData';

/**
 * Restaking positions for the address
 * @export
 * @interface GetRestakingStakesResponse
 */
export interface GetRestakingStakesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetRestakingStakesResponse
     */
    success: boolean;
    /**
     * 
     * @type {GetRestakingStakesResponseData}
     * @memberof GetRestakingStakesResponse
     */
    data?: GetRestakingStakesResponseData;
    /**
     * 
     * @type {ApiError}
     * @memberof GetRestakingStakesResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the GetRestakingStakesResponse interface.
 */
export function instanceOfGetRestakingStakesResponse(value: object): value is GetRestakingStakesResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetRestakingStakesResponseFromJSON(json: any): GetRestakingStakesResponse {
    return GetRestakingStakesResponseFromJSONTyped(json, false);
}

export function GetRestakingStakesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRestakingStakesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : GetRestakingStakesResponseDataFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function GetRestakingStakesResponseToJSON(json: any): GetRestakingStakesResponse {
    return GetRestakingStakesResponseToJSONTyped(json, false);
}

export function GetRestakingStakesResponseToJSONTyped(value?: GetRestakingStakesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetRestakingStakesResponseDataToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

