/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestakingStake } from './RestakingStake';
import {
    RestakingStakeFromJSON,
    RestakingStakeFromJSONTyped,
    RestakingStakeToJSON,
    RestakingStakeToJSONTyped,
} from './RestakingStake';

/**
 * 
 * @export
 * @interface GetRestakingStakesResponseData
 */
export interface GetRestakingStakesResponseData {
    /**
     * Restaking positions for the address
     * @type {Array<RestakingStake>}
     * @memberof GetRestakingStakesResponseData
     */
    stakes: Array<RestakingStake>;
}

/**
 * Check if a given object implements the GetRestakingStakesResponseData interface.
 */
export function instanceOfGetRestakingStakesResponseData(value: object): value is GetRestakingStakesResponseData {
    if (!('stakes' in value) || value['stakes'] === undefined) return false;
    return true;
}

export function GetRestakingStakesResponseDataFromJSON(json: any): GetRestakingStakesResponseData {
    return GetRestakingStakesResponseDataFromJSONTyped(json, false);
}

export function GetRestakingStakesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRestakingStakesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'stakes': ((json['stakes'] as Array<any>).map(RestakingStakeFromJSON)),
    };
}

export function GetRestakingStakesResponseDataToJSON(json: any): GetRestakingStakesResponseData {
    return GetRestakingStakesResponseDataToJSONTyped(json, false);
}

export function GetRestakingStakesResponseDataToJSONTyped(value?: GetRestakingStakesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stakes': ((value['stakes'] as Array<any>).map(RestakingStakeToJSON)),
    };
}

