/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStakesResponseData } from './GetStakesResponseData';
import {
    GetStakesResponseDataFromJSON,
    GetStakesResponseDataFromJSONTyped,
    GetStakesResponseDataToJSON,
    GetStakesResponseDataToJSONTyped,
} from './GetStakesResponseData';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * Staking positions for the address
 * @export
 * @interface GetStakesResponse
 */
export interface GetStakesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetStakesResponse
     */
    success: boolean;
    /**
     * 
     * @type {GetStakesResponseData}
     * @memberof GetStakesResponse
     */
    data?: GetStakesResponseData;
    /**
     * 
     * @type {ApiError}
     * @memberof GetStakesResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the GetStakesResponse interface.
 */
export function instanceOfGetStakesResponse(value: object): value is GetStakesResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetStakesResponseFromJSON(json: any): GetStakesResponse {
    return GetStakesResponseFromJSONTyped(json, false);
}

export function GetStakesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStakesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : GetStakesResponseDataFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function GetStakesResponseToJSON(json: any): GetStakesResponse {
    return GetStakesResponseToJSONTyped(json, false);
}

export function GetStakesResponseToJSONTyped(value?: GetStakesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetStakesResponseDataToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

