/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stake } from './Stake';
import {
    StakeFromJSON,
    StakeFromJSONTyped,
    StakeToJSON,
    StakeToJSONTyped,
} from './Stake';

/**
 * 
 * @export
 * @interface GetStakesResponseData
 */
export interface GetStakesResponseData {
    /**
     * Staking positions for the address
     * @type {Array<Stake>}
     * @memberof GetStakesResponseData
     */
    stakes: Array<Stake>;
}

/**
 * Check if a given object implements the GetStakesResponseData interface.
 */
export function instanceOfGetStakesResponseData(value: object): value is GetStakesResponseData {
    if (!('stakes' in value) || value['stakes'] === undefined) return false;
    return true;
}

export function GetStakesResponseDataFromJSON(json: any): GetStakesResponseData {
    return GetStakesResponseDataFromJSONTyped(json, false);
}

export function GetStakesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStakesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'stakes': ((json['stakes'] as Array<any>).map(StakeFromJSON)),
    };
}

export function GetStakesResponseDataToJSON(json: any): GetStakesResponseData {
    return GetStakesResponseDataToJSONTyped(json, false);
}

export function GetStakesResponseDataToJSONTyped(value?: GetStakesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stakes': ((value['stakes'] as Array<any>).map(StakeToJSON)),
    };
}

