/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStakingPositions200Response
 */
export interface GetStakingPositions200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetStakingPositions200Response
     */
    success: boolean;
    /**
     * 
     * @type {any}
     * @memberof GetStakingPositions200Response
     */
    data?: any | null;
}

/**
 * Check if a given object implements the GetStakingPositions200Response interface.
 */
export function instanceOfGetStakingPositions200Response(value: object): value is GetStakingPositions200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetStakingPositions200ResponseFromJSON(json: any): GetStakingPositions200Response {
    return GetStakingPositions200ResponseFromJSONTyped(json, false);
}

export function GetStakingPositions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStakingPositions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GetStakingPositions200ResponseToJSON(json: any): GetStakingPositions200Response {
    return GetStakingPositions200ResponseToJSONTyped(json, false);
}

export function GetStakingPositions200ResponseToJSONTyped(value?: GetStakingPositions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
    };
}

