/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { TokenInfo } from './TokenInfo';
import {
    TokenInfoFromJSON,
    TokenInfoFromJSONTyped,
    TokenInfoToJSON,
    TokenInfoToJSONTyped,
} from './TokenInfo';

/**
 * List of supported tokens
 * @export
 * @interface GetTokensResponse
 */
export interface GetTokensResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetTokensResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<TokenInfo>}
     * @memberof GetTokensResponse
     */
    data?: Array<TokenInfo>;
    /**
     * 
     * @type {ApiError}
     * @memberof GetTokensResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the GetTokensResponse interface.
 */
export function instanceOfGetTokensResponse(value: object): value is GetTokensResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetTokensResponseFromJSON(json: any): GetTokensResponse {
    return GetTokensResponseFromJSONTyped(json, false);
}

export function GetTokensResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokensResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TokenInfoFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function GetTokensResponseToJSON(json: any): GetTokensResponse {
    return GetTokensResponseToJSONTyped(json, false);
}

export function GetTokensResponseToJSONTyped(value?: GetTokensResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TokenInfoToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

