/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { Validator } from './Validator';
import {
    ValidatorFromJSON,
    ValidatorFromJSONTyped,
    ValidatorToJSON,
    ValidatorToJSONTyped,
} from './Validator';

/**
 * List of validators
 * @export
 * @interface GetValidatorsResponse
 */
export interface GetValidatorsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetValidatorsResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<Validator>}
     * @memberof GetValidatorsResponse
     */
    data?: Array<Validator>;
    /**
     * 
     * @type {ApiError}
     * @memberof GetValidatorsResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the GetValidatorsResponse interface.
 */
export function instanceOfGetValidatorsResponse(value: object): value is GetValidatorsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetValidatorsResponseFromJSON(json: any): GetValidatorsResponse {
    return GetValidatorsResponseFromJSONTyped(json, false);
}

export function GetValidatorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetValidatorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ValidatorFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function GetValidatorsResponseToJSON(json: any): GetValidatorsResponse {
    return GetValidatorsResponseToJSONTyped(json, false);
}

export function GetValidatorsResponseToJSONTyped(value?: GetValidatorsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ValidatorToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

