/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetValidators200Response
 */
export interface GetValidators200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetValidators200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<any | null>}
     * @memberof GetValidators200Response
     */
    data: Array<any | null>;
}

/**
 * Check if a given object implements the GetValidators200Response interface.
 */
export function instanceOfGetValidators200Response(value: object): value is GetValidators200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetValidators200ResponseFromJSON(json: any): GetValidators200Response {
    return GetValidators200ResponseFromJSONTyped(json, false);
}

export function GetValidators200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetValidators200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'],
    };
}

export function GetValidators200ResponseToJSON(json: any): GetValidators200Response {
    return GetValidators200ResponseToJSONTyped(json, false);
}

export function GetValidators200ResponseToJSONTyped(value?: GetValidators200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
    };
}

