/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * Multi-transaction operation response
 * @export
 * @interface MultiTransactionResponse
 */
export interface MultiTransactionResponse {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof MultiTransactionResponse
     */
    transactions: Array<Transaction>;
}

/**
 * Check if a given object implements the MultiTransactionResponse interface.
 */
export function instanceOfMultiTransactionResponse(value: object): value is MultiTransactionResponse {
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function MultiTransactionResponseFromJSON(json: any): MultiTransactionResponse {
    return MultiTransactionResponseFromJSONTyped(json, false);
}

export function MultiTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiTransactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function MultiTransactionResponseToJSON(json: any): MultiTransactionResponse {
    return MultiTransactionResponseToJSONTyped(json, false);
}

export function MultiTransactionResponseToJSONTyped(value?: MultiTransactionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactions': ((value['transactions'] as Array<any>).map(TransactionToJSON)),
    };
}

