/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Network ID (for Cardano)
 * @export
 * @interface NetworkConfigNetworkId
 */
export interface NetworkConfigNetworkId {
}

/**
 * Check if a given object implements the NetworkConfigNetworkId interface.
 */
export function instanceOfNetworkConfigNetworkId(value: object): value is NetworkConfigNetworkId {
    return true;
}

export function NetworkConfigNetworkIdFromJSON(json: any): NetworkConfigNetworkId {
    return NetworkConfigNetworkIdFromJSONTyped(json, false);
}

export function NetworkConfigNetworkIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkConfigNetworkId {
    return json;
}

export function NetworkConfigNetworkIdToJSON(json: any): NetworkConfigNetworkId {
    return NetworkConfigNetworkIdToJSONTyped(json, false);
}

export function NetworkConfigNetworkIdToJSONTyped(value?: NetworkConfigNetworkId | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

