/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Filter by network name
 * @export
 */
export const Network = {
    Ethereum: 'ethereum',
    Near: 'near',
    Somnia: 'somnia',
    Aptos: 'aptos',
    Allora: 'allora',
    Chromia: 'chromia',
    BinanceSmartChain: 'binance-smart-chain',
    Mantra: 'mantra',
    Nillion: 'nillion',
    Zenrock: 'zenrock',
    Zetachain: 'zetachain',
    Cronos: 'cronos',
    Autonity: 'autonity',
    Berachain: 'berachain',
    Kaia: 'kaia',
    Radix: 'radix',
    Supra: 'supra',
    Vanar: 'vanar',
    Wemix: 'wemix',
    Solana: 'solana',
    Sonic: 'sonic',
    Cardano: 'cardano',
    Tezos: 'tezos',
    Tron: 'tron',
    Monad: 'monad',
    Sui: 'sui',
    Hedera: 'hedera',
    EthereumSepoliaTestnet: 'ethereum-sepolia-testnet',
    EthereumHoodiTestnet: 'ethereum-hoodi-testnet',
    AlloraTestnet: 'allora-testnet',
    ChromiaTestnet: 'chromia-testnet',
    BinanceSmartChainTestnet: 'binance-smart-chain-testnet',
    AutonityPiccadillyTestnet: 'autonity-piccadilly-testnet',
    BerachainBartioTestnet: 'berachain-bartio-testnet',
    KaiaKairosTestnet: 'kaia-kairos-testnet',
    VanarVanguardTestnet: 'vanar-vanguard-testnet',
    WemixTestnet: 'wemix-testnet',
    SolanaTestnet: 'solana-testnet',
    SonicTestnet: 'sonic-testnet',
    AptosTestnet: 'aptos-testnet',
    SupraTestnet: 'supra-testnet',
    NearTestnet: 'near-testnet',
    NillionTestnet: 'nillion-testnet',
    MantraTestnet: 'mantra-testnet',
    CardanoTestnet: 'cardano-testnet',
    ZenrockTestnet: 'zenrock-testnet',
    ZetachainTestnet: 'zetachain-testnet',
    CronosTestnet: 'cronos-testnet',
    TezosGhostnetTestnet: 'tezos-ghostnet-testnet',
    TronTestnet: 'tron-testnet',
    MonadTestnet: 'monad-testnet',
    SuiTestnet: 'sui-testnet',
    HederaTestnet: 'hedera-testnet',
    SomniaTestnet: 'somnia-testnet'
} as const;
export type Network = typeof Network[keyof typeof Network];


export function instanceOfNetwork(value: any): boolean {
    for (const key in Network) {
        if (Object.prototype.hasOwnProperty.call(Network, key)) {
            if (Network[key as keyof typeof Network] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NetworkFromJSON(json: any): Network {
    return NetworkFromJSONTyped(json, false);
}

export function NetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Network {
    return json as Network;
}

export function NetworkToJSON(value?: Network | null): any {
    return value as any;
}

export function NetworkToJSONTyped(value: any, ignoreDiscriminator: boolean): Network {
    return value as Network;
}

