/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Chain ID
 * @export
 * @interface NetworkConfigChainId
 */
export interface NetworkConfigChainId {
}

/**
 * Check if a given object implements the NetworkConfigChainId interface.
 */
export function instanceOfNetworkConfigChainId(value: object): value is NetworkConfigChainId {
    return true;
}

export function NetworkConfigChainIdFromJSON(json: any): NetworkConfigChainId {
    return NetworkConfigChainIdFromJSONTyped(json, false);
}

export function NetworkConfigChainIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkConfigChainId {
    return json;
}

export function NetworkConfigChainIdToJSON(json: any): NetworkConfigChainId {
    return NetworkConfigChainIdToJSONTyped(json, false);
}

export function NetworkConfigChainIdToJSONTyped(value?: NetworkConfigChainId | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

