/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Native token configuration
 * @export
 * @interface NetworkConfigNativeToken
 */
export interface NetworkConfigNativeToken {
    /**
     * Token symbol
     * @type {string}
     * @memberof NetworkConfigNativeToken
     */
    symbol: string;
    /**
     * Whether this is the native token
     * @type {boolean}
     * @memberof NetworkConfigNativeToken
     */
    _native: boolean;
    /**
     * Token denomination
     * @type {string}
     * @memberof NetworkConfigNativeToken
     */
    denomination: string;
    /**
     * Number of decimals
     * @type {number}
     * @memberof NetworkConfigNativeToken
     */
    decimals: number;
}

/**
 * Check if a given object implements the NetworkConfigNativeToken interface.
 */
export function instanceOfNetworkConfigNativeToken(value: object): value is NetworkConfigNativeToken {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('_native' in value) || value['_native'] === undefined) return false;
    if (!('denomination' in value) || value['denomination'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    return true;
}

export function NetworkConfigNativeTokenFromJSON(json: any): NetworkConfigNativeToken {
    return NetworkConfigNativeTokenFromJSONTyped(json, false);
}

export function NetworkConfigNativeTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkConfigNativeToken {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        '_native': json['native'],
        'denomination': json['denomination'],
        'decimals': json['decimals'],
    };
}

export function NetworkConfigNativeTokenToJSON(json: any): NetworkConfigNativeToken {
    return NetworkConfigNativeTokenToJSONTyped(json, false);
}

export function NetworkConfigNativeTokenToJSONTyped(value?: NetworkConfigNativeToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'native': value['_native'],
        'denomination': value['denomination'],
        'decimals': value['decimals'],
    };
}

