/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Protocol and network the operator runs on
 * @export
 * @interface OperatorProtocol
 */
export interface OperatorProtocol {
    /**
     * Restaking protocol identifier
     * @type {string}
     * @memberof OperatorProtocol
     */
    protocol: string;
    /**
     * Network identifier
     * @type {string}
     * @memberof OperatorProtocol
     */
    network: string;
}

/**
 * Check if a given object implements the OperatorProtocol interface.
 */
export function instanceOfOperatorProtocol(value: object): value is OperatorProtocol {
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    return true;
}

export function OperatorProtocolFromJSON(json: any): OperatorProtocol {
    return OperatorProtocolFromJSONTyped(json, false);
}

export function OperatorProtocolFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorProtocol {
    if (json == null) {
        return json;
    }
    return {
        
        'protocol': json['protocol'],
        'network': json['network'],
    };
}

export function OperatorProtocolToJSON(json: any): OperatorProtocol {
    return OperatorProtocolToJSONTyped(json, false);
}

export function OperatorProtocolToJSONTyped(value?: OperatorProtocol | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protocol': value['protocol'],
        'network': value['network'],
    };
}

