/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperatorServicesInner
 */
export interface OperatorServicesInner {
    /**
     * Service identifier
     * @type {number}
     * @memberof OperatorServicesInner
     */
    serviceId: number;
    /**
     * Service contract address
     * @type {string}
     * @memberof OperatorServicesInner
     */
    serviceAddress: string;
    /**
     * Service name
     * @type {string}
     * @memberof OperatorServicesInner
     */
    name: string;
    /**
     * Service status
     * @type {string}
     * @memberof OperatorServicesInner
     */
    status: string;
    /**
     * Commission rate for this service
     * @type {string}
     * @memberof OperatorServicesInner
     */
    commissionRate: string;
}

/**
 * Check if a given object implements the OperatorServicesInner interface.
 */
export function instanceOfOperatorServicesInner(value: object): value is OperatorServicesInner {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('serviceAddress' in value) || value['serviceAddress'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('commissionRate' in value) || value['commissionRate'] === undefined) return false;
    return true;
}

export function OperatorServicesInnerFromJSON(json: any): OperatorServicesInner {
    return OperatorServicesInnerFromJSONTyped(json, false);
}

export function OperatorServicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorServicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['serviceId'],
        'serviceAddress': json['serviceAddress'],
        'name': json['name'],
        'status': json['status'],
        'commissionRate': json['commissionRate'],
    };
}

export function OperatorServicesInnerToJSON(json: any): OperatorServicesInner {
    return OperatorServicesInnerToJSONTyped(json, false);
}

export function OperatorServicesInnerToJSONTyped(value?: OperatorServicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'serviceAddress': value['serviceAddress'],
        'name': value['name'],
        'status': value['status'],
        'commissionRate': value['commissionRate'],
    };
}

