/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperatorServicesInner } from './OperatorServicesInner';
import {
    OperatorServicesInnerFromJSON,
    OperatorServicesInnerFromJSONTyped,
    OperatorServicesInnerToJSON,
    OperatorServicesInnerToJSONTyped,
} from './OperatorServicesInner';
import type { OperatorProtocol } from './OperatorProtocol';
import {
    OperatorProtocolFromJSON,
    OperatorProtocolFromJSONTyped,
    OperatorProtocolToJSON,
    OperatorProtocolToJSONTyped,
} from './OperatorProtocol';

/**
 * A restaking operator available for delegation. operatorId is a UUID and is not the same value as operatorAddress; the history and rewards endpoints take the UUID.
 * @export
 * @interface Operator
 */
export interface Operator {
    /**
     * Operator identifier (UUID)
     * @type {string}
     * @memberof Operator
     */
    operatorId: string;
    /**
     * Operator address
     * @type {string}
     * @memberof Operator
     */
    operatorAddress: string;
    /**
     * Operator display name
     * @type {string}
     * @memberof Operator
     */
    moniker: string;
    /**
     * Operator status
     * @type {string}
     * @memberof Operator
     */
    status: string;
    /**
     * 
     * @type {OperatorProtocol}
     * @memberof Operator
     */
    protocol: OperatorProtocol;
    /**
     * 
     * @type {string}
     * @memberof Operator
     */
    commissionRate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Operator
     */
    publicDelegationEnabled?: boolean;
    /**
     * Services this operator secures
     * @type {Array<OperatorServicesInner>}
     * @memberof Operator
     */
    services?: Array<OperatorServicesInner>;
}

/**
 * Check if a given object implements the Operator interface.
 */
export function instanceOfOperator(value: object): value is Operator {
    if (!('operatorId' in value) || value['operatorId'] === undefined) return false;
    if (!('operatorAddress' in value) || value['operatorAddress'] === undefined) return false;
    if (!('moniker' in value) || value['moniker'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    return true;
}

export function OperatorFromJSON(json: any): Operator {
    return OperatorFromJSONTyped(json, false);
}

export function OperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operator {
    if (json == null) {
        return json;
    }
    return {
        
        'operatorId': json['operatorId'],
        'operatorAddress': json['operatorAddress'],
        'moniker': json['moniker'],
        'status': json['status'],
        'protocol': OperatorProtocolFromJSON(json['protocol']),
        'commissionRate': json['commissionRate'] == null ? undefined : json['commissionRate'],
        'publicDelegationEnabled': json['publicDelegationEnabled'] == null ? undefined : json['publicDelegationEnabled'],
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(OperatorServicesInnerFromJSON)),
    };
}

export function OperatorToJSON(json: any): Operator {
    return OperatorToJSONTyped(json, false);
}

export function OperatorToJSONTyped(value?: Operator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operatorId': value['operatorId'],
        'operatorAddress': value['operatorAddress'],
        'moniker': value['moniker'],
        'status': value['status'],
        'protocol': OperatorProtocolToJSON(value['protocol']),
        'commissionRate': value['commissionRate'],
        'publicDelegationEnabled': value['publicDelegationEnabled'],
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(OperatorServicesInnerToJSON)),
    };
}

