/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The blockchain network to query
 * @export
 */
export const RestakingNetwork = {
    Ethereum: 'ethereum',
    EthereumHoodiTestnet: 'ethereum-hoodi-testnet'
} as const;
export type RestakingNetwork = typeof RestakingNetwork[keyof typeof RestakingNetwork];


export function instanceOfRestakingNetwork(value: any): boolean {
    for (const key in RestakingNetwork) {
        if (Object.prototype.hasOwnProperty.call(RestakingNetwork, key)) {
            if (RestakingNetwork[key as keyof typeof RestakingNetwork] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestakingNetworkFromJSON(json: any): RestakingNetwork {
    return RestakingNetworkFromJSONTyped(json, false);
}

export function RestakingNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingNetwork {
    return json as RestakingNetwork;
}

export function RestakingNetworkToJSON(value?: RestakingNetwork | null): any {
    return value as any;
}

export function RestakingNetworkToJSONTyped(value: any, ignoreDiscriminator: boolean): RestakingNetwork {
    return value as RestakingNetwork;
}

