/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestakingNetwork } from './RestakingNetwork';
import {
    RestakingNetworkFromJSON,
    RestakingNetworkFromJSONTyped,
    RestakingNetworkToJSON,
    RestakingNetworkToJSONTyped,
} from './RestakingNetwork';
import type { RestakingToken } from './RestakingToken';
import {
    RestakingTokenFromJSON,
    RestakingTokenFromJSONTyped,
    RestakingTokenToJSON,
    RestakingTokenToJSONTyped,
} from './RestakingToken';

/**
 * Information about a restaked position on EigenLayer. Status meanings: 'staked' = actively restaked, 'unstaking' = withdrawal queued and in cooldown, 'unstaked' = withdrawal ready to complete
 * @export
 * @interface RestakingStake
 */
export interface RestakingStake {
    /**
     * 
     * @type {RestakingNetwork}
     * @memberof RestakingStake
     */
    network: RestakingNetwork;
    /**
     * 
     * @type {RestakingToken}
     * @memberof RestakingStake
     */
    token: RestakingToken;
    /**
     * 
     * @type {string}
     * @memberof RestakingStake
     */
    tokenAddress?: string | null;
    /**
     * The address that owns the restaked position
     * @type {string}
     * @memberof RestakingStake
     */
    stakerAddress: string;
    /**
     * The EigenLayer operator address (if delegated)
     * @type {string}
     * @memberof RestakingStake
     */
    operatorAddress?: string;
    /**
     * Amount restaked in smallest unit of the asset
     * @type {string}
     * @memberof RestakingStake
     */
    amount: string;
    /**
     * Current status of the restaked position
     * @type {string}
     * @memberof RestakingStake
     */
    status: RestakingStakeStatusEnum;
    /**
     * ISO 8601 date when unstaking will complete (if unstaking/deactivating)
     * @type {string}
     * @memberof RestakingStake
     */
    unstakingCompletionDate?: string | null;
}


/**
 * @export
 */
export const RestakingStakeStatusEnum = {
    Staked: 'staked',
    Unstaking: 'unstaking',
    Unstaked: 'unstaked'
} as const;
export type RestakingStakeStatusEnum = typeof RestakingStakeStatusEnum[keyof typeof RestakingStakeStatusEnum];


/**
 * Check if a given object implements the RestakingStake interface.
 */
export function instanceOfRestakingStake(value: object): value is RestakingStake {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('stakerAddress' in value) || value['stakerAddress'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RestakingStakeFromJSON(json: any): RestakingStake {
    return RestakingStakeFromJSONTyped(json, false);
}

export function RestakingStakeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingStake {
    if (json == null) {
        return json;
    }
    return {
        
        'network': RestakingNetworkFromJSON(json['network']),
        'token': RestakingTokenFromJSON(json['token']),
        'tokenAddress': json['tokenAddress'] == null ? undefined : json['tokenAddress'],
        'stakerAddress': json['stakerAddress'],
        'operatorAddress': json['operatorAddress'] == null ? undefined : json['operatorAddress'],
        'amount': json['amount'],
        'status': json['status'],
        'unstakingCompletionDate': json['unstakingCompletionDate'] == null ? undefined : json['unstakingCompletionDate'],
    };
}

export function RestakingStakeToJSON(json: any): RestakingStake {
    return RestakingStakeToJSONTyped(json, false);
}

export function RestakingStakeToJSONTyped(value?: RestakingStake | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': RestakingNetworkToJSON(value['network']),
        'token': RestakingTokenToJSON(value['token']),
        'tokenAddress': value['tokenAddress'],
        'stakerAddress': value['stakerAddress'],
        'operatorAddress': value['operatorAddress'],
        'amount': value['amount'],
        'status': value['status'],
        'unstakingCompletionDate': value['unstakingCompletionDate'],
    };
}

