/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestakingNetwork } from './RestakingNetwork';
import {
    RestakingNetworkFromJSON,
    RestakingNetworkFromJSONTyped,
    RestakingNetworkToJSON,
    RestakingNetworkToJSONTyped,
} from './RestakingNetwork';
import type { RestakingToken } from './RestakingToken';
import {
    RestakingTokenFromJSON,
    RestakingTokenFromJSONTyped,
    RestakingTokenToJSON,
    RestakingTokenToJSONTyped,
} from './RestakingToken';

/**
 * Request body for restaking unstake endpoint. Queues a partial withdrawal while remaining delegated to operator.
 * @export
 * @interface RestakingUnstakeRequest
 */
export interface RestakingUnstakeRequest {
    /**
     * 
     * @type {RestakingNetwork}
     * @memberof RestakingUnstakeRequest
     */
    network: RestakingNetwork;
    /**
     * 
     * @type {RestakingToken}
     * @memberof RestakingUnstakeRequest
     */
    token: RestakingToken;
    /**
     * Amount to unstake in the token's base denomination
     * @type {string}
     * @memberof RestakingUnstakeRequest
     */
    amount: string;
    /**
     * Ethereum address of the staker
     * @type {string}
     * @memberof RestakingUnstakeRequest
     */
    staker: string;
}

/**
 * Check if a given object implements the RestakingUnstakeRequest interface.
 */
export function instanceOfRestakingUnstakeRequest(value: object): value is RestakingUnstakeRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    return true;
}

export function RestakingUnstakeRequestFromJSON(json: any): RestakingUnstakeRequest {
    return RestakingUnstakeRequestFromJSONTyped(json, false);
}

export function RestakingUnstakeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingUnstakeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': RestakingNetworkFromJSON(json['network']),
        'token': RestakingTokenFromJSON(json['token']),
        'amount': json['amount'],
        'staker': json['staker'],
    };
}

export function RestakingUnstakeRequestToJSON(json: any): RestakingUnstakeRequest {
    return RestakingUnstakeRequestToJSONTyped(json, false);
}

export function RestakingUnstakeRequestToJSONTyped(value?: RestakingUnstakeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': RestakingNetworkToJSON(value['network']),
        'token': RestakingTokenToJSON(value['token']),
        'amount': value['amount'],
        'staker': value['staker'],
    };
}

