/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The token to filter restaking stakes for
 * @export
 */
export const RestakingToken = {
    Eigen: 'EIGEN',
    Beigen: 'BEIGEN',
    Steth: 'STETH',
    Cbeth: 'CBETH',
    Reth: 'RETH'
} as const;
export type RestakingToken = typeof RestakingToken[keyof typeof RestakingToken];


export function instanceOfRestakingToken(value: any): boolean {
    for (const key in RestakingToken) {
        if (Object.prototype.hasOwnProperty.call(RestakingToken, key)) {
            if (RestakingToken[key as keyof typeof RestakingToken] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestakingTokenFromJSON(json: any): RestakingToken {
    return RestakingTokenFromJSONTyped(json, false);
}

export function RestakingTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingToken {
    return json as RestakingToken;
}

export function RestakingTokenToJSON(value?: RestakingToken | null): any {
    return value as any;
}

export function RestakingTokenToJSONTyped(value: any, ignoreDiscriminator: boolean): RestakingToken {
    return value as RestakingToken;
}

