/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestakingNetwork } from './RestakingNetwork';
import {
    RestakingNetworkFromJSON,
    RestakingNetworkFromJSONTyped,
    RestakingNetworkToJSON,
    RestakingNetworkToJSONTyped,
} from './RestakingNetwork';

/**
 * Request body for restaking delegate endpoint
 * @export
 * @interface RestakingDelegateRequest
 */
export interface RestakingDelegateRequest {
    /**
     * 
     * @type {RestakingNetwork}
     * @memberof RestakingDelegateRequest
     */
    network: RestakingNetwork;
    /**
     * Ethereum address of the staker
     * @type {string}
     * @memberof RestakingDelegateRequest
     */
    staker: string;
    /**
     * EigenLayer operator address to delegate to.
     * @type {string}
     * @memberof RestakingDelegateRequest
     */
    operator: string;
}

/**
 * Check if a given object implements the RestakingDelegateRequest interface.
 */
export function instanceOfRestakingDelegateRequest(value: object): value is RestakingDelegateRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    return true;
}

export function RestakingDelegateRequestFromJSON(json: any): RestakingDelegateRequest {
    return RestakingDelegateRequestFromJSONTyped(json, false);
}

export function RestakingDelegateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingDelegateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': RestakingNetworkFromJSON(json['network']),
        'staker': json['staker'],
        'operator': json['operator'],
    };
}

export function RestakingDelegateRequestToJSON(json: any): RestakingDelegateRequest {
    return RestakingDelegateRequestToJSONTyped(json, false);
}

export function RestakingDelegateRequestToJSONTyped(value?: RestakingDelegateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': RestakingNetworkToJSON(value['network']),
        'staker': value['staker'],
        'operator': value['operator'],
    };
}

