/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestakingNetwork } from './RestakingNetwork';
import {
    RestakingNetworkFromJSON,
    RestakingNetworkFromJSONTyped,
    RestakingNetworkToJSON,
    RestakingNetworkToJSONTyped,
} from './RestakingNetwork';
import type { RestakingToken } from './RestakingToken';
import {
    RestakingTokenFromJSON,
    RestakingTokenFromJSONTyped,
    RestakingTokenToJSON,
    RestakingTokenToJSONTyped,
} from './RestakingToken';

/**
 * Request body for restaking withdrawal endpoint. Must call /undelegate or /unstake first to queue withdrawals.
 * @export
 * @interface RestakingWithdrawRequest
 */
export interface RestakingWithdrawRequest {
    /**
     * 
     * @type {RestakingNetwork}
     * @memberof RestakingWithdrawRequest
     */
    network: RestakingNetwork;
    /**
     * 
     * @type {RestakingToken}
     * @memberof RestakingWithdrawRequest
     */
    token: RestakingToken;
    /**
     * Ethereum address of the staker
     * @type {string}
     * @memberof RestakingWithdrawRequest
     */
    staker: string;
}

/**
 * Check if a given object implements the RestakingWithdrawRequest interface.
 */
export function instanceOfRestakingWithdrawRequest(value: object): value is RestakingWithdrawRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    return true;
}

export function RestakingWithdrawRequestFromJSON(json: any): RestakingWithdrawRequest {
    return RestakingWithdrawRequestFromJSONTyped(json, false);
}

export function RestakingWithdrawRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingWithdrawRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': RestakingNetworkFromJSON(json['network']),
        'token': RestakingTokenFromJSON(json['token']),
        'staker': json['staker'],
    };
}

export function RestakingWithdrawRequestToJSON(json: any): RestakingWithdrawRequest {
    return RestakingWithdrawRequestToJSONTyped(json, false);
}

export function RestakingWithdrawRequestToJSONTyped(value?: RestakingWithdrawRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': RestakingNetworkToJSON(value['network']),
        'token': RestakingTokenToJSON(value['token']),
        'staker': value['staker'],
    };
}

