/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestakingNetwork } from './RestakingNetwork';
import {
    RestakingNetworkFromJSON,
    RestakingNetworkFromJSONTyped,
    RestakingNetworkToJSON,
    RestakingNetworkToJSONTyped,
} from './RestakingNetwork';

/**
 * Request body for restaking undelegate endpoint. Note: This undelegates ALL staked assets and queues them for withdrawal.
 * @export
 * @interface RestakingUndelegateRequest
 */
export interface RestakingUndelegateRequest {
    /**
     * 
     * @type {RestakingNetwork}
     * @memberof RestakingUndelegateRequest
     */
    network: RestakingNetwork;
    /**
     * Ethereum address of the staker
     * @type {string}
     * @memberof RestakingUndelegateRequest
     */
    staker: string;
}

/**
 * Check if a given object implements the RestakingUndelegateRequest interface.
 */
export function instanceOfRestakingUndelegateRequest(value: object): value is RestakingUndelegateRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    return true;
}

export function RestakingUndelegateRequestFromJSON(json: any): RestakingUndelegateRequest {
    return RestakingUndelegateRequestFromJSONTyped(json, false);
}

export function RestakingUndelegateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestakingUndelegateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': RestakingNetworkFromJSON(json['network']),
        'staker': json['staker'],
    };
}

export function RestakingUndelegateRequestToJSON(json: any): RestakingUndelegateRequest {
    return RestakingUndelegateRequestToJSONTyped(json, false);
}

export function RestakingUndelegateRequestToJSONTyped(value?: RestakingUndelegateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': RestakingNetworkToJSON(value['network']),
        'staker': value['staker'],
    };
}

