/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RewardHistoryItem } from './RewardHistoryItem';
import {
    RewardHistoryItemFromJSON,
    RewardHistoryItemFromJSONTyped,
    RewardHistoryItemToJSON,
    RewardHistoryItemToJSONTyped,
} from './RewardHistoryItem';

/**
 * 
 * @export
 * @interface RewardHistoryResponse
 */
export interface RewardHistoryResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RewardHistoryResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<RewardHistoryItem>}
     * @memberof RewardHistoryResponse
     */
    data: Array<RewardHistoryItem>;
}

/**
 * Check if a given object implements the RewardHistoryResponse interface.
 */
export function instanceOfRewardHistoryResponse(value: object): value is RewardHistoryResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RewardHistoryResponseFromJSON(json: any): RewardHistoryResponse {
    return RewardHistoryResponseFromJSONTyped(json, false);
}

export function RewardHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RewardHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(RewardHistoryItemFromJSON)),
    };
}

export function RewardHistoryResponseToJSON(json: any): RewardHistoryResponse {
    return RewardHistoryResponseToJSONTyped(json, false);
}

export function RewardHistoryResponseToJSONTyped(value?: RewardHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(RewardHistoryItemToJSON)),
    };
}

