/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingNetwork } from './StakingNetwork';
import {
    StakingNetworkFromJSON,
    StakingNetworkFromJSONTyped,
    StakingNetworkToJSON,
    StakingNetworkToJSONTyped,
} from './StakingNetwork';
import type { StakingToken } from './StakingToken';
import {
    StakingTokenFromJSON,
    StakingTokenFromJSONTyped,
    StakingTokenToJSON,
    StakingTokenToJSONTyped,
} from './StakingToken';

/**
 * 
 * @export
 * @interface SimplifiedStakeRequest
 */
export interface SimplifiedStakeRequest {
    /**
     * 
     * @type {StakingNetwork}
     * @memberof SimplifiedStakeRequest
     */
    network: StakingNetwork;
    /**
     * 
     * @type {StakingToken}
     * @memberof SimplifiedStakeRequest
     */
    token: StakingToken;
    /**
     * Amount to stake in the token's base denomination. Required for all networks except Cardano.
     * @type {string}
     * @memberof SimplifiedStakeRequest
     */
    amount?: string;
    /**
     * Staker address or public key.
     * 
     * | Network Type | Format | Example |
     * |--------------|--------|---------|
     * | **Cosmos networks (Mantra/Nillion/...)** | Bech32 address | mantra1234567890abcdefghijklmnopqrstuvwxyz123456 |
     * | **Solana** | Base58 encoded public key | updtkJ8HAhh3rSkBCd3p9Z1Q74yJW4rMhSbScRskDPM |
     * | **Cardano** | Bech32 address | addr1qx2kd4xkl38xkj2vh45jhk2l1kj3h4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9z0a1b2c3d4e5f6g7h8i9j0k1l2m3n4 |
     * | **EVM Networks (Polygon/Kaia/Somnia/...)** | 0x-prefixed hex address | 0x1234567890abcdef1234567890abcdef12345678 |
     * 
     * @type {string}
     * @memberof SimplifiedStakeRequest
     */
    staker: string;
    /**
     * Validator address/pubkey/identifier. **REQUIRED** for: Cosmos networks, Solana, Cardano, Polygon, Kaia, Somnia.
     * 
     * | Network Type | Format | Example |
     * |--------------|--------|---------|
     * | **Cosmos networks (Mantra/Nillion/...)** | Bech32 validator operator address | mantravaloper1234567890abcdefghijklmnopqrstuvwxyz123456 |
     * | **Solana** | Base58 encoded vote account address | he1iusunGwqrNtafDtLdhsUQDFvo13z9sUa36PauBtk |
     * | **Cardano** | Pool ID bech32 address | pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5... |
     * | **Polygon** | 0x-prefixed validator contract address | 0x26D1Ec50b4e62C1D1a40d16e7caD677311A5F2C5 |
     * | **Kaia** | 0x-prefixed validator address | 0xabcdef1234567890abcdef1234567890abcdef12 |
     * | **Somnia** | 0x-prefixed validator address | 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb8
     * @type {string}
     * @memberof SimplifiedStakeRequest
     */
    validator?: string;
    /**
     * Additional network-specific parameters. Refer to specific examples for additional information.
     * 
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SimplifiedStakeRequest
     */
    params?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SimplifiedStakeRequest interface.
 */
export function instanceOfSimplifiedStakeRequest(value: object): value is SimplifiedStakeRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    return true;
}

export function SimplifiedStakeRequestFromJSON(json: any): SimplifiedStakeRequest {
    return SimplifiedStakeRequestFromJSONTyped(json, false);
}

export function SimplifiedStakeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplifiedStakeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': StakingNetworkFromJSON(json['network']),
        'token': StakingTokenFromJSON(json['token']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'staker': json['staker'],
        'validator': json['validator'] == null ? undefined : json['validator'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function SimplifiedStakeRequestToJSON(json: any): SimplifiedStakeRequest {
    return SimplifiedStakeRequestToJSONTyped(json, false);
}

export function SimplifiedStakeRequestToJSONTyped(value?: SimplifiedStakeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': StakingNetworkToJSON(value['network']),
        'token': StakingTokenToJSON(value['token']),
        'amount': value['amount'],
        'staker': value['staker'],
        'validator': value['validator'],
        'params': value['params'],
    };
}

