/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkConfigNetworkId } from './NetworkConfigNetworkId';
import {
    NetworkConfigNetworkIdFromJSON,
    NetworkConfigNetworkIdFromJSONTyped,
    NetworkConfigNetworkIdToJSON,
    NetworkConfigNetworkIdToJSONTyped,
} from './NetworkConfigNetworkId';
import type { NetworkConfigNativeToken } from './NetworkConfigNativeToken';
import {
    NetworkConfigNativeTokenFromJSON,
    NetworkConfigNativeTokenFromJSONTyped,
    NetworkConfigNativeTokenToJSON,
    NetworkConfigNativeTokenToJSONTyped,
} from './NetworkConfigNativeToken';
import type { NetworkConfigChainId } from './NetworkConfigChainId';
import {
    NetworkConfigChainIdFromJSON,
    NetworkConfigChainIdFromJSONTyped,
    NetworkConfigChainIdToJSON,
    NetworkConfigChainIdToJSONTyped,
} from './NetworkConfigChainId';

/**
 * 
 * @export
 * @interface StakingOptionInfoNetwork
 */
export interface StakingOptionInfoNetwork {
    /**
     * Network identifier
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    network: string;
    /**
     * Network type (evm, cosmos, etc.)
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    type?: string;
    /**
     * 
     * @type {NetworkConfigNativeToken}
     * @memberof StakingOptionInfoNetwork
     */
    nativeToken: NetworkConfigNativeToken;
    /**
     * Bech32 prefix for cosmos chains
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    bech32Prefix?: string;
    /**
     * Whether this is a testnet
     * @type {boolean}
     * @memberof StakingOptionInfoNetwork
     */
    testnet?: boolean;
    /**
     * RPC endpoint URL
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    rpc?: string;
    /**
     * API endpoint URL
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    api?: string;
    /**
     * 
     * @type {NetworkConfigChainId}
     * @memberof StakingOptionInfoNetwork
     */
    chainId?: NetworkConfigChainId;
    /**
     * Block explorer URL
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    explorer?: string;
    /**
     * Gateway URL (for Radix)
     * @type {string}
     * @memberof StakingOptionInfoNetwork
     */
    gateway?: string;
    /**
     * 
     * @type {NetworkConfigNetworkId}
     * @memberof StakingOptionInfoNetwork
     */
    networkId?: NetworkConfigNetworkId;
}

/**
 * Check if a given object implements the StakingOptionInfoNetwork interface.
 */
export function instanceOfStakingOptionInfoNetwork(value: object): value is StakingOptionInfoNetwork {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('nativeToken' in value) || value['nativeToken'] === undefined) return false;
    return true;
}

export function StakingOptionInfoNetworkFromJSON(json: any): StakingOptionInfoNetwork {
    return StakingOptionInfoNetworkFromJSONTyped(json, false);
}

export function StakingOptionInfoNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOptionInfoNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'network': json['network'],
        'type': json['type'] == null ? undefined : json['type'],
        'nativeToken': NetworkConfigNativeTokenFromJSON(json['nativeToken']),
        'bech32Prefix': json['bech32Prefix'] == null ? undefined : json['bech32Prefix'],
        'testnet': json['testnet'] == null ? undefined : json['testnet'],
        'rpc': json['rpc'] == null ? undefined : json['rpc'],
        'api': json['api'] == null ? undefined : json['api'],
        'chainId': json['chainId'] == null ? undefined : NetworkConfigChainIdFromJSON(json['chainId']),
        'explorer': json['explorer'] == null ? undefined : json['explorer'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        'networkId': json['networkId'] == null ? undefined : NetworkConfigNetworkIdFromJSON(json['networkId']),
    };
}

export function StakingOptionInfoNetworkToJSON(json: any): StakingOptionInfoNetwork {
    return StakingOptionInfoNetworkToJSONTyped(json, false);
}

export function StakingOptionInfoNetworkToJSONTyped(value?: StakingOptionInfoNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': value['network'],
        'type': value['type'],
        'nativeToken': NetworkConfigNativeTokenToJSON(value['nativeToken']),
        'bech32Prefix': value['bech32Prefix'],
        'testnet': value['testnet'],
        'rpc': value['rpc'],
        'api': value['api'],
        'chainId': NetworkConfigChainIdToJSON(value['chainId']),
        'explorer': value['explorer'],
        'gateway': value['gateway'],
        'networkId': NetworkConfigNetworkIdToJSON(value['networkId']),
    };
}

