/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingOptionInfoExtraParamsInner } from './StakingOptionInfoExtraParamsInner';
import {
    StakingOptionInfoExtraParamsInnerFromJSON,
    StakingOptionInfoExtraParamsInnerFromJSONTyped,
    StakingOptionInfoExtraParamsInnerToJSON,
    StakingOptionInfoExtraParamsInnerToJSONTyped,
} from './StakingOptionInfoExtraParamsInner';
import type { TokenInfo } from './TokenInfo';
import {
    TokenInfoFromJSON,
    TokenInfoFromJSONTyped,
    TokenInfoToJSON,
    TokenInfoToJSONTyped,
} from './TokenInfo';
import type { StakingOptionInfoNetwork } from './StakingOptionInfoNetwork';
import {
    StakingOptionInfoNetworkFromJSON,
    StakingOptionInfoNetworkFromJSONTyped,
    StakingOptionInfoNetworkToJSON,
    StakingOptionInfoNetworkToJSONTyped,
} from './StakingOptionInfoNetwork';

/**
 * 
 * @export
 * @interface StakingOptionInfo
 */
export interface StakingOptionInfo {
    /**
     * 
     * @type {StakingOptionInfoNetwork}
     * @memberof StakingOptionInfo
     */
    network: StakingOptionInfoNetwork;
    /**
     * 
     * @type {TokenInfo}
     * @memberof StakingOptionInfo
     */
    token: TokenInfo;
    /**
     * Extra parameters required
     * @type {Array<StakingOptionInfoExtraParamsInner>}
     * @memberof StakingOptionInfo
     */
    extraParams: Array<StakingOptionInfoExtraParamsInner>;
}

/**
 * Check if a given object implements the StakingOptionInfo interface.
 */
export function instanceOfStakingOptionInfo(value: object): value is StakingOptionInfo {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('extraParams' in value) || value['extraParams'] === undefined) return false;
    return true;
}

export function StakingOptionInfoFromJSON(json: any): StakingOptionInfo {
    return StakingOptionInfoFromJSONTyped(json, false);
}

export function StakingOptionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOptionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'network': StakingOptionInfoNetworkFromJSON(json['network']),
        'token': TokenInfoFromJSON(json['token']),
        'extraParams': ((json['extraParams'] as Array<any>).map(StakingOptionInfoExtraParamsInnerFromJSON)),
    };
}

export function StakingOptionInfoToJSON(json: any): StakingOptionInfo {
    return StakingOptionInfoToJSONTyped(json, false);
}

export function StakingOptionInfoToJSONTyped(value?: StakingOptionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': StakingOptionInfoNetworkToJSON(value['network']),
        'token': TokenInfoToJSON(value['token']),
        'extraParams': ((value['extraParams'] as Array<any>).map(StakingOptionInfoExtraParamsInnerToJSON)),
    };
}

