/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingNetwork } from './StakingNetwork';
import {
    StakingNetworkFromJSON,
    StakingNetworkFromJSONTyped,
    StakingNetworkToJSON,
    StakingNetworkToJSONTyped,
} from './StakingNetwork';
import type { StakingToken } from './StakingToken';
import {
    StakingTokenFromJSON,
    StakingTokenFromJSONTyped,
    StakingTokenToJSON,
    StakingTokenToJSONTyped,
} from './StakingToken';

/**
 * Information about a stake or delegation on a blockchain network. Status meanings: 'staked' = actively staking/earning rewards, 'unstaking' = unbonding period in progress, 'unstaked' = unstaking complete and ready to withdraw
 * @export
 * @interface Stake
 */
export interface Stake {
    /**
     * 
     * @type {StakingNetwork}
     * @memberof Stake
     */
    network: StakingNetwork;
    /**
     * 
     * @type {StakingToken}
     * @memberof Stake
     */
    token: StakingToken;
    /**
     * 
     * @type {string}
     * @memberof Stake
     */
    tokenAddress?: string | null;
    /**
     * The address that owns the stake
     * @type {string}
     * @memberof Stake
     */
    stakerAddress: string;
    /**
     * The validator address (if applicable)
     * @type {string}
     * @memberof Stake
     */
    validatorAddress?: string;
    /**
     * Amount staked in smallest unit of the asset
     * @type {string}
     * @memberof Stake
     */
    amount: string;
    /**
     * Current status of the stake
     * @type {string}
     * @memberof Stake
     */
    status: StakeStatusEnum;
    /**
     * ISO 8601 date when unstaking will complete (if unstaking/deactivating)
     * @type {string}
     * @memberof Stake
     */
    unstakingCompletionDate?: string | null;
    /**
     * Accumulated rewards (if available)
     * @type {string}
     * @memberof Stake
     */
    rewards?: string;
}


/**
 * @export
 */
export const StakeStatusEnum = {
    Staked: 'staked',
    Unstaking: 'unstaking',
    Unstaked: 'unstaked'
} as const;
export type StakeStatusEnum = typeof StakeStatusEnum[keyof typeof StakeStatusEnum];


/**
 * Check if a given object implements the Stake interface.
 */
export function instanceOfStake(value: object): value is Stake {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('stakerAddress' in value) || value['stakerAddress'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function StakeFromJSON(json: any): Stake {
    return StakeFromJSONTyped(json, false);
}

export function StakeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stake {
    if (json == null) {
        return json;
    }
    return {
        
        'network': StakingNetworkFromJSON(json['network']),
        'token': StakingTokenFromJSON(json['token']),
        'tokenAddress': json['tokenAddress'] == null ? undefined : json['tokenAddress'],
        'stakerAddress': json['stakerAddress'],
        'validatorAddress': json['validatorAddress'] == null ? undefined : json['validatorAddress'],
        'amount': json['amount'],
        'status': json['status'],
        'unstakingCompletionDate': json['unstakingCompletionDate'] == null ? undefined : json['unstakingCompletionDate'],
        'rewards': json['rewards'] == null ? undefined : json['rewards'],
    };
}

export function StakeToJSON(json: any): Stake {
    return StakeToJSONTyped(json, false);
}

export function StakeToJSONTyped(value?: Stake | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': StakingNetworkToJSON(value['network']),
        'token': StakingTokenToJSON(value['token']),
        'tokenAddress': value['tokenAddress'],
        'stakerAddress': value['stakerAddress'],
        'validatorAddress': value['validatorAddress'],
        'amount': value['amount'],
        'status': value['status'],
        'unstakingCompletionDate': value['unstakingCompletionDate'],
        'rewards': value['rewards'],
    };
}

