/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The token to query stakes for
 * @export
 */
export const StakingToken = {
    Pol: 'POL',
    Sol: 'SOL',
    Somi: 'SOMI',
    Mon: 'MON',
    Mantra: 'MANTRA',
    Nill: 'NILL',
    Kaia: 'KAIA',
    Ada: 'ADA',
    S: 'S',
    Near: 'NEAR',
    Apt: 'APT',
    Rock: 'ROCK',
    Hbar: 'HBAR'
} as const;
export type StakingToken = typeof StakingToken[keyof typeof StakingToken];


export function instanceOfStakingToken(value: any): boolean {
    for (const key in StakingToken) {
        if (Object.prototype.hasOwnProperty.call(StakingToken, key)) {
            if (StakingToken[key as keyof typeof StakingToken] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StakingTokenFromJSON(json: any): StakingToken {
    return StakingTokenFromJSONTyped(json, false);
}

export function StakingTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingToken {
    return json as StakingToken;
}

export function StakingTokenToJSON(value?: StakingToken | null): any {
    return value as any;
}

export function StakingTokenToJSONTyped(value: any, ignoreDiscriminator: boolean): StakingToken {
    return value as StakingToken;
}

