/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StakingOptionInfoExtraParamsInner
 */
export interface StakingOptionInfoExtraParamsInner {
    /**
     * Parameter name
     * @type {string}
     * @memberof StakingOptionInfoExtraParamsInner
     */
    name: string;
    /**
     * Parameter type
     * @type {string}
     * @memberof StakingOptionInfoExtraParamsInner
     */
    type: string;
    /**
     * Whether parameter is required
     * @type {boolean}
     * @memberof StakingOptionInfoExtraParamsInner
     */
    required: boolean;
    /**
     * Parameter description
     * @type {string}
     * @memberof StakingOptionInfoExtraParamsInner
     */
    description?: string;
}

/**
 * Check if a given object implements the StakingOptionInfoExtraParamsInner interface.
 */
export function instanceOfStakingOptionInfoExtraParamsInner(value: object): value is StakingOptionInfoExtraParamsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    return true;
}

export function StakingOptionInfoExtraParamsInnerFromJSON(json: any): StakingOptionInfoExtraParamsInner {
    return StakingOptionInfoExtraParamsInnerFromJSONTyped(json, false);
}

export function StakingOptionInfoExtraParamsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOptionInfoExtraParamsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'required': json['required'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function StakingOptionInfoExtraParamsInnerToJSON(json: any): StakingOptionInfoExtraParamsInner {
    return StakingOptionInfoExtraParamsInnerToJSONTyped(json, false);
}

export function StakingOptionInfoExtraParamsInnerToJSONTyped(value?: StakingOptionInfoExtraParamsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'required': value['required'],
        'description': value['description'],
    };
}

