/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingOption } from './StakingOption';
import {
    StakingOptionFromJSON,
    StakingOptionFromJSONTyped,
    StakingOptionToJSON,
    StakingOptionToJSONTyped,
} from './StakingOption';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * List of staking options
 * @export
 * @interface StakingOptionsResponse
 */
export interface StakingOptionsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StakingOptionsResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<StakingOption>}
     * @memberof StakingOptionsResponse
     */
    data?: Array<StakingOption>;
    /**
     * 
     * @type {ApiError}
     * @memberof StakingOptionsResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the StakingOptionsResponse interface.
 */
export function instanceOfStakingOptionsResponse(value: object): value is StakingOptionsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function StakingOptionsResponseFromJSON(json: any): StakingOptionsResponse {
    return StakingOptionsResponseFromJSONTyped(json, false);
}

export function StakingOptionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOptionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StakingOptionFromJSON)),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function StakingOptionsResponseToJSON(json: any): StakingOptionsResponse {
    return StakingOptionsResponseToJSONTyped(json, false);
}

export function StakingOptionsResponseToJSONTyped(value?: StakingOptionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StakingOptionToJSON)),
        'error': ApiErrorToJSON(value['error']),
    };
}

