/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingOptionInfo } from './StakingOptionInfo';
import {
    StakingOptionInfoFromJSON,
    StakingOptionInfoFromJSONTyped,
    StakingOptionInfoToJSON,
    StakingOptionInfoToJSONTyped,
} from './StakingOptionInfo';

/**
 * Staking option configuration
 * @export
 * @interface StakingOption
 */
export interface StakingOption {
    /**
     * Network identifier
     * @type {string}
     * @memberof StakingOption
     */
    network: string;
    /**
     * Token symbol
     * @type {string}
     * @memberof StakingOption
     */
    token: string;
    /**
     * Staking status
     * @type {string}
     * @memberof StakingOption
     */
    status: StakingOptionStatusEnum;
    /**
     * 
     * @type {StakingOptionInfo}
     * @memberof StakingOption
     */
    info: StakingOptionInfo;
}


/**
 * @export
 */
export const StakingOptionStatusEnum = {
    Live: 'LIVE',
    Planned: 'PLANNED'
} as const;
export type StakingOptionStatusEnum = typeof StakingOptionStatusEnum[keyof typeof StakingOptionStatusEnum];


/**
 * Check if a given object implements the StakingOption interface.
 */
export function instanceOfStakingOption(value: object): value is StakingOption {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function StakingOptionFromJSON(json: any): StakingOption {
    return StakingOptionFromJSONTyped(json, false);
}

export function StakingOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOption {
    if (json == null) {
        return json;
    }
    return {
        
        'network': json['network'],
        'token': json['token'],
        'status': json['status'],
        'info': StakingOptionInfoFromJSON(json['info']),
    };
}

export function StakingOptionToJSON(json: any): StakingOption {
    return StakingOptionToJSONTyped(json, false);
}

export function StakingOptionToJSONTyped(value?: StakingOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': value['network'],
        'token': value['token'],
        'status': value['status'],
        'info': StakingOptionInfoToJSON(value['info']),
    };
}

