/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The blockchain network
 * @export
 */
export const StakingNetwork = {
    Ethereum: 'ethereum',
    Solana: 'solana',
    Somnia: 'somnia',
    Monad: 'monad',
    Mantra: 'mantra',
    Nillion: 'nillion',
    Kaia: 'kaia',
    Cardano: 'cardano',
    Sonic: 'sonic',
    Near: 'near',
    Aptos: 'aptos',
    Zenrock: 'zenrock',
    SolanaTestnet: 'solana-testnet',
    SonicTestnet: 'sonic-testnet',
    SomniaTestnet: 'somnia-testnet',
    EthereumSepoliaTestnet: 'ethereum-sepolia-testnet',
    MantraTestnet: 'mantra-testnet',
    MonadTestnet: 'monad-testnet',
    HederaTestnet: 'hedera-testnet',
    NillionTestnet: 'nillion-testnet',
    KaiaKairosTestnet: 'kaia-kairos-testnet',
    CardanoTestnet: 'cardano-testnet',
    ZenrockTestnet: 'zenrock-testnet'
} as const;
export type StakingNetwork = typeof StakingNetwork[keyof typeof StakingNetwork];


export function instanceOfStakingNetwork(value: any): boolean {
    for (const key in StakingNetwork) {
        if (Object.prototype.hasOwnProperty.call(StakingNetwork, key)) {
            if (StakingNetwork[key as keyof typeof StakingNetwork] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StakingNetworkFromJSON(json: any): StakingNetwork {
    return StakingNetworkFromJSONTyped(json, false);
}

export function StakingNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingNetwork {
    return json as StakingNetwork;
}

export function StakingNetworkToJSON(value?: StakingNetwork | null): any {
    return value as any;
}

export function StakingNetworkToJSONTyped(value: any, ignoreDiscriminator: boolean): StakingNetwork {
    return value as StakingNetwork;
}

