/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Token information
 * @export
 * @interface TokenInfo
 */
export interface TokenInfo {
    /**
     * Token symbol
     * @type {string}
     * @memberof TokenInfo
     */
    symbol: string;
    /**
     * Network identifier
     * @type {string}
     * @memberof TokenInfo
     */
    network: string;
    /**
     * Whether this is the native token
     * @type {boolean}
     * @memberof TokenInfo
     */
    _native: boolean;
    /**
     * Token denomination
     * @type {string}
     * @memberof TokenInfo
     */
    denomination: string;
    /**
     * Number of decimals
     * @type {number}
     * @memberof TokenInfo
     */
    decimals: number;
    /**
     * Token contract address (if applicable)
     * @type {string}
     * @memberof TokenInfo
     */
    tokenAddress?: string;
    /**
     * Whether this is on a testnet
     * @type {boolean}
     * @memberof TokenInfo
     */
    testnet: boolean;
}

/**
 * Check if a given object implements the TokenInfo interface.
 */
export function instanceOfTokenInfo(value: object): value is TokenInfo {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('_native' in value) || value['_native'] === undefined) return false;
    if (!('denomination' in value) || value['denomination'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('testnet' in value) || value['testnet'] === undefined) return false;
    return true;
}

export function TokenInfoFromJSON(json: any): TokenInfo {
    return TokenInfoFromJSONTyped(json, false);
}

export function TokenInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'network': json['network'],
        '_native': json['native'],
        'denomination': json['denomination'],
        'decimals': json['decimals'],
        'tokenAddress': json['tokenAddress'] == null ? undefined : json['tokenAddress'],
        'testnet': json['testnet'],
    };
}

export function TokenInfoToJSON(json: any): TokenInfo {
    return TokenInfoToJSONTyped(json, false);
}

export function TokenInfoToJSONTyped(value?: TokenInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'network': value['network'],
        'native': value['_native'],
        'denomination': value['denomination'],
        'decimals': value['decimals'],
        'tokenAddress': value['tokenAddress'],
        'testnet': value['testnet'],
    };
}

