/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';
import type { MultiTransactionResponse } from './MultiTransactionResponse';
import {
    MultiTransactionResponseFromJSON,
    MultiTransactionResponseFromJSONTyped,
    MultiTransactionResponseToJSON,
    MultiTransactionResponseToJSONTyped,
} from './MultiTransactionResponse';

/**
 * 
 * @export
 * @interface TransactionsResponse
 */
export interface TransactionsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TransactionsResponse
     */
    success: boolean;
    /**
     * 
     * @type {MultiTransactionResponse}
     * @memberof TransactionsResponse
     */
    data?: MultiTransactionResponse;
    /**
     * 
     * @type {ApiError}
     * @memberof TransactionsResponse
     */
    error?: ApiError;
}

/**
 * Check if a given object implements the TransactionsResponse interface.
 */
export function instanceOfTransactionsResponse(value: object): value is TransactionsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function TransactionsResponseFromJSON(json: any): TransactionsResponse {
    return TransactionsResponseFromJSONTyped(json, false);
}

export function TransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : MultiTransactionResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : ApiErrorFromJSON(json['error']),
    };
}

export function TransactionsResponseToJSON(json: any): TransactionsResponse {
    return TransactionsResponseToJSONTyped(json, false);
}

export function TransactionsResponseToJSONTyped(value?: TransactionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MultiTransactionResponseToJSON(value['data']),
        'error': ApiErrorToJSON(value['error']),
    };
}

