/* tslint:disable */
/* eslint-disable */
/**
 * stakeFi Developer API
 * API for creating unsigned staking transactions across multiple blockchain networks
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Unsigned transaction with both encoded and unencoded formats. The tx field contains the actual transaction object structure which varies by blockchain type.
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * The type of operation this transaction performs
     * @type {string}
     * @memberof Transaction
     */
    type: TransactionTypeEnum;
    /**
     * The blockchain type for this transaction
     * @type {string}
     * @memberof Transaction
     */
    transactionType: TransactionTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    encodingFormat: TransactionEncodingFormatEnum;
    /**
     * Blockchain-specific transaction object (see examples for structure)
     * @type {any}
     * @memberof Transaction
     */
    tx?: any | null;
    /**
     * Encoded transaction ready for broadcast
     * @type {string}
     * @memberof Transaction
     */
    encodedTx: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    description?: string;
}


/**
 * @export
 */
export const TransactionTypeEnum = {
    Stake: 'stake',
    Deposit: 'deposit',
    Delegate: 'delegate',
    Undelegate: 'undelegate',
    Approve: 'approve',
    Queue: 'queue',
    Activate: 'activate',
    Boost: 'boost',
    Lock: 'lock',
    Unlock: 'unlock',
    Withdraw: 'withdraw',
    Claim: 'claim',
    Compound: 'compound',
    Wrap: 'wrap'
} as const;
export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];

/**
 * @export
 */
export const TransactionTransactionTypeEnum = {
    Evm: 'evm',
    Cosmos: 'cosmos',
    Solana: 'solana',
    Aptos: 'aptos',
    Cardano: 'cardano',
    Near: 'near',
    SpaceAndTime: 'space and time',
    Supra: 'supra',
    Radix: 'radix',
    Chromia: 'chromia',
    Tron: 'tron',
    Sui: 'sui',
    Hedera: 'hedera'
} as const;
export type TransactionTransactionTypeEnum = typeof TransactionTransactionTypeEnum[keyof typeof TransactionTransactionTypeEnum];

/**
 * @export
 */
export const TransactionEncodingFormatEnum = {
    Hex: 'hex',
    Base64: 'base64',
    Json: 'json',
    Asn1: 'asn1'
} as const;
export type TransactionEncodingFormatEnum = typeof TransactionEncodingFormatEnum[keyof typeof TransactionEncodingFormatEnum];


/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('transactionType' in value) || value['transactionType'] === undefined) return false;
    if (!('encodingFormat' in value) || value['encodingFormat'] === undefined) return false;
    if (!('encodedTx' in value) || value['encodedTx'] === undefined) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'transactionType': json['transactionType'],
        'encodingFormat': json['encodingFormat'],
        'tx': json['tx'] == null ? undefined : json['tx'],
        'encodedTx': json['encodedTx'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TransactionToJSON(json: any): Transaction {
    return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Transaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'transactionType': value['transactionType'],
        'encodingFormat': value['encodingFormat'],
        'tx': value['tx'],
        'encodedTx': value['encodedTx'],
        'description': value['description'],
    };
}

