/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Network the validator runs on
 * @export
 * @interface ValidatorNetwork
 */
export interface ValidatorNetwork {
    /**
     * Network identifier
     * @type {string}
     * @memberof ValidatorNetwork
     */
    name: string;
    /**
     * Network type
     * @type {string}
     * @memberof ValidatorNetwork
     */
    type: ValidatorNetworkTypeEnum;
    /**
     * Native token
     * @type {string}
     * @memberof ValidatorNetwork
     */
    nativeToken: string;
    /**
     * Token symbol
     * @type {string}
     * @memberof ValidatorNetwork
     */
    tokenSymbol: string | null;
    /**
     * Token decimals
     * @type {number}
     * @memberof ValidatorNetwork
     */
    decimals: number | null;
}


/**
 * @export
 */
export const ValidatorNetworkTypeEnum = {
    Mainnet: 'mainnet',
    Testnet: 'testnet'
} as const;
export type ValidatorNetworkTypeEnum = typeof ValidatorNetworkTypeEnum[keyof typeof ValidatorNetworkTypeEnum];


/**
 * Check if a given object implements the ValidatorNetwork interface.
 */
export function instanceOfValidatorNetwork(value: object): value is ValidatorNetwork {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('nativeToken' in value) || value['nativeToken'] === undefined) return false;
    if (!('tokenSymbol' in value) || value['tokenSymbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    return true;
}

export function ValidatorNetworkFromJSON(json: any): ValidatorNetwork {
    return ValidatorNetworkFromJSONTyped(json, false);
}

export function ValidatorNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'nativeToken': json['nativeToken'],
        'tokenSymbol': json['tokenSymbol'],
        'decimals': json['decimals'],
    };
}

export function ValidatorNetworkToJSON(json: any): ValidatorNetwork {
    return ValidatorNetworkToJSONTyped(json, false);
}

export function ValidatorNetworkToJSONTyped(value?: ValidatorNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'nativeToken': value['nativeToken'],
        'tokenSymbol': value['tokenSymbol'],
        'decimals': value['decimals'],
    };
}

