/* tslint:disable */
/* eslint-disable */
/**
 * Anseta Developer API
 * Unified API for blockchain staking operations across multiple networks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidatorNetwork } from './ValidatorNetwork';
import {
    ValidatorNetworkFromJSON,
    ValidatorNetworkFromJSONTyped,
    ValidatorNetworkToJSON,
    ValidatorNetworkToJSONTyped,
} from './ValidatorNetwork';

/**
 * A validator available for delegation. validatorId is a UUID and is not the same value as validatorAddress; the history and rewards endpoints take the UUID.
 * @export
 * @interface Validator
 */
export interface Validator {
    /**
     * Validator identifier (UUID)
     * @type {string}
     * @memberof Validator
     */
    validatorId: string;
    /**
     * Validator address
     * @type {string}
     * @memberof Validator
     */
    validatorAddress: string;
    /**
     * Validator display name
     * @type {string}
     * @memberof Validator
     */
    moniker: string;
    /**
     * Validator status
     * @type {string}
     * @memberof Validator
     */
    status: string;
    /**
     * 
     * @type {ValidatorNetwork}
     * @memberof Validator
     */
    network: ValidatorNetwork;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    commissionRate?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    maxCommissionRate?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    maxCommissionChangeRate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Validator
     */
    publicDelegationEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    creationBlockNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    ownerAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    stakingContract?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    securityContact?: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    details?: string;
}

/**
 * Check if a given object implements the Validator interface.
 */
export function instanceOfValidator(value: object): value is Validator {
    if (!('validatorId' in value) || value['validatorId'] === undefined) return false;
    if (!('validatorAddress' in value) || value['validatorAddress'] === undefined) return false;
    if (!('moniker' in value) || value['moniker'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    return true;
}

export function ValidatorFromJSON(json: any): Validator {
    return ValidatorFromJSONTyped(json, false);
}

export function ValidatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Validator {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorId': json['validatorId'],
        'validatorAddress': json['validatorAddress'],
        'moniker': json['moniker'],
        'status': json['status'],
        'network': ValidatorNetworkFromJSON(json['network']),
        'commissionRate': json['commissionRate'] == null ? undefined : json['commissionRate'],
        'maxCommissionRate': json['maxCommissionRate'] == null ? undefined : json['maxCommissionRate'],
        'maxCommissionChangeRate': json['maxCommissionChangeRate'] == null ? undefined : json['maxCommissionChangeRate'],
        'publicDelegationEnabled': json['publicDelegationEnabled'] == null ? undefined : json['publicDelegationEnabled'],
        'creationBlockNumber': json['creationBlockNumber'] == null ? undefined : json['creationBlockNumber'],
        'ownerAddress': json['ownerAddress'] == null ? undefined : json['ownerAddress'],
        'stakingContract': json['stakingContract'] == null ? undefined : json['stakingContract'],
        'website': json['website'] == null ? undefined : json['website'],
        'securityContact': json['securityContact'] == null ? undefined : json['securityContact'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ValidatorToJSON(json: any): Validator {
    return ValidatorToJSONTyped(json, false);
}

export function ValidatorToJSONTyped(value?: Validator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorId': value['validatorId'],
        'validatorAddress': value['validatorAddress'],
        'moniker': value['moniker'],
        'status': value['status'],
        'network': ValidatorNetworkToJSON(value['network']),
        'commissionRate': value['commissionRate'],
        'maxCommissionRate': value['maxCommissionRate'],
        'maxCommissionChangeRate': value['maxCommissionChangeRate'],
        'publicDelegationEnabled': value['publicDelegationEnabled'],
        'creationBlockNumber': value['creationBlockNumber'],
        'ownerAddress': value['ownerAddress'],
        'stakingContract': value['stakingContract'],
        'website': value['website'],
        'securityContact': value['securityContact'],
        'details': value['details'],
    };
}

